title: !secret lovelace_street_name
views:
  # Security
  - path: security
    title: Security
    panel: false
    icon: mdi:shield-home
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - !include home/security/alarm_panel.yaml
          - !include home/security/occupancy.yaml
      - type: vertical-stack
        cards:
          - !include home/security/aarlo_front.yaml
          - !include home/security/aarlo_back.yaml
      - type: vertical-stack
        cards:
          - !include home/security/open_close.yaml
          - !include home/security/housekeeper.yaml
          - !include home/security/calamities.yaml
          - !include home/security/connectivity.yaml
  # Climate
  - title: Climate
    type: custom:masonry-layout
    path: climate
    icon: mdi:home-thermometer
    badges: []
    layout:
      min_height: 1
    cards:
      - type: vertical-stack
        cards:
          - !include home/climate/thermostat.yaml
      - type: vertical-stack
        cards:
          - !include home/climate/temperature.yaml
      - type: vertical-stack
        cards:
          - type: grid
            cards:
              - type: button
                name: Electric blanket – Bedroom
                tap_action:
                  action: toggle
                entity: switch.on_off_plug_in_unit_3
              - type: button
                name: Electric heater – Shed
                tap_action:
                  action: toggle
                entity: switch.smart_plug_5
              - type: button
                name: Boiler – Kitchen
                tap_action:
                  action: toggle
                entity: switch.smart_plug_9
              - type: button
                name: VOCOlinc – Living room
                tap_action:
                  action: toggle
                entity: humidifier.vocolinc_flb_living_room
  # Air-quality
  - title: Air-quality
    type: custom:masonry-layout
    path: air-quality
    icon: mdi:fan
    badges: []
    layout:
      min_height: 1
    cards:
      - type: vertical-stack
        cards:
          - !include home/air_quality/co2.yaml
          - !include home/air_quality/pm.yaml
      - !include home/air_quality/fans.yaml
      - !include home/air_quality/bathroom_fan.yaml
  # Lights
  - title: Lights
    path: lights
    icon: mdi:home-lightbulb-outline
    badges: []
    cards:
      - !include home/lights/rooms.yaml
      - type: vertical-stack
        cards:
          - !include home/lights/wakeup.yaml
          - type: button
            tap_action:
              action: call-service
              service: script.turn_on
              target:
                entity_id: script.lights_out
              data:
                variables:
                  activatedFrom: kitchen
              confirmation:
                text: Turn off all lights?
            show_state: false
            show_icon: true
            show_name: false
            icon_height: 48px
            icon: mdi:lightbulb-group-off
          - type: grid
            cards:
              - type: button
                tap_action:
                  action: toggle
                entity: input_boolean.fireplace
              - type: button
                tap_action:
                  action: toggle
                entity: light.hue_white_light_1
                icon: mdi:vanity-light
                name: Ensuite
              - type: button
                tap_action:
                  action: call-service
                  service: light.turn_on
                  data:
                    entity_id: light.attic
                    flash: short
                icon: hue:room-attic
                name: Blink Attic
          - !include home/lights/hue_scenes.yaml
      - !include home/lights/lux_downstairs.yaml
      - !include home/lights/lux_upstairs.yaml
  # Consumption
  - title: Consumption
    path: consumption
    icon: mdi:finance
    badges: []
    cards:
      - !include home/consumption/energy.yaml
      - !include home/consumption/gas.yaml
      - type: grid
        cards:
          - !include home/consumption/appliances/lights.yaml
          - !include home/consumption/appliances/ups.yaml
          - !include home/consumption/appliances/boiler_kitchen.yaml
          - !include home/consumption/appliances/dishwasher.yaml
          - !include home/consumption/appliances/television.yaml
          - !include home/consumption/appliances/sonair.yaml
          - !include home/consumption/appliances/washing_machine.yaml
          - !include home/consumption/appliances/dryer.yaml
          - !include home/consumption/appliances/airco_attic.yaml
          - !include home/consumption/appliances/airco_bedroom.yaml
          - !include home/consumption/appliances/heater_shed.yaml
        columns: 2
        square: false
  # Network
  - title: Network
    path: network
    icon: mdi:lan
    badges: []
    cards:
      - !include home/network/pi4.yaml
      - !include home/network/pi4_sandbox.yaml
      - !include home/network/bandwidth_ping.yaml
      - !include home/network/pihole.yaml
      - !include home/network/routers_dns.yaml
      - !include home/network/gammu.yaml
  # Weather
  - title: Weather
    path: weather
    icon: mdi:weather-partly-cloudy
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - !include home/weather/temperature.yaml
          - !include home/weather/sun.yaml
          - type: custom:sun-card
            card_mod:
              style: |
                ha-card div.sun-card-footer{
                  display: none;
                }
      - type: vertical-stack
        cards:
          - !include home/weather/wind.yaml
          - !include home/weather/rain.yaml
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - !include home/weather/wind_direction.yaml
              - !include home/weather/uv_index.yaml
          - !include home/weather/humidity_pressure.yaml
          - !include home/weather/forecast.yaml
  # Chores
  - icon: mdi:broom
    title: Chores
    path: chores
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - !include home/chores/neato_downstairs.yaml
              - !include home/chores/afvalwijzer.yaml
      - !include home/chores/neato_upstairs.yaml
  # Hobby
  - title: Hobby
    path: hobby
    icon: mdi:hammer-screwdriver
    badges: []
    cards:
      - !include home/hobby/prusa.yaml
  # Media
  - title: Media
    path: media
    icon: mdi:filmstrip
    badges: []
    cards:
      - !include home/media/shield_tv.yaml
      - type: media-control
        entity: media_player.pi0_speaker_bedroom
      - !include home/media/dvb.yaml
