- alias: 📹 | ⏰ Arm Arlo "Armed Home" (daily at 22:30)
  id: 093a7fa4-2045-4c7e-a8fb-2ff211c44213
  description: ""
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    # Only act if Arlo is currently disarmed (to prevent unintentionally
    # toggling from armed "Night" or "Away" to armed "Home")
    - condition: state
      entity_id: !secret aarlo_control_panel
      state: disarmed
  action:
    # Wait (indefinitely) for Aarlo to be connected – this can lead to race
    # conditions between this and the next two automations (which also wait
    # indefinitely). It beats not waiting at all though (in which case
    # connectivity issue at trigger time will surely cause the system to get
    # stuck in the wrong state).
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - service: alarm_control_panel.alarm_arm_home
      entity_id: !secret aarlo_control_panel
      data: {}
  mode: restart
- alias: 📹 | 🤖 Arm Arlo (following "Home Alarm")
  id: 6fcafedb-78df-4fa4-a7ac-80aec0750cd1
  description: ""
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - armed_away
        - armed_night
  condition: []
  action:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_night
          sequence:
            - service: alarm_control_panel.alarm_arm_night
              entity_id: !secret aarlo_control_panel
              data: {}
      # Armed "Away" is stricter than armed "Night", so we default to that...
      default:
        - service: alarm_control_panel.alarm_arm_away
          entity_id: !secret aarlo_control_panel
          data: {}
  mode: restart
- alias: 📹 | 🤖 Disarm Arlo (following "Home Alarm")
  id: 82789ffd-a7ef-476f-a51d-41ed4f32c30f
  description: ""
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  condition: []
  action:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: !secret aarlo_control_panel
  mode: restart
- alias: 📹 | ⏳ Pause Arlo "Armed Home" (timer started)
  id: ed2ae249-369f-4503-9122-21a5e49e1c21
  description: ""
  trigger:
    - platform: event
      event_type:
        - timer.started
        - timer.restarted
      event_data:
        entity_id: timer.aarlo_pause
  condition: []
  action:
    - choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: !secret aarlo_control_panel
                  state: armed_home
          sequence:
            - service: timer.cancel
              data:
                entity_id: timer.aarlo_pause
      default:
        - service: alarm_control_panel.alarm_disarm
          entity_id: !secret aarlo_control_panel
          data: {}
  mode: single
- alias: 📹 | ⏳ Resume Arlo "Armed Home" (timer ended)
  id: 71bb747a-25c5-416a-a98d-66c33789a702
  description: ""
  trigger:
    - platform: event
      event_type:
        - timer.finished
        - timer.paused
      event_data:
        entity_id: timer.aarlo_pause
  condition:
    - condition: state
      entity_id: !secret aarlo_control_panel
      state: disarmed
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: !secret aarlo_control_panel
      data: {}
  mode: single
- alias: 📹 | ⏰/🤖 Arlo snapshot (every 2 hours / Home Assistant start; "Home Alarm" state)
  id: 769a4449-f68b-4403-a09b-87b81cbe1581
  description: ""
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: time_pattern
      hours: /2
      minutes: 0
      seconds: 0
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - disarmed
        - armed_night
        - armed_away
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - camera.aarlo_back
            - camera.aarlo_front
          state: recording
  action:
    # Wait up to 5 minutes for Aarlo to be connected – to cope with the fact
    # that, at Home Assistant start, Aarlo is probably not connected yet...
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
      timeout: 300
      continue_on_timeout: false
    - service: aarlo.camera_request_snapshot
      data: {}
      entity_id:
        - camera.aarlo_back
        - camera.aarlo_front
  mode: single
  max_exceeded: silent
- alias: 📹 | ⏰ Arlo store daily garden snapshot (at dawn and dusk)
  id: e56ad77e-9f8e-43f7-9fe6-6b2678a86df6
  description: ""
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: camera.aarlo_back
          state: recording
  action:
    - service: aarlo.camera_request_snapshot_to_file
      data:
        filename: >-
          /config/var/aarlo/back-
            {{- now() | as_timestamp | timestamp_custom('%Y%m%d%H%M') -}}.jpg
      entity_id: camera.aarlo_back
  mode: single
