- alias: Arlo "Armed home"
  id: 093a7fa4-2045-4c7e-a8fb-2ff211c44213
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  triggers:
    - trigger: time
      at: "22:30:00"
  conditions:
    # Only act if Arlo is currently disarmed (to prevent unintentionally
    # toggling from armed "Night" or "Away" to armed "Home")
    - condition: state
      entity_id: !secret aarlo_control_panel
      state: disarmed
  actions:
    # Wait (indefinitely) for Aarlo to be connected – this can lead to race
    # conditions between this and the next two automations (which also wait
    # indefinitely). It beats not waiting at all though (in which case
    # connectivity issue at trigger time will surely cause the system to get
    # stuck in the wrong state).
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - action: alarm_control_panel.alarm_arm_home
      entity_id: !secret aarlo_control_panel
  mode: restart
- alias: Arm Arlo (following "Home Alarm")
  id: 6fcafedb-78df-4fa4-a7ac-80aec0750cd1
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - armed_away
        - armed_vacation
        - armed_night
  conditions: []
  actions:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_night
          sequence:
            - action: alarm_control_panel.alarm_arm_night
              entity_id: !secret aarlo_control_panel
      # Armed "Away" is stricter than armed "Night", so we default to that...
      default:
        - action: alarm_control_panel.alarm_arm_away
          entity_id: !secret aarlo_control_panel
  mode: restart
- alias: Disarm Arlo (following "Home Alarm")
  id: 82789ffd-a7ef-476f-a51d-41ed4f32c30f
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  triggers:
    - trigger: state
      id: alarm_disarmed
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
    # Fallback in case Home Alarm wasn't armed during the night
    - trigger: state
      id: everyone_awake
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
      # Slight delay to prevent race-condition (the regular trigger fires at
      # wake-up time too)
      for: "00:00:30"
  conditions:
    - condition: or
      conditions:
        # Regular trigger
        - condition: and
          conditions:
            - condition: trigger
              id: alarm_disarmed
            - condition: state
              entity_id: !secret aarlo_control_panel
              state:
                - armed_away
                - armed_night
        # Fallback trigger (only act if Arlo is "Armed home")
        - condition: and
          conditions:
            - condition: trigger
              id: everyone_awake
            - condition: state
              entity_id: !secret aarlo_control_panel
              state: armed_home
  actions:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - action: alarm_control_panel.alarm_disarm
      entity_id: !secret aarlo_control_panel
  mode: restart
- alias: Update "two-hour" snapshot
  id: 769a4449-f68b-4403-a09b-87b81cbe1581
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  triggers:
    - trigger: time_pattern
      hours: /2
      minutes: 0
      seconds: 0
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - disarmed
        - armed_night
        - armed_away
        - armed_vacation
  conditions: []
  actions:
    # Arlo should be connected; wait up to 10-minutes for Arlo to connect.
    # Prevent issues with the capture when Home Assistant was just (re)started,
    # _and_ copes with the (as of recent) unstable Arlo-connectivity...
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
      timeout: "00:10:00"
      continue_on_timeout: false
    - parallel:
        # Back camera
        - if:
            # Don't disturb an active recording session
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_back
                  state: recording
          then:
            - action: aarlo.camera_request_snapshot
              entity_id: camera.aarlo_back
        # Balcony camera
        - if:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_balcony
                  state: recording
          then:
            - action: aarlo.camera_request_snapshot
              entity_id: camera.aarlo_balcony
        # Front camera
        - sequence:
            # In case of a regular/timed snapshot, ensure at least five-minutes
            # have passed since the doorbell last rang (the four-minute time
            # delta is intentional as the sensor remains active for one-minute).
            # This prevents a race condition where we overwrite the doorbell
            # capture with a regular capture too quickly (and send out the wrong
            # capture in doorbell related notifications).
            - wait_template: >-
                {{
                  trigger.platform != 'time_pattern' or (
                    states.binary_sensor.vibration_43 is defined and
                    states.binary_sensor.vibration_43.last_changed <=
                      now() - timedelta(minutes=4)
                  )
                }}
              timeout: 300
              # if timer expires, update snapshot regardless
              continue_on_timeout: true
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_front
                  state: recording
            - action: aarlo.camera_request_snapshot
              entity_id: camera.aarlo_front
  mode: single
  max_exceeded: silent
- alias: Store daily snapshots
  id: e56ad77e-9f8e-43f7-9fe6-6b2678a86df6
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  triggers:
    - trigger: state
      id: dawn
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: state
      id: dusk
      entity_id: sensor.time_of_day
      from: day
      to: dusk
    - trigger: state
      id: noon
      entity_id: sun.sun
      attribute: rising
      from: true
      to: false
    - trigger: state
      id: midnight
      entity_id: sun.sun
      attribute: rising
      from: false
      to: true
  conditions: []
  actions:
    # Arlo should be connected; wait up to 10-minutes for Arlo to connect.
    # In order to cope with the (as of recent) unstable Arlo-connectivity...
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
      timeout: "00:10:00"
      continue_on_timeout: false
    - variables:
        filename: >-
          {{ trigger.id }}-{{-
            now() | as_timestamp | timestamp_custom('%Y%m%d%H%M')
          -}}.jpg
    - parallel:
        # Front
        - if:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_front
                  state: recording
          then:
            - action: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /gtx/var/aarlo-snapshots/daily/front-{{ filename }}
              entity_id: camera.aarlo_front
        # Back
        - if:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_back
                  state: recording
          then:
            - action: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /gtx/var/aarlo-snapshots/daily/back-{{ filename }}
              entity_id: camera.aarlo_back
        # Balcony
        - if:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_balcony
                  state: recording
          then:
            - action: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /gtx/var/aarlo-snapshots/daily/balcony-{{ filename }}
              entity_id: camera.aarlo_balcony
  mode: single
- alias: Store activity snapshot
  id: 4dbb8ad5-e671-4f72-ba30-70fe0a29932e
  triggers:
    - trigger: event
      event_type: aarlo_capture_updated
  conditions:
    # Prevent trigger in case of a manual snapshot (e.g., by another automation)
    - condition: state
      entity_id:
        - camera.aarlo_front
        - camera.aarlo_back
        - camera.aarlo_balcony
      state:
        - recording
        - recently active
      match: any
  actions:
    - variables:
        filename: >-
          -{{ now() | as_timestamp | timestamp_custom('%Y%m%d%H%M') }}.jpg
        time_of_day: >-
          {% set time_of_day = states('sensor.time_of_day') %}
          {% if time_of_day in ['day', 'dusk', 'night', 'dawn'] %}
            -{{ time_of_day }}
          {% else %}
            -unknown
          {% endif %}
    - parallel:
        # Front
        - if:
            - condition: state
              entity_id: camera.aarlo_front
              state:
                - recording
                - recently active
          then:
            - action: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_front', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'front' ~ time_of_day ~ filename }}
        # Back
        - if:
            - condition: state
              entity_id: camera.aarlo_back
              state:
                - recording
                - recently active
          then:
            - action: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_back', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'back' ~ time_of_day ~ filename }}
        # Balcony
        - if:
            - condition: state
              entity_id: camera.aarlo_balcony
              state:
                - recording
                - recently active
          then:
            - action: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_balcony', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'balcony' ~ time_of_day ~ filename }}
  mode: single
