- alias: 📹 | ⏰ Arm Arlo "Armed home" (daily at 22:30)
  id: 093a7fa4-2045-4c7e-a8fb-2ff211c44213
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    # Only act if Arlo is currently disarmed (to prevent unintentionally
    # toggling from armed "Night" or "Away" to armed "Home")
    - condition: state
      entity_id: !secret aarlo_control_panel
      state: disarmed
  action:
    # Wait (indefinitely) for Aarlo to be connected – this can lead to race
    # conditions between this and the next two automations (which also wait
    # indefinitely). It beats not waiting at all though (in which case
    # connectivity issue at trigger time will surely cause the system to get
    # stuck in the wrong state).
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - service: alarm_control_panel.alarm_arm_home
      entity_id: !secret aarlo_control_panel
  mode: restart
- alias: 📹 | 🤖 Arm Arlo (following "Home Alarm")
  id: 6fcafedb-78df-4fa4-a7ac-80aec0750cd1
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - armed_away
        - armed_vacation
        - armed_night
  condition: []
  action:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_night
          sequence:
            - service: alarm_control_panel.alarm_arm_night
              entity_id: !secret aarlo_control_panel
      # Armed "Away" is stricter than armed "Night", so we default to that...
      default:
        - service: alarm_control_panel.alarm_arm_away
          entity_id: !secret aarlo_control_panel
  mode: restart
- alias: 📹 | 🤖 Disarm Arlo (following "Home Alarm")
  id: 82789ffd-a7ef-476f-a51d-41ed4f32c30f
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: state
      id: alarm_disarmed
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
    # Fallback in case Home Alarm wasn't armed during the night
    - platform: state
      id: everyone_awake
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
      # Slight delay to prevent race-condition (the regular trigger fires at
      # wake-up time too)
      for: "00:00:30"
  condition:
    - condition: or
      conditions:
        # Regular trigger
        - condition: and
          conditions:
            - condition: trigger
              id: alarm_disarmed
            - condition: state
              entity_id: !secret aarlo_control_panel
              state:
                - armed_away
                - armed_night
        # Fallback trigger (only act if Arlo is "Armed home")
        - condition: and
          conditions:
            - condition: trigger
              id: everyone_awake
            - condition: state
              entity_id: !secret aarlo_control_panel
              state: armed_home
  action:
    # Wait (indefinitely) for Aarlo to be connected
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
    - service: alarm_control_panel.alarm_disarm
      entity_id: !secret aarlo_control_panel
  mode: restart
- alias: 📹 | ⏳ Pause Arlo "Armed home" (timer started)
  id: ed2ae249-369f-4503-9122-21a5e49e1c21
  trigger:
    - platform: event
      event_type:
        - timer.started
        - timer.restarted
      event_data:
        entity_id: timer.aarlo_pause
  condition: []
  action:
    - choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: !secret aarlo_control_panel
                  state: armed_home
          sequence:
            - service: timer.cancel
              data:
                entity_id: timer.aarlo_pause
      default:
        - service: alarm_control_panel.alarm_disarm
          entity_id: !secret aarlo_control_panel
  mode: single
- alias: 📹 | ⏳ Resume Arlo "Armed home" (timer ended)
  id: 71bb747a-25c5-416a-a98d-66c33789a702
  trigger:
    - platform: event
      event_type:
        - timer.finished
        - timer.paused
      event_data:
        entity_id: timer.aarlo_pause
  condition:
    - condition: state
      entity_id: !secret aarlo_control_panel
      state: disarmed
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: !secret aarlo_control_panel
  mode: single
- alias: >-
    📹 | ⏰/🤖 Snapshot (every 2 hours / HA start; "Home Alarm"-state;
    Arlo connected)
  id: 769a4449-f68b-4403-a09b-87b81cbe1581
  variables:
    aarlo_connected_sensor: !secret aarlo_connected_sensor
  trigger:
    - platform: time_pattern
      hours: /2
      minutes: 0
      seconds: 0
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - disarmed
        - armed_night
        - armed_away
        - armed_vacation
    # Other triggers can pre-empt this one; that's no problem. The script will
    # wait (a while) for Arlo to connect.
    - platform: state
      entity_id: !secret aarlo_connected_sensor
      to: "on"
  condition: []
  action:
    # Arlo should be connected; wait up to 5 minutes for Arlo to connect. Mainly
    # to cope with the fact that – at Home Assistant start – Arlo might not be
    # connected yet...
    - wait_template: >-
        {{ states(aarlo_connected_sensor) == 'on' }}
      timeout: 300
      continue_on_timeout: false
    # Back camera
    - choose:
        - conditions:
            # Don't disturb an active recording session
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_back
                  state: recording
          sequence:
            - service: aarlo.camera_request_snapshot
              entity_id: camera.aarlo_back
    # Balcony camera
    - choose:
        - conditions:
            # Don't disturb an active recording session
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_balcony
                  state: recording
          sequence:
            - service: aarlo.camera_request_snapshot
              entity_id: camera.aarlo_balcony
    # Front camera
    # In case of a regular/timed snapshot, ensure at least five minutes have
    # passed since the doorbell last rang (the 4-minute time delta is
    # intentional as the sensor remains active for 1 minute). This prevents a
    # "race condition" where we overwrite the doorbell capture with a regular
    # capture too quickly (and send out the wrong capture in doorbell related
    # notifications).
    - wait_template: >-
        {{
          trigger.platform != 'time_pattern' or (
            states.binary_sensor.vibration_43 is defined and
            states.binary_sensor.vibration_43.last_changed <=
              now() - timedelta(minutes=4)
          )
        }}
      timeout: 300
      # If timer expires, update snapshot regardless
      continue_on_timeout: true
    # Don't disturb an active recording session
    - condition: not
      conditions:
        - condition: state
          entity_id: camera.aarlo_front
          state: recording
    - service: aarlo.camera_request_snapshot
      entity_id: camera.aarlo_front
  mode: single
  max_exceeded: silent
- alias: 📹 | ⏰ Store daily snapshots (dawn, noon, dusk and midnight)
  id: e56ad77e-9f8e-43f7-9fe6-6b2678a86df6
  trigger:
    - platform: state
      id: dawn
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - platform: state
      id: dusk
      entity_id: sensor.time_of_day
      from: day
      to: dusk
    - platform: state
      id: noon
      entity_id: sun.sun
      attribute: rising
      from: true
      to: false
    - platform: state
      id: midnight
      entity_id: sun.sun
      attribute: rising
      from: false
      to: true
  condition: []
  action:
    - variables:
        filename: >-
          {{ trigger.id }}-{{-
            now() | as_timestamp | timestamp_custom('%Y%m%d%H%M')
          -}}.jpg
    # Front
    - choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_front
                  state: recording
          sequence:
            - service: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /config/var/aarlo/front-{{ filename }}
              entity_id: camera.aarlo_front
    # Back
    - choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_back
                  state: recording
          sequence:
            - service: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /config/var/aarlo/back-{{ filename }}
              entity_id: camera.aarlo_back
    # Balcony
    - choose:
        - conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: camera.aarlo_balcony
                  state: recording
          sequence:
            - service: aarlo.camera_request_snapshot_to_file
              data:
                filename: >-
                  /config/var/aarlo/balcony-{{ filename }}
              entity_id: camera.aarlo_balcony
  mode: single
- alias: 📹 | 🤖 Store activity snapshot (Arlo recording)
  id: 4dbb8ad5-e671-4f72-ba30-70fe0a29932e
  trigger:
    # This triggers if the capture was updated by an Arlo recording (i.e. the
    # camera was active and detected motion) – this event does _not_ fire when a
    # manual snapshot is taken (including the snapshots taken by other
    # automations)
    - platform: event
      event_type: aarlo_capture_updated
  condition: []
  action:
    - variables:
        filename: >-
          -{{ now() | as_timestamp | timestamp_custom('%Y%m%d%H%M') }}.jpg
        time_of_day: >-
          {% set time_of_day = states('sensor.time_of_day') %}
          {% if time_of_day in ['day', 'dusk', 'night', 'dawn'] %}
            -{{ time_of_day }}
          {% else %}
            -unknown
          {% endif %}
    - choose:
        # Front
        - conditions:
            - condition: state
              entity_id: camera.aarlo_front
              state:
                - recording
                - recently active
          sequence:
            - service: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_front', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'front' ~ time_of_day ~ filename }}
        # Back
        - conditions:
            - condition: state
              entity_id: camera.aarlo_back
              state:
                - recording
                - recently active
          sequence:
            - service: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_back', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'back' ~ time_of_day ~ filename }}
        # Balcony
        - conditions:
            - condition: state
              entity_id: camera.aarlo_balcony
              state:
                - recording
                - recently active
          sequence:
            - service: downloader.download_file
              data:
                url: >-
                  {{ state_attr('camera.aarlo_balcony', 'last_thumbnail') }}
                subdir: arlo/activity
                filename: >-
                  {{ 'balcony' ~ time_of_day ~ filename }}
  mode: parallel
  max: 4
