- alias: 🚨 Trigger alarm (door / window opened)
  id: cb55dcf5-9182-482c-9d3a-ce14387709b5
  description: ""
  trigger:
    - platform: state
      # Not using groups of sensors – They will trigger "off" → "on" if one of
      # their members transitions from "unavailable" → "on", which leads to false
      # alarms...
      # Furthermore, listing the individual entities is relevant as some
      # doors/windows might intentionally be left open – using a group would
      # obscure all further state transitions.
      entity_id:
        - binary_sensor.openclose_12
        - binary_sensor.openclose_16
        - binary_sensor.openclose_17
        - binary_sensor.openclose_33
        - binary_sensor.openclose_36
        - binary_sensor.openclose_18
        - binary_sensor.openclose_19
        - binary_sensor.openclose_20
        - binary_sensor.openclose_8
        - binary_sensor.openclose_14
        - binary_sensor.openclose_15
      from: "off"
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
  action:
    - service: alarm_control_panel.alarm_trigger
      data: {}
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: 🚨 | 🔊 Sound the alarm (alarm triggered)
  id: 714cfa44-bce7-41f8-be78-9891769fef74
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  condition: []
  action:
    - service: script.sirens
      data:
        mode: lselect
        ontime: 180
  mode: restart
- alias: 🚨 | 🔊 Stop sounding the alarm (alarm trigger ended)
  id: 06b3864d-3f70-45d7-96fa-6c30fa2576c2
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: triggered
  condition: []
  action:
    - service: script.sirens
      data:
        mode: none
  mode: single
- alias: 🚨 | 🕹️ Silence the alarm (Bedroom Smart Switches)
  id: 830121ea-907f-4234-be81-b4acce05c1bc
  description: ""
  trigger:
    # Bedside Smart Switches
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition:
    # Only act if the "Home Alarm" is triggered, the siren is sounding _and_
    # someone is home
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: triggered
    - condition: state
      entity_id: script.sirens
      state: "on"
    - condition: state
      entity_id: group.family
      state: home
  action:
    # Silence – continue blinking until the alarm state clears
    - service: script.sirens
      data:
        mode: blink
        ontime: 180
  mode: single
  max_exceeded: silent
- alias: 🚨 | 💡 Bedroom lights on (everyone asleep; alarm triggered)
  id: 45a353ab-e5c4-459c-a2ca-ac0d6a5e3aa8
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
    # Only useful if there's someone home (i.e. asleep in the bedroom)
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: light.turn_on
      data:
        brightness: 255
        kelvin: 6500
      entity_id: light.bedroom
  mode: single
- alias: 🚨 | 💡 Flash lights (pending alarm; Front / Kitchen door open)
  id: 4416cb36-8291-41ae-8c62-7a246fdc9d2d
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: pending
  condition: []
  action:
    - choose:
        - conditions:
            # Front door
            - condition: state
              entity_id: binary_sensor.openclose_16
              state: "on"
          sequence:
            - service: light.turn_on
              data:
                flash: long
                entity_id:
                  - light.hue_filament_bulb_1_5
                  - light.hue_filament_bulb_1_4
        - conditions:
            # Kitchen door
            - condition: state
              entity_id: binary_sensor.openclose_12
              state: "on"
          sequence:
            - service: light.turn_on
              data:
                flash: long
                entity_id:
                  - light.spot_4_kitchen_garden_side
                  - light.spot_3_kitchen
      default: []
  mode: single
- alias: 🚨 | 💡 Garden lights on (alarm pending)
  id: af18c5c4-4619-485f-8ff0-97ce63c7e42f
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: pending
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Active
    # To prevent the Garden lights from staying on unnecessarily, switch them
    # off if the alarm is disarmed or when it gets light outside. Only do this
    # if no-one is home (i.e. assuming a remote disarm) – if someone is home we
    # assume this is done manually...
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          to: disarmed
        - platform: state
          entity_id: sensor.time_of_day
          from: dawn
          to: day
    - condition: state
      entity_id: group.family
      state: not_home
    - service: light.turn_off
      data:
        entity_id: light.garden
  mode: restart
- alias: 🚨 | 📱 Notify on alarm pending
  id: 601cb512-c43b-4155-b58f-122441d49d22
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: pending
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          criticalNotification: true
          title: 🚨 Home Alarm pending!
          # The list of sensors includes doors/windows that were already open.
          # Filtering out those is more trouble than it's worth...
          message: >-
            The Home Alarm just got triggered!
            If not promptly disarmed, the alarm will sound...<br><br>
            One of the following sensor(s) triggered the alarm:
            <ul>
              <li>
                {{-
                  (expand('group.openclose_all') + expand('group.motion_all'))  |
                    selectattr('state', 'eq', 'on') | join('</li><li>', 'name')
                  -}}
              </li>
            </ul>
  mode: single
- alias: 🚨 | 📱 Notify on alarm sounding
  id: 05a2188b-8940-4311-adfb-bea75a792000
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Critical
          importance: high
          lovelaceDismiss: false
          criticalNotification: true
          title: 🚨 Home Alarm sounding!
          message: >-
            The Home Alarm is sounding – there's someone in the house!
  mode: single
- alias: 🚨 | 📱 Notify on alarm disarmed
  id: d06c2a3e-f1a7-41c2-9bf3-d29c6c352c93
  description: ""
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from:
        - pending
        - triggered
      to:
        - disarmed
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          lovelaceDismiss: false
          criticalNotification: true
          title: 🚨 Home Alarm disarmed
          message: >-
            The Home Alarm just got disarmed
            {%- if trigger is defined and
                trigger.to_state.context.user_id is defined -%}
              {%- set persons = states.person | selectattr(
                'attributes.user_id', 'eq', trigger.to_state.context.user_id
              ) | list -%}
              {%- if persons | count == 1
                %} by {{ persons[0].attributes.friendly_name }}
              {%- endif -%}
            {%- endif -%}.
- alias: 🚨 | 💡 Lights on (triggered alarm disarmed)
  id: 5132f575-5f3f-43e5-8720-8eddd8c66355
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: triggered
      to: disarmed
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    # Someone should be home _and_ have manually disarmed the alarm via the
    # Lovelace UI – this prevents the lights from switching on if the alarm is
    # disarmed remotely (and/or automatically)
    - condition: state
      entity_id: group.family
      state: home
    - condition: template
      value_template: >-
        {{ trigger.to_state.context.user_id is not none }}
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Bright (custom)
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Active
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Bright
