- alias: 🚨 | 💤 Alarm arm night (everyone asleep)
  id: c7465f32-cd4f-49e0-a675-4ef234a80eac
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.alarm_auto_arm_night
      state: "on"
    # Prevent overruling "Armed away"
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: >-
    🚨 | 💤 Alarm disarm and re-enable "Auto-arm at night" (everyone awake)
  id: 33aaf958-65a3-42ed-9b0a-07966a049482
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_auto_arm_night
          state: "off"
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
  action:
    - choose:
        # Re-enable "Auto-arm Home Alarm at night"
        - conditions:
            - condition: state
              entity_id: input_boolean.alarm_auto_arm_night
              state: "off"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.alarm_auto_arm_night
    # Prevent overruling "Armed away"
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: 🚨 | 🚗 Alarm arm away (everyone away)
  id: 4cb07e27-5af6-4a81-b51c-dc35372c3deb
  trigger:
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
      for: "00:05:00"
    # Fallback in case the Home Alarm is left in an incorrect state due to a
    # unexpected Home Assistant (re)start
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: group.family
      state: not_home
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state:
            - armed_away
            - armed_vacation
    - condition: state
      entity_id: input_boolean.housekeeper_present
      state: "off"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: 🚨 | 🚗 Alarm disarm (someone home)
  id: 1b7d2951-39c5-41d1-bcac-9acdf31c1173
  trigger:
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
  mode: single
# If the alarm gets disarmed when "everyone['s] asleep" and someone is/gets
# home, it's safe to assume not everyone's asleep anymore... 😉
- alias: >-
    🚨 | 💤 Everyone awake (alarm disarmed when «Everyone [at home] asleep»)
  id: daec5087-59f1-4307-9b8c-5739d579a97b
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
  action:
    # Should only run if someone is home. If no-one's home, wait up to five
    # minutes for a state change (the alarm might have been disabled manually;
    # wait for presence detection to catch up...)
    - if:
        - condition: state
          entity_id: group.family
          state: not_home
      then:
        - wait_for_trigger:
            - platform: state
              entity_id: group.family
              from: not_home
              to: home
          timeout: "00:05:00"
          continue_on_timeout: false
    - service: input_boolean.turn_off
      entity_id: input_boolean.everyone_asleep
  mode: single
# If the Home Alarm is "Armed Night" prior to "wakeup"-time, and "Everyone
# asleep" is not enabled, enable it. Relevant when one of us gets up early,
# leaves the house, and manually "arms night" the Home Alarm.
# Without this automation, "Everyone asleep" would remain off in those cases,
# causing the Home Alarm to not be aumatically disarmed at "wakeup"-time...
- alias: 🚨 | 💤 Everyone asleep (alarm armed night)
  id: 28f49e27-7c15-4eb9-95e4-509f48969362
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: arming
      to: armed_night
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
    # This should not happen after "wakeup"-time. The interval is intentionally
    # a bit broader to also capture the (unlikely, but not impossible) situation
    # where the Home Alarm is manually set to "Armed Night" prior to going to
    # bed.
    - condition: time
      after: "23:00:00"
      before: input_datetime.wakeup
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.everyone_asleep
  mode: single
- alias: 🚨 | 🧹 Alarm disarm for housekeeper ("Armed away/vacation")
  id: 3e6dc009-efd8-4c15-bb6d-52430aa7d32c
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeper_present
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
  action:
    - variables:
        alarm_state: >-
          {{ states('alarm_control_panel.home_alarm') }}
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    - wait_for_trigger:
        - platform: state
          entity_id: input_boolean.housekeeper_present
          from: "on"
          to: "off"
      timeout: "06:00:00"
      continue_on_timeout: true
    - condition: state
      entity_id: group.family
      state: not_home
    - if:
        - >-
          {{ alarm_state == 'armed_vacation' }}
      then:
        - service: alarm_control_panel.alarm_arm_vacation
          entity_id: alarm_control_panel.home_alarm
      else:
        - service: alarm_control_panel.alarm_arm_away
          entity_id: alarm_control_panel.home_alarm
  mode: single
