- alias: ðŸš¨ | ðŸ’¤ Alarm arm night (everyone asleep)
  id: c7465f32-cd4f-49e0-a675-4ef234a80eac
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.alarm_auto_arm_night
      state: "on"
    # Prevent overruling "Armed away"
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: >-
    ðŸš¨ | ðŸ’¤ Alarm disarm and re-enable "Auto-arm at night" (everyone awake)
  id: 33aaf958-65a3-42ed-9b0a-07966a049482
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_auto_arm_night
          state: "off"
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
  action:
    - choose:
        # Re-enable "Auto-arm Home Alarm at night"
        - conditions:
            - condition: state
              entity_id: input_boolean.alarm_auto_arm_night
              state: "off"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.alarm_auto_arm_night
    # Prevent overruling "Armed away"
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: ðŸš¨ | âœˆï¸ Alarm arm away (everyone away)
  id: 4cb07e27-5af6-4a81-b51c-dc35372c3deb
  trigger:
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
      for: "00:05:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_away
    - condition: state
      entity_id: input_boolean.housekeeper_present
      state: "off"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: ðŸš¨ | âœˆï¸ Alarm disarm (someone home)
  id: 1b7d2951-39c5-41d1-bcac-9acdf31c1173
  trigger:
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
  mode: single
# If the alarm gets disarmed when "everyone['s] asleep" and someone is/gets
# home, it's safe to assume not everyone's asleep anymore... ðŸ˜‰
- alias: >-
    ðŸš¨ | ðŸ’¤ Everyone awake (alarm disarmed when Â«everyone [at home] asleepÂ»)
  id: daec5087-59f1-4307-9b8c-5739d579a97b
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
  action:
    - choose:
        # Should only run if someone is home. If no-one's home, wait up to five
        # minutes for a state change (the alarm might have been disabled
        # manually; wait for presence detection to catch up...)
        - conditions:
            - condition: state
              entity_id: group.family
              state: not_home
          sequence:
            - wait_for_trigger:
                - platform: state
                  entity_id: group.family
                  from: not_home
                  to: home
              timeout: "00:05:00"
              continue_on_timeout: false
    - service: input_boolean.turn_off
      entity_id: input_boolean.everyone_asleep
  mode: single
- alias: ðŸš¨ | ðŸ§¹ Alarm disarm (housekeeper comes when everyone away)
  id: 3e6dc009-efd8-4c15-bb6d-52430aa7d32c
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeper_present
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: ðŸš¨ | ðŸ§¹ Alarm arm away (housekeeper leaves when everyone away)
  id: 5cf9fd2b-f126-4a13-a637-213be05d1cea
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeper_present
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
  mode: single
