- alias: 🚨 | ⏰ Alarm arm night (everyone asleep)
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.everyone_asleep
    to: "on"
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.home_alarm
    data: {}
  mode: single
- alias: 🚨 | ⏰ Alarm disarm (everyone awake)
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.everyone_asleep
    to: "off"
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret alarm_code
    entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: 🚨 | 🤖 Alarm arm away (everyone away)
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
    data: {}
  mode: single
- alias: 🚨 | 🤖 Alarm disarm (someone home)
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret alarm_code
    entity_id: alarm_control_panel.home_alarm
  mode: single
