- alias: 🚨 | 📱 Notify on doors/windows left open ("Armed away")
  id: c3684211-bceb-4256-8238-077f21798da1
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
  condition:
    - condition: state
      entity_id: group.openclose_all
      state: "on"
  action:
    - variables:
        doors_windows: >-
          {{
            expand('group.openclose_all') | selectattr('state', 'eq', 'on') |
            map(attribute='name') | list
          }}
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          criticalNotification: true
          title: 🚪 Doors and/or windows left open!
          message: >-
            {%- if doors_windows | length == 1 -%}
              {{ doors_windows[0] }} is still open
            {%- else -%}
              The following doors and/or windows are still open:
              <br><br>◾ {{
                doors_windows | join('<br>◾ ')
              -}}
            {%- endif -%}
- alias: 🚨 | 📱 Notify on "Armed away"
  id: e23e2cf8-502d-4e28-8758-9ab11b5fee14
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Notification
          criticalNotification: true
          title: 🛡️ Home Alarm armed
          message: >-
            The Home Alarm just changed into "Armed away"-mode.
- alias: 🚨 | 📱 Notify on alarm disarmed ("Armed away")
  id: a78d71df-f5a9-49f1-a584-18d5260e88db
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: disarmed
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Notification
          criticalNotification: true
          title: 🔓 Home Alarm disarmed
          message: >-
            The Home Alarm just got disarmed
            {%- set result = namespace(people=[]) -%}
            {%- for person in expand('group.family') |
                selectattr('state', '==', 'home') -%}
                  {# Firstname only; remove everything after first space #}
                  {%- set result.people = result.people +
                    [person.name | regex_replace(' .*$', '') ] -%}
            {%- endfor -%}
            {%- if result.people | length > 0
              %} – {{ result.people | join(' and ')
              }} {% if result.people | length > 1 -%}
                are home
              {%- else -%}
                is home
              {%- endif -%}
            {%- endif -%}.
- alias: 🚨 | 👋 Trigger alarm (motion detected; "Armed away")
  id: 358bd339-33e4-4c0a-a92e-0682346e48a1
  trigger:
    # Not all motion sensors are optimally positioned for intruder detection
    # (e.g. the one triggering the light in the toilet probably won't catch a
    # burglar). Still, if no-one is home, there's no harm in having all of them
    # trigger the alarm...
    - platform: state
      # N.B. This list of entities is duplicated further down
      entity_id:
        - binary_sensor.presence_50 # Basement
        - binary_sensor.presence_53 # Kitchen counter
        - binary_sensor.presence_60 # Toilet
        - binary_sensor.presence_63 # Wardrobe
        - binary_sensor.presence_68 # Bathroom
        - binary_sensor.presence_71 # Bathroom
        - binary_sensor.presence_91 # Attic stairs/hallway
        - binary_sensor.presence_92 # Attic stairs/hallway
        - binary_sensor.presence_105 # Kitchen counter
        - binary_sensor.presence_121 # Stairs
        - binary_sensor.presence_123 # Downstairs hallway
        - binary_sensor.presence_125 # Downstairs hallway
        - binary_sensor.presence_127 # Upstairs hallway
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    # Ignore motion sensor in Attic while Neato is active – Neato's LIDAR uses
    # infrared and thus triggers (PIR) motion sensors...
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_91
          state: "off"
        - condition: state
          entity_id: binary_sensor.neato_active_attic
          state: "off"
    # Ignore motion sensors on first floor while Neato is active
    - condition: or
      conditions:
        - condition: state
          entity_id:
            - binary_sensor.presence_63
            - binary_sensor.presence_127
          state: "off"
        - condition: state
          entity_id: binary_sensor.neato_active_first_floor
          state: "off"
  action:
    # Wait up to five minutes for either the same or another motion sensor to
    # trigger. This prevents false positives (e.g. due to Sun light or heat) –
    # if someone is really moving around the house it's highly likely they'll
    # trigger another sensor within this timeframe...
    # There remains a slight possibility for a false positive when the initial
    # trigger occurs while one of the Neato units is active. The below triggers
    # don't account for that – would make things overly complex.
    - wait_for_trigger:
        - platform: state
          entity_id:
            - binary_sensor.presence_50
            - binary_sensor.presence_53
            - binary_sensor.presence_60
            - binary_sensor.presence_63
            - binary_sensor.presence_68
            - binary_sensor.presence_71
            - binary_sensor.presence_91
            - binary_sensor.presence_92
            - binary_sensor.presence_105
            - binary_sensor.presence_121
            - binary_sensor.presence_123
            - binary_sensor.presence_125
            - binary_sensor.presence_127
          from: "off"
          to: "on"
        # Additionally, if the triggered sensor stays "on" for more than 2
        # minutes also assume it got triggered twice (if triggered once the
        # sensor stays "on" for 90 seconds at most)
        - platform: template
          value_template: >-
            {{ states(trigger.entity_id) == 'on' }}
          for: 120
      timeout: 300
      continue_on_timeout: false
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
  mode: single
  max_exceeded: silent
- alias: 🚨 | ⚡ Trigger alarm (power outage; "Armed away")
  id: c9c16198-8524-440f-99ea-0b447c68b798
  trigger:
    - platform: state
      entity_id: binary_sensor.power_outage
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    # A generic "alarm pending" persistent notification is also raised. Since
    # the power is out, that notification probably won't be received in time /
    # at all. As such, that notification does not factor in the possibility of
    # a power outage – this information is conveyed exclusively via the below
    # SMS.
    - service: script.sms_notification
      data:
        message: >-
          ⚡ Power outage at home!
          \nNo-one is home so the Home Alarm has been triggered as a precaution
          – it will start sounding in 30 seconds. To silence the alarm:
          \n\n✉️ #secret# alarm silence
          \n\nTo inspect the status of the house:
          \n\n✉️ #secret# status
  mode: single
- alias: 🚨 | 📱 Notify when back gate opened ("Armed away")
  id: b1825172-d7ab-4114-8c4d-6030c6bae7b6
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          tag: alert_away_back_gate
          criticalNotification: true
          title: 🚨 Back gate opened!
          message: >-
            The back gate was just opened!
            There could be someone in the garden – check the camera feed...
            {% if states('sensor.time_of_day') != 'day' -%}
              <br><br>As a precaution, the garden and downstairs lights have
              been automatically switched on – please check their state after
              resolving the incident...
            {% endif %}
    - choose:
        # Only send an SMS message when in Vacation-mode. This limits the number
        # of false alarms by only sending SMS messages when we're away from home
        # longer than during a normal working day.
        - conditions:
            - condition: state
              entity_id: binary_sensor.vacation_mode
              state: "on"
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.sms_notification
              data:
                variables:
                  message: >-
                    🚨 The back gate was just opened!
                    \nThere could be someone in the garden –
                    check the camera feed:
                    \n\n✉️ #secret# status camera
    # If the alarm is disarmed within 5 minutes, dismiss the notification as it
    # was a false positive. This is aligned with the false alarm timeout for the
    # Garden lights as defined in "📄 automations/alarm/alert.yaml".
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          from: armed_away
          to: disarmed
      timeout: "00:05:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: alert_away_back_gate
  mode: single
  max_exceeded: silent
- alias: 🚨 | 💡 Downstairs lights maximum brightness (back gate opened; "Armed away")
  id: 9684f5d2-8d26-429f-bb08-aa5deeb23c50
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  condition:
    # This automation (intentionally) doesn't have a lot of guard conditions
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Bright (custom)
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Active
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Bright
    - service: light.turn_on
      data:
        brightness: 255
        entity_id: light.hue_filament_bulb_1 # Light above the Kitchen door
    # The delay below is to prevent DoS-ing the system by rapidly opening and
    # closing the back gate...
    - delay: 60
    # A regular automation switches the inside lights (including the one outside
    # above the Kitchen door) off at dawn, so there's no need to account for
    # that here.
  mode: single
  max_exceeded: silent
- alias: 🚨 | 💡 Downstairs lights on ("Armed away" → disarmed; door open)
  id: 23900a05-e8bd-4296-a8fe-fdcaa53caedf
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: disarmed
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  action:
    # Wait five minutes for either the Front or Kitchen door to open – presence
    # detection might have disarmed the alarm earlier than one would've done
    # manually, so some extra slack is required...
    - wait_for_trigger:
        - platform: state
          entity_id:
            - binary_sensor.openclose_16 # Front door
            - binary_sensor.openclose_12 # Kitchen door
          from: "off"
          to: "on"
      timeout: "00:05:00"
      continue_on_timeout: false
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Ambiance
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Ambiance
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Evening
- alias: 🚨 | 💡 Downstairs lights on ("Armed away" → pending → disarmed)
  id: 84d125f9-e88c-4bce-81e7-6f08a04f5afe
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: pending
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          from: pending
          to: disarmed
      # Delay time for the pending → triggered transition is 30 seconds, so
      # after 60 seconds it's safe to give up
      timeout: 60
      continue_on_timeout: false
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Ambiance
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Ambiance
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Evening
