- alias: 🚨 | 📱 Notify on doors/windows left open ("Armed away")
  id: c3684211-bceb-4256-8238-077f21798da1
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
  condition:
    - condition: state
      entity_id: group.openclose_all
      state: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          criticalNotification: true
          title: 🚪 Doors and/or windows left open!
          message: >-
            The following doors and/or windows are still open:
            <br><br>◾ {{
              expand('group.openclose_all') | selectattr('state', 'eq', 'on') |
                join('<br>◾ ', 'name')
            -}}
- alias: 🚨 | 📱 Notify on "Armed away"
  id: e23e2cf8-502d-4e28-8758-9ab11b5fee14
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Notification
          criticalNotification: true
          title: 🛡️ Home Alarm armed
          message: >-
            The Home Alarm just changed into "Armed away"-mode.
- alias: 🚨 | 📱 Notify on "Disarmed"
  id: a78d71df-f5a9-49f1-a584-18d5260e88db
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: disarmed
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Notification
          criticalNotification: true
          title: 🔓 Home Alarm disarmed
          message: >-
            The Home Alarm just got disarmed
            {%- set result = namespace(people=[]) -%}
            {%- for person in expand('group.family') |
                selectattr('state', '==', 'home') -%}
                  {# Firstname only; remove everything after first space #}
                  {%- set result.people = result.people +
                    [person.name | regex_replace(' .*$', '') ] -%}
            {%- endfor -%}
            {%- if result.people | length > 0
              %} – {{ result.people | join(' and ')
              }} {% if result.people | length > 1 -%}
                are home
              {%- else -%}
                is home
              {%- endif -%}
            {%- endif -%}.
# Presence (i.e. motion) sensors are used to turn on lights – the sensors are
# not well-positioned for intruder detection. Still, if no-one is home, there's
# no harm in making them trigger the alarm...
- alias: 🚨 | 👋 Trigger alarm (motion detected; "Armed away")
  id: 358bd339-33e4-4c0a-a92e-0682346e48a1
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.presence_50
        - binary_sensor.presence_53
        - binary_sensor.presence_60
        - binary_sensor.presence_63
        - binary_sensor.presence_68
        - binary_sensor.presence_71
        - binary_sensor.presence_91
        - binary_sensor.presence_92
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    # Ignore motion sensor in Attic while Neato is active
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_91
          state: "off"
        - condition: not
          conditions:
            - condition: time
              after: "11:30:00"
              before: "14:30:00"
              weekday: [mon, thu] # yamllint disable-line rule:brackets
    # Ignore motion sensor on first floor while Neato is active
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_63
          state: "off"
        - condition: not
          conditions:
            - condition: or
              conditions:
                - condition: time
                  after: "11:00:00"
                  before: "16:00:00"
                  weekday: mon
                - condition: time
                  after: "13:00:00"
                  before: "18:00:00"
                  weekday: thu
  action:
    - service: alarm_control_panel.alarm_trigger
      data: {}
      entity_id: alarm_control_panel.home_alarm
  mode: single
- alias: 🚨 | ⚡ Trigger alarm (power outage; "Armed away")
  id: c9c16198-8524-440f-99ea-0b447c68b798
  trigger:
    - platform: state
      entity_id: binary_sensor.power_outage
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      data: {}
      entity_id: alarm_control_panel.home_alarm
    # A generic "alarm pending" persistent notification is also raised. Since
    # the power is out, that notification probably won't be received in time /
    # at all. As such, that notification does not factor in the possibility of
    # a power outage – this information is conveyed exclusively via the below
    # SMS.
    - service: script.sms_notification
      data:
        message: >-
          ⚡ Power outage at home!
          \nNo-one is home so the Home Alarm has been triggered as a precaution
          – it will start sounding in 30 seconds. To silence the alarm:
          \n\n✉️ #secret# alarm silence
          \n\nTo inspect the status of the house:
          \n\n✉️ #secret# status
  mode: single
- alias: 🚨 | 📱 Notify when back gate opened ("Armed away")
  id: b1825172-d7ab-4114-8c4d-6030c6bae7b6
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: home alarm
          channel: Alert
          tag: alert_away_back_gate
          criticalNotification: true
          title: 🚨 Back gate opened!
          message: >-
            The back gate was just opened!
            There could be someone in the garden – check the camera feed...
            {% if states('sensor.time_of_day') != 'day' -%}
              <br><br>As a precaution, the garden and downstairs lights might
              have been automatically switched on – please check them after
              resolving the incident...
            {% endif %}
    - choose:
        # Only send an SMS message if the alarm has been armed for *more* than
        # 12 hours. This limits the number of false positives by only sending
        # SMS messages when we're away from home longer than during a normal
        # working day (e.g. weekend trip or vacation).
        - conditions:
            - condition: template
              value_template: >-
                {%
                  if states.alarm_control_panel.home_alarm.last_changed
                    is defined
                %}
                  {{
                    states.alarm_control_panel.home_alarm.last_changed <
                      now() - timedelta(hours=12)
                  }}
                {# Err on the side of caution #}
                {% else %}
                  true
                {% endif %}
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.sms_notification
              data:
                variables:
                  message: >-
                    🚨 The back gate was just opened!
                    \nThere could be someone in the garden –
                    check the camera feed:
                    \n\n✉️ #secret# status camera
    # If the alarm is disarmed within 2 minutes, dismiss the notification as it
    # was a false positive
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          from: armed_away
          to: disarmed
      timeout: "00:02:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: alert_away_back_gate
  mode: single
  max_exceeded: silent
- alias: 🚨 | 💡 Lights on when back gate opened ("Armed away")
  id: 9684f5d2-8d26-429f-bb08-aa5deeb23c50
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Active
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Bright (custom)
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Active
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Evening
    # Wait for 2 minutes to ensure this is not a false positive
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          from: armed_away
          to: disarmed
      timeout: "00:02:00"
      continue_on_timeout: true
    - choose:
        # In case of false positive, switch the garden lights back to a more
        # agreeable setting
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger.platform == 'state' }}
          sequence:
            - service: hue.hue_activate_scene
              data:
                group_name: Garden
                scene_name: Ambiance
      # In case it is _not_ a false positive, prevent the Garden lights from
      # staying on indefinitely. Switch them off when it gets light outside –\
      # the inside lights will have already been switched off by a "regular"
      # automation at this point...
      default:
        - wait_for_trigger:
            - platform: state
              entity_id: sensor.time_of_day
              from: dawn
              to: day
        - service: light.turn_off
          data:
            entity_id: light.garden
  mode: restart
- alias: 🚨 | 💡 Hallway and Kitchen lights on ("Armed away" → disarmed; door open)
  id: 23900a05-e8bd-4296-a8fe-fdcaa53caedf
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: disarmed
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: or
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: "off"
        - condition: state
          entity_id: light.hallway
          state: "off"
  action:
    # Wait five minutes for either the Front or Kitchen door to open – presence
    # detection might have disarmed the alarm earlier than one would've done
    # manually, so some extra slack is required...
    - wait_for_trigger:
        - platform: state
          entity_id:
            - binary_sensor.openclose_16 # Front door
            - binary_sensor.openclose_12 # Kitchen door
          from: "off"
          to: "on"
      timeout: "00:05:00"
      continue_on_timeout: false
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Evening
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Ambiance
- alias: 🚨 | 💡 Hallway and Kitchen lights on ("Armed away" → pending → disarmed)
  id: 84d125f9-e88c-4bce-81e7-6f08a04f5afe
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: armed_away
      to: pending
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: or
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: "off"
        - condition: state
          entity_id: light.hallway
          state: "off"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          from: pending
          to: disarmed
      # Delay time for the pending → triggered transition is 30 seconds, so
      # after 60 seconds it's safe to give up
      timeout: 60
      continue_on_timeout: false
    - service: hue.hue_activate_scene
      data:
        group_name: Hallway
        scene_name: Evening
    - service: hue.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Ambiance
