- alias: Flash indoor lights
  id: 4416cb36-8291-41ae-8c62-7a246fdc9d2d
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: pending
  conditions: []
  actions:
    - parallel:
        # Front door opened – assumes the door isn't rapidly closed again (which
        # is also fine, it would only prevent the visual trigger warning)
        - if:
            - condition: state
              entity_id: binary_sensor.openclose_16
              state: "on"
          then:
            - action: light.turn_on
              data:
                flash: long
                entity_id:
                  - light.front_hallway
                  - light.back_hallway
        # Kitchen door opened
        - if:
            - condition: state
              entity_id: binary_sensor.openclose_12
              state: "on"
          then:
            - action: light.turn_on
              data:
                flash: long
                entity_id:
                  - light.spot_4_kitchen_garden_side
                  - light.spot_3_kitchen
        # Hallway/staircase motion detected (primarily relevant when "Armed
        # night", so only considered if someone is home)
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.motion_hallway
                  state: "on"
                - condition: state
                  entity_id: group.motion_attic
                  state: "on"
            - condition: state
              entity_id: group.family
              state: home
          then:
            - action: light.turn_on
              data:
                flash: long
                entity_id:
                  - light.hallway
                  - light.attic
            # The Attic staircase relay doesn't support flash – instead of
            # rapidly toggling the relay (*click*, *click*, *click*, *click*),
            # switch it off and gently flash the lights in the Attic proper to
            # reach roughly the same effect...
            - action: light.turn_off
              data:
                entity_id: light.attic_hallway
  mode: single
- alias: Front and Back door to maximum brightness
  id: 1aa3f46d-2703-419b-829c-64ee68e461a0
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: pending
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.front_back_door_bright
    # Turn the lights off if the alarm disarms
    - wait_for_trigger:
        - trigger: state
          id: disarmed
          entity_id: alarm_control_panel.home_alarm
          to: disarmed
        # Short-circuit if the light is switched off
        - trigger: state
          id: abort
          entity_id: light.front_back_door
          to: "off"
      timeout: "24:00:00"
      continue_on_timeout: false
    - condition: template
      value_template: >-
        {{ wait.trigger.id != 'abort' }}
    - action: light.turn_off
      data:
        entity_id: light.front_back_door
  mode: restart
- alias: Garden lights to maximum brightness
  id: b937fe69-27ce-49dd-b720-4fb34907ba66
  trigger:
    - trigger: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_night
        - armed_away
        - armed_vacation
  action:
    - parallel:
        - action: scene.turn_on
          target:
            entity_id: scene.garden_active
        - action: light.turn_on
          data:
            brightness: 255
            entity_id: light.hue_filament_bulb_1 # Light above the Kitchen door
    # Wait for 5-minutes to ensure this is not a false alarm
    - wait_for_trigger:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          to: disarmed
        # Short-circuit if the alarm gets triggered
        - trigger: state
          id: abort
          entity_id: alarm_control_panel.home_alarm
          to: triggered
      timeout: "00:05:00"
      continue_on_timeout: false
    # In case of false alarm, switch the Garden lights back to a more
    # agreeable setting
    - condition: template
      value_template: >-
        {{ wait.trigger.id != 'abort' }}
    - parallel:
        - action: scene.turn_on
          target:
            entity_id: scene.garden_ambiance
        - action: light.turn_on
          data:
            brightness: 75
            entity_id: light.hue_filament_bulb_1
  mode: single
  max_exceeded: silent
- alias: All indoor lights to maximum brightness
  id: af18c5c4-4619-485f-8ff0-97ce63c7e42f
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  actions:
    - action: scene.turn_on
      target:
        entity_id:
          - scene.living_room_active
          - scene.kitchen_bright_custom
          - scene.hallway_concentrate
          - scene.garden_active
          - scene.bedroom_concentrate
          - scene.bathroom_concentrate
          - scene.wardrobe_bright
          - scene.guestroom_concentrate
          - scene.attic_concentrate
    - action: light.turn_on
      data:
        entity_id: light.attic_hallway
    # Wait for the alarm to disarm or for dawn
    - wait_for_trigger:
        - trigger: state
          id: disarmed
          entity_id: alarm_control_panel.home_alarm
          to: disarmed
        - trigger: state
          entity_id: sensor.time_of_day
          from: night
          to: dawn
      timeout: "24:00:00"
      continue_on_timeout: false
    - choose:
        # If the alarm is disarmed from the tablet in the Kitchen, or someone is
        # home when it gets disarmed, keep all lights on – switch some of them
        # to a more agreeable setting though.
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger.id == 'disarmed' }}
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.family
                  state: home
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger.to_state.context.user_id ==
                        tablet_kitchen_user_id
                    }}
          sequence:
            - action: scene.turn_on
              target:
                entity_id:
                  - scene.living_room_active
                  - scene.kitchen_bright_custom
                  - scene.hallway_read
                  - scene.garden_ambiance
                  - scene.bedroom_bright
                  - scene.guestroom_read
                  - scene.attic_bright
            - action: light.turn_off
              data:
                entity_id:
                  - light.bathroom
                  - light.wardrobe
                  - light.attic_hallway
      # Otherwise, switch the house back to regular "Ambiance"/Evening-mode.
      # An automation in "📄 automations/lights/dawn.yaml" switches off all
      # "Ambiance"/Evening-mode lights just after sunrise. By switching the
      # house back to this mode when the alarm is disarmed _or_ at dawn (which
      # is well _before_ sunrise), we ensure all lights are properly switched
      # off after sunrise (without duplicating any logic).
      default:
        - action: scene.turn_on
          target:
            entity_id:
              - scene.living_room_ambiance
              - scene.kitchen_ambiance
              - scene.hallway_evening
              - scene.garden_ambiance
              - scene.guestroom_relax
        - action: light.turn_off
          data:
            entity_id:
              - light.bedroom
              - light.bathroom
              - light.wardrobe
              - light.attic
              - light.attic_hallway
  mode: single
- alias: Downstairs lights maximum brightness
  id: 9684f5d2-8d26-429f-bb08-aa5deeb23c50
  triggers:
    - trigger: state
      entity_id: binary_sensor.openclose_34
      from: "off"
      to: "on"
  conditions:
    # This automation (intentionally) doesn't have a lot of guard conditions
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
  actions:
    - parallel:
        - action: scene.turn_on
          target:
            entity_id: scene.kitchen_bright_custom
        - action: scene.turn_on
          target:
            entity_id: scene.living_room_active
        - action: scene.turn_on
          target:
            entity_id: scene.hallway_concentrate
    # The delay below is to prevent DoS-ing the system by rapidly opening and
    # closing the back gate...
    - delay: 60
    # A regular automation switches the inside lights off at dawn, so there's no
    # need to account for that here.
  mode: single
  max_exceeded: silent
