- alias: 🚨 | 📣 Test the sirens (1st Monday of the month at 12:00)
  id: 6125cbba-0fd0-448a-917e-10f00402c32f
  description: ""
  trigger:
    - platform: time
      at: "11:50:00"
  condition:
    # First Monday of the month
    - condition: template
      value_template: >-
        {{ now().isoweekday() == 1 and now().day <= 7 }}
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Alert
          group: home alarm
          tag: siren_test
          title: 📣 Home Alarm siren will sound at 12:00:30
          message: >-
            To test the sirens, they will sound for 1 second followed by a 10
            second delay and then sound for 2 seconds. After this, all alarm
            devices' lights will blink for 3 minutes to allow for a visual
            inspection...<br><br>
            Additionally, directly after the sirens stop sounding you should
            receive an SMS message from Home Assistant allowing you to validate
            the SMS notification service is working as intended...
    # Wait for 10 minutes and 30 seconds – this ensures our test coincides with
    # the monthly test of the public alarm sirens in The Netherlands. These
    # sirens are tested every first Monday of the month at 12:00 for 1 minute
    # and 26 seconds.
    - delay: "00:10:30"
    # First set mode "select" (which sounds and blinks for 1 second); wait 10
    # seconds; set mode "lselect" with "ontime" 10 (sound and blink for 10
    # seconds) and after 2 seconds set mode "none" (which should stop the sound
    # and blink – testing that silencing the alarm also works). Finally, set
    # mode "blink" for 3 minutes to allow for a visual inspection of the alarm
    # alarm devices.
    - service: script.sirens
      data:
        mode: select
    - delay: 10
    - service: script.turn_on
      target:
        entity_id: script.sirens
      data:
        variables:
          mode: lselect
          ontime: 10
    - delay: 2
    - service: script.sirens
      data:
        mode: none
    - delay: 2
    # Send SMS without blocking script's execution
    - service: script.turn_on
      target:
        entity_id: script.sms_notification
      data:
        variables:
          targetDevices: all
          message: >-
            🧪 SMS notification service test!
            \nPlease respond to this message to validate Home Assistant's SMS
            response capability:
            \n\n✉️ #secret# ping?
    - service: script.sirens
      data:
        mode: blink
        ontime: 180
    # Once the test is over, dismiss the notification
    - service: persistent_notification.dismiss
      data:
        notification_id: siren_test
