- alias: ✈️ | 🛡️ Enable Holiday-mode ("Armed away" ⏰ > 16-hours)
  id: c8b73e92-cc5f-4090-8c1f-cac4d6377630
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
      for: "16:00:00"
    - platform: homeassistant
      id: start
      event: start
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    # As this automation has a rather long-running trigger, a secondary trigger
    # on Home Assistant start is provided to ensure restarts don't interfer with
    # the logic: If Home Assistant starts while the alarm is "Armed Away", wait
    # for 16-hours for it to move away from that state. If that does *not*
    # happen, toggle on Holiday-mode...
    - if:
        - condition: trigger
          id: start
      then:
        - wait_for_trigger:
            - platform: state
              entity_id: alarm_control_panel.home_alarm
              from: armed_away
          timeout: "16:00:00"
          continue_on_timeout: false
    - service: alarm_control_panel.alarm_arm_vacation
      entity_id: alarm_control_panel.home_alarm
