proseWrap: always
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      # I have prose wrap set to "always" in VS Code's settings (mainly with an
      # eye on Markdown) – prefer to have it disabled for YAML-files.
      # Especially relevant in this repository as there's a lot of Jinja2 in the
      # Home Assistant configuration I'd like Prettier to leave alone.
      proseWrap: preserve
  - files:
      - TODO
      - NOTES
    options:
      parser: markdown
