yaml-files:
  - "*.yaml"

ignore: |
  /.cloud
  /.storage
  /blueprints
  /custom_components
  /known_devices.yaml

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: non-empty
  colons: disable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  hyphens: disable
  indentation: disable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings:
    required: only-when-needed
  trailing-spaces: disable
  truthy: enable
