- platform: group
  name: Attic hallway
  unique_id: 2cb6deb0-459e-4837-aef1-e7cead101792
  entities:
    - light.attic_hallway_down
    - light.attic_hallway_up
- platform: group
  name: Fireplace
  unique_id: 1d73f495-bba4-4d6c-a5b5-e7494a7c00d5
  entities:
    - light.fireplace_1_living_room
    - light.fireplace_2_living_room
