- platform: group
  name: Attic hallway
  entities:
    - light.smart_relay_3
    - light.smart_relay_4
# Used by the Hue scene heuristic in "📄 templates/hue_scenes.yaml" to determine
# the state of each Hue room/zone and to enumerate the number of lights on.
# These groups are defined explicitly (i.e., not relying the room/zone "lights"
# provided by the Hue API) in order to exclude all non-Signify bulbs – those
# tend to bug out quite a bit and wreak havoc with the heuristic...
- platform: group
  name: Hue Group – Living room
  entities:
    - light.hue_filament_bulb_1_3
    - light.fireplace_1_living_room
    - light.fireplace_2_living_room
    - light.hue_aura_living_room
    - light.hue_iris_1
    - light.screen_left_living_room
    - light.screen_right_living_room
    - light.wall_garden_left_living_room
    - light.wall_garden_right_living_room
- platform: group
  name: Hue Group – Kitchen
  entities:
    - light.color_spot_1_kitchen
    - light.color_spot_2_kitchen
    - light.hue_color_spot_1
    - light.hue_color_spot_2_2
    - light.hue_color_spot_1_3
    - light.hue_color_spot_1_2
    - light.hue_color_spot_2
    - light.hue_lightstrip_plus_1
    - light.hue_lightstrip_plus_1_3
    - light.hue_lightstrip_plus_1_2
    - light.spot_1_kitchen_hallway_side
    - light.spot_2_kitchen
    - light.spot_3_kitchen
    - light.spot_4_kitchen_garden_side
- platform: group
  name: Hue Group – Kitchen counter & cupboards
  entities:
    - light.hue_color_spot_2_2
    - light.hue_color_spot_1_3
    - light.hue_color_spot_1_2
    - light.hue_color_spot_2
- platform: group
  name: Hue Group – Garden
  entities:
    - light.hue_outdoor_wall_1
    - light.outdoor_lightstrip_garden
    - light.hue_outdoor_wall_1_2
    - light.shed_wall_garden
    - light.hue_ambiance_spot_1
    - light.outdoor_spot_garden
    - light.hue_outdoor_spot_1
