# Arlo
- platform: aarlo
  monitored_conditions:
  - total_cameras
  - last_capture
  - recent_activity
  - captured_today
  - battery_level
  - signal_strength

# 92929 OV
- platform: dutch_public_transport_api
  name: 9292 OV Einhoven Centraal
  station: eindhoven/bushalte-evoluon
  destination: Eindhoven Station
  show_future_departures: 1
- platform: dutch_public_transport_api
  name: 9292 OV Einhoven Airport
  station: eindhoven/bushalte-evoluon
  destination: Airport via P+R Meerhoven
  show_future_departures: 1

# Media
- platform: history_stats
  name: NVIDIA Shield TV playing (today)
  entity_id: media_player.nvidia_shield_tv
  state: 'playing'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

# DSMR (Slimme Meter)
- platform: dsmr
  host: pi0-dsmr.sgraastra
  port: 2001
  dsmr_version: 5
- platform: template
  sensors:
    daily_energy:
      friendly_name: Daily energy
      unit_of_measurement: kWh
      value_template: >
        {{
          states('sensor.daily_energy_offpeak')|float + states('sensor.daily_energy_peak')|float
        }}
    monthly_energy:
      friendly_name: Monthly energy
      unit_of_measurement: kWh
      value_template: >
        {{
          states('sensor.monthly_energy_offpeak')|float + states('sensor.monthly_energy_peak')|float
        }}

# Pi4
- platform: snmp
  name: 'Pi4 1-minute load'
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{ value | multiply(25) | round(1) }}'
- platform: snmp
  name: 'Pi4 CPU temperature'
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.8072.9999.9999.314.1
  version: 2c
  accept_errors: true
  unit_of_measurement: '°C'
  value_template: '{{ (value|float/1000) | round(1) }}'
- platform: snmp
  name: 'Pi4 memAvailReal (raw)'
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.6.0
  version: 2c
  accept_errors: true
  unit_of_measurement: 'KiB'
- platform: snmp
  name: 'Pi4 memCached (raw)'
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.14.0
  version: 2c
  accept_errors: true
  unit_of_measurement: 'KiB'
- platform: snmp
  name: 'Pi4 memBuffer (raw)'
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.15.0
  version: 2c
  accept_errors: true
  unit_of_measurement: 'KiB'
- platform: template
  sensors:
    pi4_memory_available:
      value_template: >
        {{ ((
              (states('sensor.pi4_memavailreal_raw')|int) +
              (states('sensor.pi4_memcached_raw')|int) +
              (states('sensor.pi4_membuffer_raw')|int)
            )|float/1000) | round(0)
        }}
      unit_of_measurement: 'MiB'
      friendly_name: 'Pi4 memory available'

# Google DNS
- platform: template
  sensors:
    google_dns_roundtrip_time:
      value_template: "{{ state_attr('binary_sensor.google_dns_ping', 'round_trip_time_avg') }}"
      friendly_name: 'Google DNS roundtrip time'
      unit_of_measurement: 'ms'

# DD-WRT-1
- platform: snmp
  name: 'DD-WRT-1 1-minute load'
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{ value | multiply(50) | round(1) }}'
- platform: snmp
  name: 'DD-WRT-1 WAN in (total octets)'
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.10.5
  version: '2c'
  accept_errors: true
- platform: snmp
  name: 'DD-WRT-1 WAN out (total octets)'
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.16.5
  version: '2c'
  accept_errors: true
- platform: derivative
  source: sensor.dd_wrt_1_wan_in_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN in (bps)
- platform: derivative
  source: sensor.dd_wrt_1_wan_out_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN OUT (bps)
- platform: template
  sensors:
    dd_wrt_1_wan_in_mbps:
      value_template:  "{{ [((states('sensor.dd_wrt_1_wan_in_bps')|float*8)/1000000)|round(2),0]|max }}"
      unit_of_measurement: 'Mbps'
      friendly_name: 'DD-WRT-1 WAN in (Mbps)'
    dd_wrt_1_wan_out_mbps:
      value_template:  "{{ [((states('sensor.dd_wrt_1_wan_out_bps')|float*8)/1000000)|round(2),0]|max }}"
      unit_of_measurement: 'Mbps'
      friendly_name: 'DD-WRT-1 WAN out (Mbps)'

# DD-WRT-2
- platform: snmp
  name: 'DD-WRT-2 1-minute load'
  host: dd-wrt-2.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{ value | multiply(50) | round(1) }}'

# Pi-hole
- platform: snmp
  name: 'Pi-hole 1-minute load'
  host: pi-hole.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{ value | multiply(100) | round(1) }}'
