# Airco – tado° (combination of HomeKit and online integration)
#
# Basic scheduling is handled by the tado° app/service. The "Away"-mode logic
# is shared with the (heating) thermostat. The below automations deal with
# enabling/disabling the tado° schedule based on outside temperature.
#
# The tado° airco schedule is quite aggressive – constant active cooling is
# required to keep temperatures down. When the outside temperature drops, inside
# temperature remains high; this causes the airco schedule to keep cooling.
# Although pleasant, this is costly and less needed...
# As such, a secondary "schedule" is enforced through the below automations.
# It switches off the main tado° schedule when the outside temperature passes
# through certain thresholds.

- alias: ❄️ | ⏰ Resume Airco schedule (daily at 01:00)
  id: 63196195-97ca-473b-860d-1394b54ea6ed
  description: ""
  trigger:
    - platform: time
      at: "01:00:00"
  condition:
    # Manual/secondary toggle to allow the schedule to be re-enabled
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_attic_ac
      attribute: preset_mode
      state: home
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_attic_ac
          state: auto
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic_ac
- alias: ❄️ | ⏰ Suspend Airco schedule (daily at 09:00 when 🌡️ < 15ºC)
  id: 7a6b6d1d-4da4-430e-bb98-b18c489b5fd9
  description: ""
  trigger:
    # Pre-empt schedule change – trigger slightly before 09:00
    - platform: time
      at: "08:59:00"
  condition:
    - condition: state
      entity_id: climate.tado_attic_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_attic_ac
      state: auto
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 15.0
  action:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.tado_attic_ac
- alias: ❄️ | ⏰ Suspend Airco schedule (daily at 14:00 when 🌡️ < 22ºC)
  id: 75a786cf-b211-45f3-9ec0-db227ae708fa
  description: ""
  trigger:
    # Pre-empt schedule change – trigger slightly before 14:00
    - platform: time
      at: "13:59:00"
  condition:
    - condition: state
      entity_id: climate.tado_attic_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_attic_ac
      state: auto
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 22.0
  action:
    - service: climate.turn_off
      data: {}
      target:
        entity_id: climate.tado_attic_ac
- alias: ❄️ | ⏰ Resume Airco schedule (daily at 14:00 when 🌡️ > 22ºC)
  id: 64786e0a-e5d7-4586-9011-ffc256d28bda
  description: ""
  trigger:
    # Pre-empt schedule change – trigger slightly before 14:00
    - platform: time
      at: "13:59:00"
  condition:
    - condition: state
      entity_id: climate.tado_attic_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_attic_ac
      state: "off"
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 22.0
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic_ac
