- alias: 🤖 | 🌡️ Attic heating on (Attic lights on)
  description: ''
  trigger:
  - platform: state
    entity_id: light.attic
    from: 'off'
    to: 'on'
    for: 00:05:00
  condition:
  # Follow the main (Living room) thermostat's setting
  - condition: numeric_state
    entity_id: sensor.tado_smart_thermostat_setpoint
    above: 18.0
  - condition: state
    entity_id: climate.tado_smart_thermostat
    state: heat
  action:
  - service: climate.set_temperature
    data:
      temperature: 21.0
    entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: 🤖 | 🌡️ Attic heating off (Attic lights off)
  description: ''
  trigger:
  - platform: state
    entity_id: light.attic
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 12.0
    entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: ⏰ | 🌡️ Attic heating off (weekdays when lights remain off)
  description: ''
  trigger:
  - platform: time
    at: "09:00:00"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  # Only relevant if the Attic radiator is actively heating
  - condition: numeric_state
    entity_id: sensor.tado_smart_radiator_attic_setpoint
    above: 18.0
  - condition: state
    entity_id: sensor.tado_smart_radiator_attic_mode
    state: heat
  # Don't continue if the Attic light is already switched on...
  - condition: state
    entity_id: light.attic
    state: 'off'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id: light.attic
      to: 'on'
    timeout: 01:30:00
    continue_on_timeout: true
  # Only continue (i.e. switch the radiator off) if the timer expired (i.e. the
  # light in the Attic was not switched on within 90 minutes)
  - condition: template
    value_template: >-
      {{ wait.trigger == 'none' }}
  - service: climate.set_temperature
    data:
      temperature: 12.0
    entity_id: climate.tado_smart_radiator_attic
  mode: single
