- alias: 🤖 | 🌡️ Attic heating on (Attic lights on)
  description: ''
  trigger:
  - platform: state
    entity_id: light.attic
    from: 'off'
    to: 'on'
    for: 00:05:00
  condition:
  - condition: numeric_state
    entity_id: sensor.tado_smart_thermostat_setpoint
    above: 18.0
  - condition: state
    entity_id: climate.tado_smart_thermostat
    state: heat
  action:
  - service: climate.set_temperature
    data:
      temperature: 20.5
    entity_id: climate.thermostat_29
  mode: single
- alias: 🤖 | 🌡️ Attic heating off (Attic lights off)
  description: ''
  trigger:
  - platform: state
    entity_id: light.attic
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 15.0
    entity_id: climate.thermostat_29
  mode: single
- alias: ⏰ | 🌡️ Attic heating on (weekdays at 08:30 when someone home)
  description: ''
  trigger:
  - platform: time
    at: 08:30:00
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: climate.tado_smart_thermostat
    state: heat
  action:
  - service: climate.set_temperature
    data:
      temperature: 20.5
    entity_id: climate.thermostat_29
  - wait_for_trigger:
    - platform: state
      entity_id: light.attic
      to: 'on'
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
    timeout: 01:30:00
    continue_on_timeout: true
  # Abort (i.e. leave the heating on) if the light in the Attic is switched on
  # within 90 minutes. Otherwise (including the "no-one home" anymore short-
  # circuit) switch the heating back off...
  - condition: template
    value_template: >-
      {{
        wait.trigger.entity_id != 'light.state'
      }}
  - service: climate.set_temperature
    data:
      temperature: 15.0
    entity_id: climate.thermostat_29
  mode: single
