- alias: Attic radiator on
  id: e5978d8a-cfec-4b8d-a78d-03e973de84ae
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_attic
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: binary_sensor.openclose_33 # Attic window
      state: "off"
    # Only act if the main (Living room) thermostat is on
    - condition: numeric_state
      entity_id: sensor.tado_smart_thermostat_setpoint
      above: 16.0
    - condition: state
      entity_id: climate.tado_smart_thermostat
      state: heat
  action:
    - action: climate.set_temperature
      data:
        temperature: 21.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: Attic radiator retain setpoint
  id: 4e9442c0-9b22-441a-9f3c-13fee3cedd52
  # This is primarily to prevent the tado°-schedule from switching the Attic
  # heating off on weekdays at 19:00 (while the Attic is still occupied). Manual
  # adjustments also trigger this automation, but since it only triggers below
  # 18°, manual temperature adjustments are generally unaffected...
  triggers:
    - trigger: numeric_state
      entity_id: sensor.tado_smart_radiator_attic_setpoint
      below: 18.0
  conditions:
    - condition: state
      entity_id: binary_sensor.occupancy_attic
      state: "on"
    - condition: state
      entity_id: binary_sensor.openclose_33 # Attic window
      state: "off"
    # Only act if the main (Living room) thermostat is on
    - condition: numeric_state
      entity_id: sensor.tado_smart_thermostat_setpoint
      above: 16.0
    - condition: state
      entity_id: climate.tado_smart_thermostat
      state: heat
  actions:
    - action: climate.set_temperature
      data:
        temperature: 21.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: Attic radiator off
  id: 19c32aa8-2c41-4026-ba1a-798a34a2bf6b
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_attic
      from: "on"
      to: "off"
  conditions:
    - condition: state
      entity_id: climate.tado_smart_radiator_attic
      state: heat
  actions:
    - action: climate.set_temperature
      data:
        temperature: 12.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: Attic radiator off
  id: fc16d0c4-d9ea-48da-ad28-ca9f83065f5d
  triggers:
    - trigger: time
      at: "09:00:00"
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    # Only relevant if the Attic radiator is on
    - condition: numeric_state
      entity_id: sensor.tado_smart_radiator_attic_setpoint
      above: 18.0
    - condition: state
      entity_id: climate.tado_smart_radiator_attic
      state: heat
    # Waiting for the Attic to get occupied only makes sense when the Attic is
    # unoccupied to begin with...
    - condition: state
      entity_id: binary_sensor.occupancy_attic
      state: "off"
  actions:
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.occupancy_attic
          from: "off"
          to: "on"
      timeout: "01:00:00"
      continue_on_timeout: true
    # Only continue (i.e. switch the radiator off) if the timer expired (i.e.
    # the light in the Attic was not switched on within 60 minutes)
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - action: climate.set_temperature
      data:
        temperature: 12.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: Attic radiator off
  id: d8587843-f45f-48cc-811a-e7dbf346a31f
  triggers:
    # When tado° transitions from Away- to Home-mode, it restores all schedules
    # and thus potentially switches the Attic radiator on...
    - trigger: state
      entity_id: climate.tado_attic
      attribute: preset_mode
      from: away
      to: home
      # Hold the state for a short while to ensure HomeKit (which we use for
      # radiator control) catches up with the online state...
      for: "00:02:00"
  conditions:
    # Only relevant if the Attic radiator is on
    - condition: numeric_state
      entity_id: sensor.tado_smart_radiator_attic_setpoint
      above: 18.0
    - condition: state
      entity_id: climate.tado_smart_radiator_attic
      state: heat
  actions:
    - action: climate.set_temperature
      data:
        temperature: 12.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
- alias: Attic radiator off
  id: 529a20b2-7b28-4cf7-84c3-72c5d851d853
  triggers:
    # Mainly intended as a fail-safe to ensure the Attic radiator (which can
    # control the cv-boiler by itself) doesn't stay on throughout the night...
    - trigger: numeric_state
      entity_id: sensor.tado_smart_thermostat_setpoint
      below: 16.0
  conditions:
    # Only relevant if the Attic radiator is on
    - condition: numeric_state
      entity_id: sensor.tado_smart_radiator_attic_setpoint
      above: 18.0
    - condition: state
      entity_id: climate.tado_smart_radiator_attic
      state: heat
  actions:
    - action: climate.set_temperature
      data:
        temperature: 12.0
      entity_id: climate.tado_smart_radiator_attic
  mode: single
# Keep the operation mode of the Attic radiator in-sync with the main (i.e.
# Living room) thermostat. This ensures the Living room thermostat is always
# the leading indicator of whether the heating/boiler is on. Using the Tado
# integration to ensure the operation mode change persists, which is not
# possible via HomeKit.
- alias: Attic radiator operation mode
  id: da50685d-7a61-470c-96d0-07c6ee84a53b
  triggers:
    - trigger: state
      entity_id:
        - climate.tado_living_room
        # Recently, Tado has started bugging out, and occasionally switches
        # itself momentarily to "heat" or "auto" for no apparent reason – this
        # additional trigger corrects for this abhorrent behaviour...
        - climate.tado_attic
      # Explicitly specify relevant HVAC modes to prevent the automation from
      # running at every (irrelevant) attribute change.
      to:
        - auto
        - heat
        - "off"
  conditions:
    # Only run if the states differ
    - condition: template
      value_template: >-
        {{ states('climate.tado_living_room') != states('climate.tado_attic') }}
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: >-
          {{ states('climate.tado_living_room') }}
      target:
        entity_id: climate.tado_attic
  mode: single
- alias: Airco – Attic enable schedule
  id: f3bd94fa-4646-4c70-9e0d-fd7288579bfe
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_attic
      from: "off"
      to: "on"
    - trigger: state
      entity_id: input_boolean.airco_active
      from: "off"
      to: "on"
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: binary_sensor.occupancy_attic
      state: "on"
    - condition: state
      entity_id: binary_sensor.openclose_33 # Attic window
      state: "off"
    - condition: numeric_state
      entity_id: sensor.temperature_3
      above: 25.0
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_attic_ac
          state: auto
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic_ac
  mode: single
# The "Attic off"-automation is broader than the "Attic on"-automation. It turns
# the airco off unconditionally (i.e. if it's not already off) – this to prevent
# leaving the airco on unintentionally...
- alias: Airco – Attic off
  id: 426b173e-cef1-4e6d-a7f0-a1249db7c745
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_attic
      from: "on"
      to: "off"
    - trigger: state
      entity_id: input_boolean.airco_active
      from: "on"
      to: "off"
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_attic_ac
          state: "off"
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_attic_ac
  mode: single
# Opposite side of this is in "bedroom.yaml"
- alias: Airco – Attic off
  id: 8f2ec70c-bc8b-4569-abce-a4161ec384f4
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_attic
      from: "off"
      to: cool
  conditions:
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
  actions:
    # Pull the handbrake
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_smart_ac_control_attic
    - action: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          rooms: attic
          priority: attention
          message: >-
            The airco in the Bedroom is switched on; please switch it off before
            switching on the airco in the Attic...
- alias: Airco – Attic enable schedule
  id: 0669c656-3142-4572-8e4b-30e9c65b4761
  triggers:
    - trigger: numeric_state
      entity_id: sensor.temperature_3
      above: 25.0
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: binary_sensor.occupancy_attic
      state: "on"
    - condition: state
      entity_id: binary_sensor.openclose_33 # Attic window
      state: "off"
    - condition: state
      entity_id: climate.tado_attic_ac
      state: "off"
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic_ac
  mode: single
- alias: Airco – Attic off
  id: bc7a77e4-3fad-4b78-a2aa-91b0e507681a
  triggers:
    - trigger: time
      at: "09:00:00"
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_attic_ac
      state: auto
    - condition: state
      entity_id: binary_sensor.occupancy_attic
      state: "off"
  actions:
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.occupancy_attic
          from: "off"
          to: "on"
      timeout: "00:30:00"
      continue_on_timeout: true
    # Only continue (i.e. switch the airco off) if the timer expired (i.e. the
    # Attic was not occupied within half an hour)
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_attic_ac
  mode: single
- alias: Airco – Attic restore schedule
  id: 63196195-97ca-473b-860d-1394b54ea6ed
  triggers:
    - trigger: time
      at: "01:00:00"
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_attic_ac
      attribute: preset_mode
      state: home
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_attic_ac
          state: auto
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic_ac
- alias: Attic radiator restore schedule
  id: 2024e4d4-ea94-4109-a217-37dcd6b653fd
  triggers:
    - trigger: time
      at: "01:00:00"
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: climate.tado_living_room
      state: auto
    - condition: state
      entity_id: climate.tado_living_room
      attribute: preset_mode
      state: home
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_attic
          state: auto
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_attic
- alias: Airco – Attic off
  id: 717e590f-b4d7-4cf9-8efd-c540f5ea3298
  triggers:
    - trigger: state
      entity_id: binary_sensor.openclose_33
      from: "off"
      to: "on"
    # Using HomeKit to trigger – when using a schedule, the online tadoº
    # integration doesn't trigger to "cool" (instead, it stays in "auto") so
    # it's of no use here...
    - trigger: state
      entity_id: climate.tado_smart_ac_control_attic
      from: "off"
      to: cool
      # Wait 30-seconds for the online tadoº integration to catch-up — moving
      # too fast might cause the "physical" commands to the Airco to criss-cross
      # with the "virtual" state, leaving the entire thing messed up
      for: "00:00:30"
  conditions:
    - condition: state
      entity_id: binary_sensor.openclose_33
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_attic
      state: cool
  actions:
    - variables:
        # Take state from the (online) tadoº integration (so we can distinguish
        # between "cool" and "auto" hvac-modes)
        last_hvac_mode: >-
          {{ states('climate.tado_attic_ac') }}
        last_swing_mode: >-
          {{ state_attr('climate.tado_attic_ac', 'swing_mode') }}
        # HomeKit updates much faster, so prefer that for the temperature
        last_temperature: >-
          {{ state_attr('climate.tado_smart_ac_control_attic', 'temperature') }}
    # Control via (online) tadoº integration – this ensures a planned schedule
    # change doesn't overrule the off-state (and thus switches on the airco
    # regardless of the fact the window is still open)
    - action: climate.turn_off
      target:
        entity_id: climate.tado_attic_ac
    - action: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Notification
          group: climate
          tag: airco_attic_window
          action_1: Switch off Airco
          title: ❄️ Attic airco switched off – the window is open
          message: >-
            Please close the window in the Attic to allow the airco to switch
            back to {{ last_hvac_mode }}-mode...
    - wait_for_trigger:
        # Action from mobile notification
        - trigger: event
          id: switch_off
          event_type: mobile_app_notification_action
          event_data:
            action: ACTION_1_airco_attic_window
        # Window closed
        - trigger: state
          entity_id: binary_sensor.openclose_33
          from: "on"
          to: "off"
      timeout: "06:00:00"
      continue_on_timeout: true
    - action: persistent_notification.dismiss
      data:
        notification_id: airco_attic_window
    # Only restore the Airco's state if the window was closed, otherwise keep
    # the Airco switched off. Other triggers will attempt to restore the Airco
    # to auto-mode later on (all guarded by "window closed"-conditions).
    - condition: template
      value_template: >-
        {{
          wait.trigger is not none and wait.trigger.id != 'switch_off'
        }}
    # Use the (online) tadoº integration to restore so we can properly restore
    # hvac- and swing-modes (even though it's slow to update its state, commands
    # come through without delay)...
    - choose:
        # No need to restore swing-mode or temperature in "auto" hvac-mode
        - conditions:
            - condition: template
              value_template: >-
                {{ last_hvac_mode == 'auto' }}
          sequence:
            - action: climate.set_hvac_mode
              data:
                hvac_mode: >-
                  {{ last_hvac_mode }}
              target:
                entity_id: climate.tado_attic_ac
      default:
        - action: script.climate_set_operating_mode
          data:
            entity_id: climate.tado_attic_ac
            hvac_mode: >-
              {{ last_hvac_mode }}
            swing_mode: >-
              {{ last_swing_mode }}
            temperature: >-
              {{ last_temperature }}
  mode: restart
- alias: Attic radiator off
  id: 336491f4-871a-4ac2-8e9e-f4f83cd123f6
  triggers:
    - trigger: state
      entity_id: binary_sensor.openclose_33
      from: "off"
      to: "on"
    - trigger: state
      entity_id: climate.tado_smart_radiator_attic
      from: "off"
      to: heat
  condition:
    - condition: state
      entity_id: binary_sensor.openclose_33
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_radiator_attic
      state: heat
  action:
    - variables:
        last_hvac_mode: >-
          {{ states('climate.tado_attic') }}
        last_temperature: >-
          {{ state_attr('climate.tado_smart_radiator_attic', 'temperature') }}
    - action: climate.turn_off
      target:
        entity_id: climate.tado_attic
    - action: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Notification
          group: climate
          tag: radiator_attic_window
          action_1: Switch off radiator
          title: 🌡️ Attic radiator switched off – the window is open
          message: >-
            Please close the window in the Attic to allow the radiator to switch
            back to {{ last_hvac_mode }}-mode...
    - wait_for_trigger:
        - trigger: event
          id: switch_off
          event_type: mobile_app_notification_action
          event_data:
            action: ACTION_1_radiator_attic_window
        - trigger: state
          entity_id: binary_sensor.openclose_33
          from: "on"
          to: "off"
      timeout: "06:00:00"
      continue_on_timeout: true
    - action: persistent_notification.dismiss
      data:
        notification_id: radiator_attic_window
    - condition: template
      value_template: >-
        {{
          wait.trigger is not none and wait.trigger.id != 'switch_off'
        }}
    - choose:
        - conditions:
            - condition: template
              value_template: >-
                {{ last_hvac_mode == 'auto' }}
          sequence:
            - action: climate.set_hvac_mode
              data:
                hvac_mode: >-
                  {{ last_hvac_mode }}
              target:
                entity_id: climate.tado_attic
      default:
        - action: script.climate_set_operating_mode
          data:
            entity_id: climate.tado_attic
            hvac_mode: >-
              {{ last_hvac_mode }}
            temperature: >-
              {{ last_temperature }}
  mode: restart
