# Restore twice daily from potential overrides that happen further down in this
# file
- alias: Airco – Bedroom restore schedule
  id: bdfe854c-79d1-474d-a30e-84a3e99e1672
  triggers:
    - trigger: time
      at: "01:00:00"
    - trigger: time
      at: "11:00:00"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_bedroom_ac
      attribute: preset_mode
      state: home
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_bedroom_ac
          state: auto
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_bedroom_ac
  mode: single
# tado° Is scheduled to switch on daily at 22:30 – the below is in case someone
# goes to bed early
- alias: Airco – Bedroom on
  id: d32f9d2b-c66c-41d2-85dd-b3049a077dce
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_bed
      from: "off"
      to: "on"
      for: "00:05:00"
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: "off"
    # Don't trigger after going to bed, nor in the morning after waking up...
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: idle
  actions:
    # Control properly via the tado°-integration – the settings below are
    # identical to what is scheduled to happen at 22:30
    - action: climate.set_temperature
      data:
        temperature: 20
        hvac_mode: cool
      target:
        entity_id: climate.tado_bedroom_ac
    - delay: 2
    - action: climate.set_fan_mode
      data:
        fan_mode: low
      target:
        entity_id: climate.tado_bedroom_ac
  mode: single
# tado° Is scheduled to switch off daily at 09:00/10:00 (weekdays versus
# weekend) – the below is in case we get out of bed early
- alias: Airco – Bedroom off
  id: 6767ad63-9f59-4d70-b304-45cafd75442e
  triggers:
    - trigger: state
      entity_id: light.bedroom
      from: "on"
      to: "off"
      for: "00:05:00"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
    # Only act when the wakeup "grace-time" timer is running — this ensures it's
    # in the morning _after_ the wakeup-alarm has sounded
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: active
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_bedroom_ac
  mode: single
# Prevent the Bedroom- and Attic-aircos from running simultaneously – doesn't
# blow a fuse, but leaves too little margin for comfort. There's an opposite
# automation defined in "attic.yaml".
- alias: Airco – Bedroom off
  id: 620de186-54bc-4c1c-a3df-761186db44c9
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
  conditions:
    - condition: state
      entity_id: climate.tado_smart_ac_control_attic
      state: cool
  actions:
    # Pull the handbrake
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_smart_ac_control_bedroom
    - action: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          rooms: bedroom
          priority: attention
          message: >-
            The airco in the Attic is switched on; please switch it off before
            switching on the airco in the Bedroom...
  mode: single
- alias: Airco – Bedroom nighttime settings
  id: f8b4d2e6-9e72-43be-839e-c4c6b10c6082
  # Triggering is bi-directional: Either when someone goes to bed and the airco
  # is on, _or_ when the airco goes on and there's someone in the bed
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_bed
      from: "off"
      to: "on"
      for: "00:05:00"
    - trigger: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
      for: "00:00:30"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.occupancy_bed
          state: "on"
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "on"
        - condition: state
          entity_id: script.lights_out
          state: "on"
  actions:
    # Adjust fan-speed based on current Bedroom-temperature – as I also want to
    # adjust the airflow direction (and prefer the four fan speeds offered by
    # the IR remote over the three offered by the tado°-integration), we send
    # (composite) IR-commands directly.
    # Switching the airco off via tado° is not a use-case: The airco manages
    # itself just fine (and I don't mind it running silently in the background).
    # As the airco is higher up in the room than the tado°-unit, it'll never
    # actually bring the temperature to the setpoint (20° C) from tado°'s
    # perspective...
    - if:
        condition: numeric_state
        # The HomeKit-backed temperature-sensor of the tado° unit itself is
        # most appropriate in this case
        entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
        above: 24
      then:
        # Further boost when it's really hot inside
        - if:
            condition: numeric_state
            entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
            above: 26
          then:
            - action: remote.send_command
              data:
                command: fan_4_bottom_right_20
                device: airco
              target:
                entity_id: remote.broadlink_bedroom_remote
          else:
            - action: remote.send_command
              data:
                command: fan_3_bottom_right_20
                device: airco
              target:
                entity_id: remote.broadlink_bedroom_remote
      else:
        - action: remote.send_command
          data:
            command: fan_2_bottom_right_20
            device: airco
          target:
            entity_id: remote.broadlink_bedroom_remote
  mode: single
- alias: Airco – Bedroom nighttime reduce airflow
  id: ac143f4e-ef0a-4da5-a975-9793c81a4373
  triggers:
    - trigger: numeric_state
      entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
      below: 22.5
      for: "00:05:00"
    # Fallback in case tado° messes with the fan-speed
    - trigger: state
      entity_id: climate.tado_bedroom_ac
      attribute: fan_modes
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.occupancy_bed
          state: "on"
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "on"
        - condition: state
          entity_id: script.lights_out
          state: "on"
  actions:
    - if:
        condition: numeric_state
        entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
        below: 22.5
      then:
        - action: remote.send_command
          data:
            command: fan_2_bottom_right_20
            device: airco
          target:
            entity_id: remote.broadlink_bedroom_remote
      else:
        - action: remote.send_command
          data:
            command: fan_3_bottom_right_20
            device: airco
          target:
            entity_id: remote.broadlink_bedroom_remote
  mode: single
