# Restore schedule daily to prevent (accidental) overrides from keeping the
# airco off
- alias: Airco (Bedroom) restore schedule
  id: bdfe854c-79d1-474d-a30e-84a3e99e1672
  triggers:
    - trigger: time
      at: "15:00:00"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_bedroom_ac
      attribute: preset_mode
      state: home
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.tado_bedroom_ac
          state: auto
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target:
        entity_id: climate.tado_bedroom_ac
  mode: single
# tado° Is scheduled to switch on daily at 22:30 – the below is in case someone
# goes to bed early
- alias: Airco (Bedroom) nighttime early on
  id: d32f9d2b-c66c-41d2-85dd-b3049a077dce
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_bed
      from: "off"
      to: "on"
      for: "00:05:00"
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_bedroom_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: "off"
    - condition: state
      entity_id: group.openclose_bedroom
      state: "off"
    # Don't trigger after going to bed, nor in the morning after waking up...
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: idle
  actions:
    # Control properly via the tado°-integration – the settings below are
    # identical to what is scheduled to happen at 22:30
    - action: script.climate_set_operating_mode
      data:
        entity_id: climate.tado_bedroom_ac
        hvac_mode: cool
        swing_mode: "off"
        fan_mode: low
        temperature: 20
  mode: single
# tado° Is scheduled to switch off daily at 09:00/10:00 (weekdays versus
# weekend) – the below is in case we get out of bed early
- alias: Airco (Bedroom) off
  id: 6767ad63-9f59-4d70-b304-45cafd75442e
  triggers:
    - trigger: state
      entity_id: light.bedroom
      from: "on"
      to: "off"
      for: "00:05:00"
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
    # Only act when the wakeup "grace-time" timer is running — this ensures it's
    # in the morning _after_ the wakeup-alarm has sounded
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: active
  actions:
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_bedroom_ac
  mode: single
# Switching off the airco implicitly switches off the override controlled via
# `fan.airco_bedroom_broadlink`; keep its state in sync with the actual airco –
# no better way around this than using an automation
- alias: Airco (Bedroom) – Broadlink off
  id: ebf46928-d119-4f9d-8c8c-fde90b28fed7
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: cool
      to: "off"
  conditions:
    - condition: numeric_state
      entity_id: input_number.speed_airco_bedroom
      above: 0
  actions:
    - action: input_number.set_value
      target:
        entity_id: input_number.speed_airco_bedroom
      data:
        value: 0
  mode: single
# Prevent the Bedroom- and Attic-aircos from running simultaneously – doesn't
# blow a fuse, but leaves too little margin for comfort. There's an opposite
# automation defined in "attic.yaml".
- alias: Airco (Bedroom) off
  id: 620de186-54bc-4c1c-a3df-761186db44c9
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
  conditions:
    - condition: state
      entity_id: climate.tado_smart_ac_control_attic
      state: cool
  actions:
    # Pull the handbrake (HomeKit is most responsive)
    - action: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target:
        entity_id: climate.tado_smart_ac_control_bedroom
    - action: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          rooms: bedroom
          priority: attention
          message: >-
            The airco in the Attic is switched on; please switch it off before
            switching on the airco in the Bedroom...
  mode: single
- alias: Airco (Bedroom) off
  id: c70eb89e-dbca-467a-8e40-19efe902f107
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
      for: "00:00:30"
  conditions:
    - condition: state
      entity_id: group.openclose_bedroom
      state: "on"
  actions:
    - variables:
        # Take HVAC-mode from the tadoº-integration (so we can distinguish
        # between "cool" and "auto")
        last_hvac_mode: >-
          {{ states('climate.tado_bedroom_ac') }}
        last_swing_mode: >-
          {{ state_attr('climate.tado_bedroom_ac', 'swing_mode') }}
        last_fan_mode: >-
          {{ state_attr('climate.tado_bedroom_ac', 'fan_mode') }}
        # HomeKit updates much faster, so prefer that for the temperature
        last_temperature: >-
          {{
            state_attr('climate.tado_smart_ac_control_bedroom', 'temperature')
          }}
    - action: climate.turn_off
      target:
        entity_id: climate.tado_bedroom_ac
    - wait_for_trigger:
        - trigger: state
          entity_id: group.openclose_bedroom
          from: "on"
          to: "off"
        # Abort conditions
        - trigger: state
          id: abort
          entity_id: input_boolean.everyone_asleep
          from: "off"
          to: "on"
        - trigger: event
          id: abort
          event_type: airco_bedroom_abort_wait
      timeout: "06:00:00"
      continue_on_timeout: false
    - condition: template
      value_template: >-
        {{ wait.trigger.id != 'abort' }}
    - if:
        # No need to restore other settings in "auto" HVAC-mode
        - >-
          {{ last_hvac_mode == 'auto' }}
      then:
        - action: climate.set_hvac_mode
          data:
            hvac_mode: >-
              {{ last_hvac_mode }}
          target:
            entity_id: climate.tado_bedroom_ac
      else:
        - action: script.climate_set_operating_mode
          data:
            entity_id: climate.tado_bedroom_ac
            hvac_mode: >-
              {{ last_hvac_mode }}
            swing_mode: >-
              {{ last_swing_mode }}
            fan_mode: >-
              {{ last_fan_mode }}
            temperature: >-
              {{ last_temperature }}
  mode: restart
- alias: Airco (Bedroom) window open nighttime announcement
  id: 7ccc2315-fd8a-479e-a29f-c6df92707c4a
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: group.openclose_bedroom
      state: "on"
    # The airco _should_ be on, but isn't
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_bedroom_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: "off"
  actions:
    - delay: 1 # Queue these announcements up first
    - if:
        - condition: numeric_state
          entity_id: sensor.weewx_outside_temperature_balcony
          above: 18
        - condition: numeric_state
          entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
          above: 20.5
      then:
        - action: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: regular
              message: >-
                The airco was not switched on because the Bedroom window is
                open. Close the window to switch on the airco...
      else:
        - action: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: regular
              message: >-
                The airco isn't needed tonight. Consider leaving the Bedroom
                window open so it remains switched off...
  mode: single
- alias: Airco (Bedroom) window open notification
  id: 92f0bc70-113d-4b67-a96e-b62373e50e28
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
      for: "00:00:30"
  conditions:
    - condition: state
      entity_id: group.openclose_bedroom
      state: "on"
    # During nighttime a different approach is taken
    - condition: state
      entity_id: script.lights_out
      state: "off"
    - condition: state
      entity_id: timer.everyone_asleep_delay
      state: idle
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
  actions:
    - action: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Notification
          group: climate
          tag: airco_bedroom_window
          action_1: Switch off airco
          title: ❄️ Bedroom airco switched off – the window is open
          message: >-
            Please close the door and/or window(s) in the Bedroom to allow the
            airco to switch back on...
    - wait_for_trigger:
        - trigger: event
          event_type: mobile_app_notification_action
          event_data:
            action: ACTION_1_airco_bedroom_window
      timeout: "06:00:00"
      continue_on_timeout: false
    - action: persistent_notification.dismiss
      data:
        notification_id: airco_bedroom_window
    - event: airco_bedroom_abort_wait
  mode: single
  max_exceeded: silent
- alias: Airco (Bedroom) nighttime airflow adjustment
  id: ac143f4e-ef0a-4da5-a975-9793c81a4373
  triggers:
    - trigger: state
      entity_id: climate.tado_smart_ac_control_bedroom
      from: "off"
      to: cool
    - trigger: state
      entity_id: binary_sensor.occupancy_bed
      from: "off"
      to: "on"
    - trigger: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
    # Temperature-based triggers
    - trigger: numeric_state
      entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
      above: 26
      for: "00:05:00"
    - trigger: numeric_state
      entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
      above: 24
      below: 26
      for: "00:05:00"
    - trigger: numeric_state
      entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
      above: 20.5
      below: 24
      for: "00:05:00"
    - trigger: numeric_state
      entity_id: sensor.smart_ac_control_wr2352422400_current_temperature
      below: 20.5
      for: "00:05:00"
    # Fallback in case tado° messes with the fan-speed
    - trigger: state
      entity_id: climate.tado_bedroom_ac
      attribute: fan_modes
  conditions:
    - condition: state
      entity_id: input_boolean.airco_active
      state: "on"
    - condition: state
      entity_id: climate.tado_bedroom_ac
      attribute: preset_mode
      state: home
    - condition: state
      entity_id: climate.tado_smart_ac_control_bedroom
      state: cool
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.occupancy_bed
          state: "on"
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "on"
        - condition: state
          entity_id: script.lights_out
          state: "on"
  actions:
    # Switching the airco off via tado° is not a use-case: The airco manages
    # itself just fine (and I don't mind it running silently in the background).
    # As the airco is higher up in the room than the tado°-unit, it'll barely
    # bring the temperature to the setpoint (20° C) from tado°'s perspective...
    - choose:
        - conditions:
            # The HomeKit-backed temperature-sensor of the tado° unit itself is
            # most appropriate in this case
            - condition: numeric_state
              entity_id: >-
                sensor.smart_ac_control_wr2352422400_current_temperature
              above: 26
            # Only send if the fan isn't already at the wanted speed
            - condition: not
              conditions:
                - condition: state
                  entity_id: fan.airco_bedroom_broadlink
                  attribute: percentage
                  state: 100
          sequence:
            - action: fan.set_percentage
              data:
                percentage: 100
              target:
                entity_id: fan.airco_bedroom_broadlink
        - conditions:
            - condition: numeric_state
              entity_id: >-
                sensor.smart_ac_control_wr2352422400_current_temperature
              above: 24
            - condition: not
              conditions:
                - condition: state
                  entity_id: fan.airco_bedroom_broadlink
                  attribute: percentage
                  state: 75
          sequence:
            - action: fan.set_percentage
              data:
                percentage: 75
              target:
                entity_id: fan.airco_bedroom_broadlink
        - conditions:
            - condition: numeric_state
              entity_id: >-
                sensor.smart_ac_control_wr2352422400_current_temperature
              above: 20.5
            - condition: not
              conditions:
                - condition: state
                  entity_id: fan.airco_bedroom_broadlink
                  attribute: percentage
                  state: 50
          sequence:
            - action: fan.set_percentage
              data:
                percentage: 50
              target:
                entity_id: fan.airco_bedroom_broadlink
      default:
        if:
          - condition: not
            conditions:
              - condition: state
                entity_id: fan.airco_bedroom_broadlink
                attribute: percentage
                state: 25
        then:
          - action: fan.set_percentage
            data:
              percentage: 25
            target:
              entity_id: fan.airco_bedroom_broadlink
    # As there's a broad array of triggers, block for one-minute to prevent
    # unintentionally triggering in rapid succession
    - delay: "00:01:00"
  mode: single
  max_exceeded: silent
- alias: Nighttime reminder to open Bedroom window
  id: ee31d2d5-cf8f-4538-8570-addc28b43768
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: group.openclose_bedroom
      state: "on"
    - condition: state
      entity_id: input_boolean.airco_active
      state: "off"
  actions:
    - delay: 1 # Queue this one up first
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: regular
          message: >-
            The bedroom window is closed. Consider opening it to get some fresh
            air during the night...
  mode: single
