- alias: 🌡️ | ⏰/🚗 Electric blanket on (daily at 22:00 / someone home)
  id: f712246a-1aba-4efe-8834-9cd9a62f706c
  trigger:
    - platform: time
      id: time
      at: "22:00:00"
    # This is explicitly _not_ based around the Home Alarm-state, as it's
    # dependent on one of us being home, not just anyone (ie, guests)...
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: switch.on_off_plug_in_unit_3
      state: "off"
    - condition: state
      state: home
      entity_id: group.family
    # Ignore time-constraint if triggered by time-trigger
    - condition: or
      conditions:
        - condition: trigger
          id: time
        - condition: time
          after: "22:00:00"
          before: "04:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.on_off_plug_in_unit_3
    # If there's already someone in the bed, take care of switching off here
    # (as the regular "Off"-automation won't trigger)
    - condition: state
      entity_id: binary_sensor.occupancy_bed
      state: "on"
    # The Withings Sleep Analysers aren't 100% accurate, so a bit of margin is
    # required – if the bed is empty for 10-minutes, abort; leave the blanket on
    # (the regular "Off"-automation adequately handles things from there). If
    # someone's in the bed for more than 45-minutes, assume they went to sleep.
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.occupancy_bed
          from: "on"
          to: "off"
          for: "00:10:00"
      timeout: "00:45:00"
      continue_on_timeout: true
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - condition: state
      entity_id: switch.on_off_plug_in_unit_3
      state: "on"
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_3
  mode: single
  max_exceeded: silent
- alias: >-
    🌡️ | 🛌/💤 Electric blanket off (Someone in the bed / everyone asleep)
  id: e5b75f79-e60f-4d3e-b354-29a3622567ba
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_bed
      from: "off"
      to: "on"
      for: "00:20:00"
    # As a fallback, also turn off when everyone is asleep
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.on_off_plug_in_unit_3
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_3
  mode: restart
- alias: 🌡️ | ⏰ Electric blanket off (after 3 hours)
  id: ba757313-c28b-4533-be3f-897d47e18c35
  trigger:
    - platform: state
      entity_id: switch.on_off_plug_in_unit_3
      to: "on"
      for: "03:00:00"
  condition: []
  action:
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_3
  mode: single
