- alias: 🌪️ | ⏰ Guestroom fan on (daily at 05:00)
  description: ''
  trigger:
  - platform: time
    at: '05:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.on_off_plug_in_unit_4
  mode: single
- alias: 🌪️ | ⏰ Guestroom fan off (daily at 07:00)
  description: ''
  trigger:
  - platform: time
    at: '07:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.on_off_plug_in_unit_4
  mode: single
