- alias: 💨 | 💤 Sonair – Living room increase airflow (everyone asleep)
  id: 9a1829d1-11f8-4487-93b3-b5e7288a3f31
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: fan.sonair_living_room
      state: "on"
  action:
    - choose:
        # If the outside temperature is within an acceptable range (i.e. it
        # won't make it too hot nor too cold inside) increase to 70 m³/h. As
        # this automation only triggers at night, the temperature ranges are
        # narrower than those used for the other automations...
        - conditions:
            - condition: numeric_state
              entity_id: sensor.weewx_outside_temperature
              above: 10
              below: 22
          sequence:
            - service: fan.set_percentage
              data:
                percentage: 60
              target:
                entity_id: fan.sonair_living_room
        # If it's freezing outside don't increase airflow (30 m³/h is more or
        # less equal to what the CO₂-controlled mode pulls in by default)
        - conditions:
            - condition: numeric_state
              entity_id: sensor.weewx_outside_temperature
              below: 0
          sequence:
            - service: fan.set_percentage
              data:
                percentage: 20
              target:
                entity_id: fan.sonair_living_room
      # In all other cases set to 50 m³/h
      default:
        - service: fan.set_percentage
          data:
            percentage: 40
          target:
            entity_id: fan.sonair_living_room
  mode: single
- alias: 💨 | 💤 Sonair – Living room reduce airflow (everyone awake)
  id: 540d2378-b1e4-40f6-8863-8270e5bb6ea8
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: fan.sonair_living_room
      state: "on"
  action:
    - service: fan.set_percentage
      data:
        percentage: 40
      target:
        entity_id: fan.sonair_living_room
  mode: single
- alias: 💨 | 🤖 Sonair – Living room restore airflow (6ºC < 🌡️ < 28ºC)
  id: d7e3c910-09f3-405d-855d-58e9c5564a1b
  trigger:
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      below: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_living_room
      state: "on"
    - condition: state
      entity_id: switch.co2_sensor_sonair_living_room
      state: "on"
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      below: 28
  action:
    - service: fan.set_percentage
      data:
        percentage: 40
      target:
        entity_id: fan.sonair_living_room
  mode: single
- alias: 💨 | ⏰/🤖 Sonair – Living room CO₂-controlled (daily at 20:00 / 6ºC > 🌡️ > 28ºC)
  id: 1fe024b6-8f8b-4d34-b19b-62c4052fadf2
  trigger:
    # The Sonair is relatively silent but as it gets quiet outside, the 40%
    # speed setting becomes audible. Switching to CO₂-controlled mode reduces
    # ventilation (and thus noise).
    - platform: time
      at: "20:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 6
      for: "01:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      id: start
      event: start
    - platform: event
      id: reload
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_living_room
      state: "on"
    - condition: state
      entity_id: switch.co2_sensor_sonair_living_room
      state: "off"
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
    # Abort if triggered by a start/reload event and the temperature isn't out
    # of bounds
    - condition: or
      conditions:
        - condition: not
          conditions:
            - condition: trigger
              id: [start, reload] # yamllint disable-line rule:brackets
        - condition: numeric_state
          entity_id: sensor.weewx_outside_temperature
          above: 28
          below: 6
    # If the fan speed is _above_ 40% it has most likely been manually
    # overridden; in that case we leave the current setting alone...
    - condition: not
      conditions:
        - condition: numeric_state
          entity_id: fan.sonair_living_room
          attribute: percentage
          above: 40
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.co2_sensor_sonair_living_room
  mode: single
- alias: 💨 | ⏰/🤖 Sonair – Guestroom restore airflow (everyone awake / 6ºC < 🌡️ < 28ºC)
  id: fc5a63a2-f71d-4320-8f98-d61341cba37e
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      for: "01:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_guestroom
      state: "on"
    - condition: state
      entity_id: switch.co2_sensor_sonair_guestroom
      state: "on"
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      below: 28
  action:
    - service: fan.set_percentage
      data:
        percentage: 40
      target:
        entity_id: fan.sonair_guestroom
  mode: single
- alias: 💨 | 💤/⏰/🤖 Sonair – Guestroom CO₂-controlled (everyone asleep / daily at 23:00 / 6ºC > 🌡️ > 28ºC)
  id: cefa0b39-73b1-47cc-b781-0604d5f23fd6
  trigger:
    - platform: time
      at: "23:00:00"
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "off"
      to: "on"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 6
      for: "01:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      id: start
      event: start
    - platform: event
      id: reload
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_guestroom
      state: "on"
    - condition: state
      entity_id: switch.co2_sensor_sonair_guestroom
      state: "off"
    # Abort if triggered by a start/reload event and the temperature isn't out
    # of bounds
    - condition: or
      conditions:
        - condition: not
          conditions:
            - condition: trigger
              id: [start, reload] # yamllint disable-line rule:brackets
        - condition: numeric_state
          entity_id: sensor.weewx_outside_temperature
          above: 28
          below: 6
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.co2_sensor_sonair_guestroom
- alias: 💨 | 🤖 Sonair – Wardrobe limit airflow (6ºC > 🌡️ > 28ºC)
  id: f7bbe56e-fef4-4a79-9e94-5ec3d861fc3b
  trigger:
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 6
      for: "01:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_wardrobe
      state: "on"
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 28
      below: 6
    - condition: not
      conditions:
        - condition: state
          entity_id: fan.sonair_wardrobe
          attribute: percentage
          state: 20
  action:
    - service: fan.set_percentage
      data:
        percentage: 20
      target:
        entity_id: fan.sonair_wardrobe
- alias: 💨 | 🤖 Sonair – Wardrobe restore airflow (6ºC < 🌡️ < 28ºC)
  id: e97b3037-3e1e-4933-9257-3c1fe74c1295
  trigger:
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      for: "01:00:00"
    - platform: numeric_state
      entity_id: sensor.weewx_outside_temperature
      below: 28
      for: "01:00:00"
    # Trigger on Home Assistant (re)start and automations reloaded to prevent
    # missing the "held state"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  condition:
    - condition: state
      entity_id: fan.sonair_wardrobe
      state: "on"
    - condition: numeric_state
      entity_id: sensor.weewx_outside_temperature
      above: 6
      below: 28
    - condition: not
      conditions:
        - condition: state
          entity_id: fan.sonair_wardrobe
          attribute: percentage
          state: 60
  action:
    - service: fan.set_percentage
      data:
        percentage: 60
      target:
        entity_id: fan.sonair_wardrobe
