# tado° (combination of HomeKit controller and the Tado integration)
#
# Scheduling and "Away" mode are arranged via the tado° app/service. The below
# automations are mainly concerned with switching the "Away" mode on and off
# and some exceptional scheduling conditions.
- alias: 🤖 | 🌡️ tado° to "Away" mode (everyone away)
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition: []
  action:
  # Control tado° via the Tado integration (i.e. Internet)
  - service: climate.tado_living_room
    data:
      preset_mode: away
    entity_id: climate.thermostat
  mode: single
- alias: 🤖 | 🌡️ tado° to "Home" mode (someone home)
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  condition: []
  action:
  # Control tado° via the Tado integration (i.e. Internet)
  - service: climate.tado_living_room
    data:
      preset_mode: home
    entity_id: climate.thermostat
  mode: single
# This assumes we don't go to bed too early: tado° overwrites the temperature
# at the next schedule change (19:00 or 20:30 depending on day of the week). If
# we go to bed before that time, the heating will be switched on again later in
# the evening...
- alias: 🤖 | 🌡️ Lower thermostat (everyone asleep)
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.everyone_asleep
    from: 'off'
    to: 'on'
  condition:
  # Control tado° via HomeKit
  - condition: state
    entity_id: climate.tado_smart_thermostat
    state: heat
  - condition: numeric_state
    entity_id: sensor.tado_smart_thermostat_setpoint
    above: 18.0
  action:
  - service: climate.set_temperature
    data:
      temperature: 15.0
    entity_id: climate.tado_smart_thermostat
  mode: single
