# tado° (combination of HomeKit controller and the Tado integration)
#
# Scheduling and "Away" mode are arranged via the tado° app/service. The below
# automations are mainly concerned with switching the "Away" mode on and off
# and some exceptional scheduling conditions.
- alias: 🌡️ | ✈️ tado° to "Away" mode (everyone away)
  id: 7dd16eef-43de-458c-9231-145260a5bea8
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition: []
  action:
  # Control tado° via the Tado integration (i.e. Internet)
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    entity_id: climate.tado_living_room
  mode: single
- alias: 🌡️ | ✈️ tado° to "Home" mode (someone home)
  id: e9f167c4-5f85-4eb3-810b-942edd2c5f0f
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  condition: []
  action:
  # Control tado° via the Tado integration (i.e. Internet)
  - service: climate.set_preset_mode
    data:
      preset_mode: home
    entity_id: climate.tado_living_room
  mode: single
# This assumes we don't go to bed too early: tado° overwrites the temperature
# at the next schedule change (19:00 or 20:30 depending on day of the week). If
# we go to bed before that time, the heating will be switched on again later in
# the evening...
- alias: 🌡️ | 💤 Lower thermostat (everyone asleep)
  id: 00e26ec6-b41d-4978-96bb-52225fa26721
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.everyone_asleep
    from: 'off'
    to: 'on'
  condition:
  # Control tado° via HomeKit
  - condition: state
    entity_id: climate.tado_smart_thermostat
    state: heat
  - condition: numeric_state
    entity_id: sensor.tado_smart_thermostat_setpoint
    above: 18.0
  action:
  - service: climate.set_temperature
    data:
      temperature: 15.0
    entity_id: climate.tado_smart_thermostat
  mode: single
