- alias: >-
    💨 | ⏰/🚗 Aroma diffuser Living room off (after 90 minutes / everyone away)
  id: dab99a02-cf11-43a2-a2af-c188dac07acf
  trigger:
    - platform: state
      entity_id: humidifier.vocolinc_flb_living_room
      to: "on"
      for: "01:30:00"
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
    # Trigger on Home Assistant (re)start to prevent missing the "held state"
    # (and staying on indefinitely)
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: humidifier.turn_off
      data:
        entity_id: humidifier.vocolinc_flb_living_room
  mode: single
