- alias: Front and Back door lights on
  id: 57d64e4d-8ec5-4245-a98e-be4ac4dd0fc5
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions: []
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.front_back_door_evening
  mode: single
# Back door is handled by the Garden automation
- alias: Front door light off
  id: eff18963-7828-4cb0-9edd-ff18771e1974
  triggers:
    - trigger: time
      at: "22:50:00"
  conditions: []
  actions:
    - delay: >-
        {{ range(2400) | random }}
    - if:
        - condition: state
          entity_id: light.hue_filament_bulb_1_2
          state: "on"
      then:
        - action: light.turn_off
          entity_id: light.hue_filament_bulb_1_2
# Fallback to prevent the Front and/or Back door lights from staying on the
# day, should something go wrong with any of the other automations..
- alias: Front and Back door lights off
  id: 766babb7-e5b3-43ff-b72a-e782d22e82d6
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  conditions:
    - condition: state
      entity_id: light.front_back_door
      state: "on"
  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.front_back_door
  mode: single
- alias: Front door light to maximum brightness
  id: 78c89018-504b-4ff1-8aa1-fbebc14206e9
  triggers:
    # Front door
    - trigger: state
      entity_id: binary_sensor.openclose_16
      from: "off"
      to: "on"
    # Doorbell
    - trigger: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
      # Slight delay on doorbell activation to not startle visitors / make it
      # less obvious the lights are automated
      for: "00:00:03"
  variables:
    light_state: >-
      {{ states('light.hue_filament_bulb_1_2') }}
    light_brightness: >-
      {{ state_attr('light.hue_filament_bulb_1_2', 'brightness') | int(0) }}
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  actions:
    - action: light.turn_on
      data:
        brightness: 255
        entity_id: light.hue_filament_bulb_1_2
    # Wait for the front door to be closed for 30-seconds, or for the doorbell
    # to have rang 30-minutes ago
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.openclose_16
          from: "on"
          to: "off"
          for: "00:00:30"
        - trigger: state
          id: doorbell
          entity_id: binary_sensor.vibration_43
          from: "on"
          to: "off"
          for: "00:29:00" # Sensor stays "on" for 1-minute
        # Abort if the light gets otherwise changed (this prevents us from
        # messing with other lighting automations)
        # N.B. To prevent triggering on the transition initiated above (which is
        # not instantaneous), we use a "from"-attribute check to trigger on
        # leaving the state we explicitly set above.
        - trigger: state
          id: abort
          entity_id: light.hue_filament_bulb_1_2
          attribute: brightness
          from: 255
      timeout: "02:00:00"
      continue_on_timeout: true
    - condition: >-
        {{ wait.trigger is none or wait.trigger.id != 'abort' }}
    # In case of a pending or triggered Home Alarm, don't further interfer
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state:
            - pending
            - triggered
    - if: >-
        {{ light_state == 'on' and light_brightness > 0 }}
      then:
        - action: light.turn_on
          data:
            brightness: >-
              {{ light_brightness }}
          target:
            entity_id: light.hue_filament_bulb_1_2
      else:
        - action: light.turn_off
          target:
            entity_id: light.hue_filament_bulb_1_2
  mode: single
  max_exceeded: silent
- alias: Kitchen door light to maximum brightness
  id: ffff8c6f-9dbd-4791-8c32-766e1570811e
  triggers:
    - trigger: state
      entity_id: binary_sensor.openclose_12
      from: "off"
      to: "on"
  variables:
    light_state: >-
      {{ states('light.hue_filament_bulb_1') }}
    light_brightness: >-
      {{ state_attr('light.hue_filament_bulb_1', 'brightness') | int(0) }}
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  actions:
    - action: light.turn_on
      data:
        brightness: 255
        entity_id: light.hue_filament_bulb_1
    # Wait for the back door to be closed for 30-seconds
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.openclose_12
          from: "on"
          to: "off"
          for: "00:00:30"
        # Abort if the light gets otherwise changed
        - trigger: state
          id: abort
          entity_id: light.hue_filament_bulb_1
          attribute: brightness
          from: 255
      timeout: "02:00:00"
      continue_on_timeout: true
    - condition: >-
        {{ wait.trigger is none or wait.trigger.id != 'abort' }}
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state:
            - pending
            - triggered
    - if: >-
        {{ light_state == 'on' and light_brightness > 0 }}
      then:
        - action: light.turn_on
          data:
            brightness: >-
              {{ light_brightness }}
          target:
            entity_id: light.hue_filament_bulb_1
      else:
        - action: light.turn_off
          target:
            entity_id: light.hue_filament_bulb_1
  mode: single
  max_exceeded: silent
