- alias: Kitchen lights on
  id: 772891ad-0afb-4460-a10d-cd812243d082
  triggers:
    - trigger: time
      at: input_datetime.wakeup
  conditions:
    - condition: state
      entity_id: light.kitchen
      state: "off"
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
      then:
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_active
            transition: 15
      else:
        # Respect the daytime-lighting threshold
        - condition: numeric_state
          entity_id: sensor.lightlevel_47
          below: 80
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_daytime
            transition: 15
  mode: single
- alias: Kitchen lights on
  id: c1a18069-46f1-4e3d-9518-6b8e63b3e04d
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: "off"
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state:
            - Daytime
            - Active
  actions:
    - action: script.hue_activate_scene_kitchen
      data:
        scene_id: scene.kitchen_active
        transition: >-
          {{ 30 if states('light.kitchen') == 'off' else 600 }}
  mode: single
- alias: Kitchen daytime-lighting on
  id: 5b3387c6-763b-47da-b938-1eaefcd0ffd1
  triggers:
    - trigger: numeric_state
      id: lux
      entity_id: sensor.lightlevel_47
      for: "00:01:00"
      below: 80
    - trigger: state
      id: obscured
      entity_id: sensor.sun_relative_to_house
      from: obscured
      to: in_front
    - trigger: state
      id: obscured
      entity_id: sensor.sun_relative_to_house
      from: in_back
      to: obscured
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: or
      conditions:
        # For lux triggers, the lights should be off
        - condition: and
          conditions:
            - condition: trigger
              id: lux
            - condition: state
              entity_id: light.kitchen
              state: "off"
        # For transitions to/from obscured, the lights should be on
        - condition: and
          conditions:
            - condition: trigger
              id: obscured
            - condition: state
              entity_id: light.kitchen
              state: "on"
    # Never override "Bright (custom)" – this is handled by the activity
    # activations in the Kitchen (which also handles restoring the lights back
    # to their daytime setting if so required)
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
      then:
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_active
            transition: >-
              {{ 15 if states('light.kitchen') == 'off' else 600 }}
      else:
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_daytime
            transition: >-
              {{ 15 if states('light.kitchen') == 'off' else 600 }}
  mode: single
- alias: Kitchen daytime-lighting off
  id: 2c48592e-2d8b-42f1-880b-44183ffc442a
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: state
      entity_id: sensor.sun_relative_to_house
      from: obscured
      to: in_front
      # Prevent race-condition with "daytime-lighting on"
      for: "00:00:10"
    - trigger: numeric_state
      entity_id: sensor.lightlevel_47
      for: "00:10:00"
      above: 90
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    # Ensure the time-of-day triggers respects the lux-requirement
    - condition: numeric_state
      entity_id: sensor.lightlevel_47
      above: 90
    # Only act when the lights are in their expected state ("Active" when
    # obscured; "Daytime" otherwise)
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.sun_relative_to_house
              state:
                - in_front
                - in_back
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Daytime
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.sun_relative_to_house
              state: obscured
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Active
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
  actions:
    - action: script.hue_activate_scene_kitchen
      data:
        turn_off: true
        transition: 15
  mode: single
- alias: Kitchen scene "Active" to "Ambiance"
  id: 61478b1a-9dab-4b1f-a7cc-5ded98df1f95
  triggers:
    - trigger: time
      at: "21:30"
    - trigger: state
      entity_id: sensor.time_of_day
      to: night
  conditions:
    - condition: state
      entity_id: sensor.hue_scene_kitchen
      state: Active
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: time
      after: "21:29"
  actions:
    - action: hue.activate_scene
      target:
        entity_id: scene.kitchen_ambiance
      data:
        transition: 600
    - delay: 600
  mode: single
- alias: Kitchen counter & cupboards toggle
  id: ff4ddb05-91d8-431d-9226-b51e0bbd9b36
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.presence_53 # Sink
        - binary_sensor.presence_155 # Coffee machine
      from: "off"
      to: "on"
  conditions:
    # Don't trigger when Kitchen is "Bright (custom)" – that's bright enough;
    # there's another automation handling motion for that situation
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
    - condition: or
      conditions:
        # One sensor triggers regardless of light level...
        - condition: template
          value_template: >-
            {{ trigger.entity_id == 'binary_sensor.presence_155' }}
        # ...the other not
        - condition: and
          conditions:
            - condition: template
              value_template: >-
                {{ trigger.entity_id == 'binary_sensor.presence_53' }}
            - condition: numeric_state
              entity_id: sensor.lightlevel_55
              # N.B. Same threshold value as in the next automation
              below: 200
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.kitchen_counter_cupboards_activity
    # Wait for _all_ motion sensors to clear – otherwise race conditions are
    # possible where the lights go off (because one sensor clears) and never
    # come back on again (because the other sensor never clears due to
    # ongoing motion and thus never retriggers the lights).
    - wait_template: >-
        {{
          states('binary_sensor.presence_53') == 'off' and
          states('binary_sensor.presence_155') == 'off'
        }}
    - delay: "00:03:00"
    # If the Kitchen scene is not "Bright (custom)" and the scene for "Kitchen
    # counter & cupboards" is still "Activity", no changes were made to the
    # lighting (either manual, or by the "sustained activity"-automation). We
    # can safely restore the previous scene for the "Kitchen" as a whole...
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
    - condition: state
      entity_id: sensor.hue_scene_kitchen_counter_cupboards
      state: Activity
    # Changing the "Kitchen counter & cupboards" scene doesn't change the
    # "Kitchen" scene – we thus can simply re-apply the active scene
    - action: script.hue_activate_scene
      data:
        scene_entity: sensor.hue_scene_kitchen
  mode: restart
- alias: Kitchen scene to "Bright (custom)"
  id: ac457661-49b6-4ee6-b0cf-ceac3bd4ccab
  triggers:
    - trigger: state
      id: activity
      entity_id:
        - binary_sensor.presence_53
        - binary_sensor.presence_155
      from: "off"
      to: "on"
    # Initial trigger only considers the sensor above the sink
    - trigger: state
      id: sustained_activity
      entity_id: binary_sensor.presence_53
      from: "off"
      to: "on"
      # Empirically determined to be the threshold for "sustained activity" 😉
      for: "00:01:30"
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
    - condition: or
      conditions:
        - condition: trigger
          id: activity
        # Initial trigger should respect maximum light level
        - condition: and
          conditions:
            - condition: trigger
              id: sustained_activity
            - condition: numeric_state
              entity_id: sensor.lightlevel_55
              # N.B. Same threshold value as in the previous automation
              below: 200
  actions:
    # Only attempt to change scene on the initial (sustained activity) trigger.
    # The additional (more prolific) trigger only serves to reset the delay
    # timer...
    - choose:
        - conditions:
            - condition: trigger
              id: sustained_activity
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.hue_scene_kitchen
                  state: Bright (custom)
          sequence:
            - action: scene.turn_on
              target:
                entity_id: scene.kitchen_bright_custom
    - wait_template: >-
        {{
          states('binary_sensor.presence_53') == 'off' and
          states('binary_sensor.presence_155') == 'off'
        }}
    - wait_for_trigger:
        - trigger: state
          entity_id: sensor.hue_scene_kitchen
          from: Bright (custom)
      timeout: "00:08:00"
      continue_on_timeout: true
    # Only continue if Kitchen hasn't been taken out of "Bright (custom)"
    - condition: >-
        {{ wait.trigger is none }}
    # During the bright part of the day, re-apply daytime-lighting, or switch
    # off the Kitchen
    - if:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
        - condition: not
          conditions:
            - condition: state
              entity_id: sensor.sun_relative_to_house
              state: obscured
      then:
        if:
          - condition: numeric_state
            entity_id: sensor.lightlevel_47
            below: 90
        then:
          - action: hue.activate_scene
            target:
              entity_id: scene.kitchen_daytime
            data:
              transition: 120
        else:
          - action: light.turn_off
            target:
              entity_id: light.kitchen
            data:
              transition: 120
      # Otherwise, follow the Living Room
      else:
        - choose:
            # Active
            - conditions:
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state: Active
              sequence:
                - action: hue.activate_scene
                  target:
                    entity_id: scene.kitchen_active
                  data:
                    transition: 120
            # Ambiance
            - conditions:
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state:
                    - Ambiance
                    - Movie (ambiance)
              sequence:
                - action: hue.activate_scene
                  target:
                    entity_id: scene.kitchen_ambiance
                  data:
                    transition: 120
            # Movie
            - conditions:
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state: Movie
              sequence:
                - action: hue.activate_scene
                  target:
                    entity_id: scene.kitchen_movie
                  data:
                    transition: 30
            # Off
            - conditions:
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state: «Off»
              sequence:
                - action: light.turn_off
                  target:
                    entity_id: light.kitchen
                  data:
                    transition: 120
  mode: restart
- alias: Kitchen persist scene "Daytime"
  id: 1816c80c-83dd-44cd-b902-11f605f73584
  triggers:
    - trigger: state
      entity_id: sensor.hue_scene_kitchen
      not_to:
        - Daytime
        - «Off»
      for: "00:00:30"
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
  actions:
    - action: script.hue_activate_scene_kitchen
      data:
        scene_id: scene.kitchen_daytime
        transition: 600
  mode: single
