- alias: 🌦️ | 📱/🔊 Notify Attic window is open (starts raining)
  id: 4dd59c72-309a-441a-b97c-07a69c6898da
  trigger:
    - platform: numeric_state
      entity_id: sensor.weewx_rain_rate_hour
      above: 2.0
  condition:
    - condition: state
      entity_id: sensor.attic_window_position
      state:
        - ajar
        - open
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
  action:
    - choose:
        # Only announce it's raining via TTS if the window is fully open
        - conditions:
            - condition: state
              entity_id: sensor.attic_window_position
              state: open
          sequence:
            - service: script.tts_p20
              data:
                message: >-
                  It's raining!
                  Check the Attic window to ensure it's not raining in...
    # Explicitly block any further runs of this automation while the
    # notification is up (i.e. once a notification is up, no additional
    # notifications are raised)
    - service: script.persistent_notification
      data:
        group: weather
        channel: Alert
        targetDevices: home
        criticalNotification: true
        tag: rain-attic
        title: ☔ It's raining!
        message: >-
          Check the Attic window to ensure it's not raining in...
  mode: single
  max_exceeded: silent
- alias: 🌦️ | 📱 Dismiss Attic window notification (stops raining)
  id: 0bfb45f6-5516-4f37-86f1-d7bb7af88e94
  trigger:
    - platform: numeric_state
      entity_id: sensor.weewx_rain_rate_hour
      below: 2.0
      for: "00:10:00"
  condition: []
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: rain-attic
  mode: single
- alias: 🌦️ | 📱 Dismiss Attic window notification (window closed)
  id: dd524898-9606-4c30-b7dc-d061515ee6bc
  trigger:
    - platform: state
      entity_id: sensor.attic_window_position
      from:
        - ajar
        - open
      to:
        - ajar-locked
        - closed-ventilate
        - closed
  condition:
    - condition: numeric_state
      entity_id: sensor.weewx_rain
      above: 0
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: rain-attic
  mode: single
