- alias: 🌦️ | 📱/🔊 Notify Attic window is open (starts raining)
  id: 4dd59c72-309a-441a-b97c-07a69c6898da
  triggers:
    - trigger: numeric_state
      entity_id: sensor.weewx_rain_rate_hour
      above: 1.0
  conditions:
    - condition: state
      entity_id: sensor.attic_window_position
      state: open
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
  actions:
    - action: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          priority: attention
          message: >-
            It's raining and the Attic window is open.
    # Explicitly block any further runs of this automation while the
    # notification is up (i.e. once a notification is up, no additional
    # notifications are raised)
    - action: script.persistent_notification
      data:
        group: weather
        channel: Alert
        targetDevices: home
        criticalNotification: true
        tag: rain-attic
        title: ☔ It's raining!
        message: >-
          Check the Attic window to ensure it's not raining in...
  mode: single
  max_exceeded: silent
- alias: 🌦️ | 📱 Dismiss Attic window notification (stops raining)
  id: 0bfb45f6-5516-4f37-86f1-d7bb7af88e94
  triggers:
    - trigger: numeric_state
      entity_id: sensor.weewx_rain_rate_hour
      below: 1.0
      for: "00:10:00"
  conditions: []
  actions:
    - action: persistent_notification.dismiss
      data:
        notification_id: rain-attic
  mode: single
- alias: 🌦️ | 📱 Dismiss Attic window notification (window closed)
  id: dd524898-9606-4c30-b7dc-d061515ee6bc
  triggers:
    - trigger: state
      entity_id: sensor.attic_window_position
      from:
        - ajar
        - open
      to:
        - ajar-locked
        - closed-ventilate
        - closed
  conditions:
    - condition: numeric_state
      entity_id: sensor.weewx_rain
      above: 0
  actions:
    - action: persistent_notification.dismiss
      data:
        notification_id: rain-attic
  mode: single
- alias: 🌦️ | 🔊 Announce expected rain (Buienradar forecast)
  id: 47715bbc-60bf-4417-9932-73e59a9edbf8
  triggers:
    - trigger: numeric_state
      entity_id: sensor.buienradar_precipitation_forecast_total
      above: 0.25
  conditions:
    # Don't bother if it's already raining...
    - condition: not
      conditions:
        - condition: numeric_state
          entity_id: sensor.weewx_rain_hour
          above: 0
  actions:
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          tag: forecast_rain
          # Buienradar forecasts 2-hours into the future – also, the expiry
          # allows %WAIT_REMAINING% to be used as an indication when rain is
          # expected (e.g. "in 30 minutes")
          expiry: "02:00:00"
          message: >-
            Rain is expected at {{
              (now() + timedelta(hours=2)) | as_timestamp |
                timestamp_custom('%H:%M')
            }}; that is %WAIT_REMAINING%
    # Wait for up to 4 hours for it to start raining
    - wait_for_trigger:
        - trigger: numeric_state
          # Note the use of the rain-rate (as opposed to "weewx_rain_hour", its
          # integral) – the former is more responsive, so better suited as a
          # trigger; the latter is better suited as the "it is raining"-
          # condition...
          entity_id: sensor.weewx_rain_rate_hour
          above: 1.0
      timeout: "04:00:00"
      continue_on_timeout: true
    - if:
        - >-
          {{ wait.trigger is not none }}
      # It started raining
      then:
        # Abort the announcement (for good measure – might have already expired)
        - event: tts_queue_abort
          event_data:
            tag: forecast_rain
        # Now wait for it to stop raining...
        - wait_for_trigger:
            - trigger: numeric_state
              entity_id: sensor.weewx_rain_hour
              below: 0.1
              for: "04:00:00"
          timeout: "24:00:00"
          continue_on_timeout: false
      # It didn't rain
      else:
        # Block – unconditionally – for 8 hours to prevent getting too "chatty"
        # with the rain announcements...
        - delay: "08:00:00"
  mode: single
  max_exceeded: silent
