#!/usr/bin/env bash

set -eo pipefail

if [ -n "$PUID" ] && [ -n "$PGID" ] ; then

  addgroup --gid "$PGID" androidtv
  adduser --system --uid "$PUID" --gid "$PGID" androidtv

else

  addgroup androidtv
  adduser --system --group androidtv androidtv

fi

# Symlink ADB-keys into AndroidTV's home-directory (where adb is hard-coded
# to look for them)

if [ -f /androidtv/keys/adbkey ] && [ -f /androidtv/keys/adbkey.pub ] ; then

  mkdir -p /home/androidtv/.android

  ln -s /androidtv/keys/adbkey /home/androidtv/.android/adbkey
  ln -s /androidtv/keys/adbkey.pub /home/androidtv/.android/adbkey.pub

  chown -R androidtv:androidtv /home/androidtv/.android

fi
