#!/usr/bin/env bash

set -eo pipefail

if ! id -u androidtv &> /dev/null; then

  if [ -n "$PUID" ] && [ -n "$PGID" ]; then

    addgroup --gid "$PGID" androidtv
    adduser --system --uid "$PUID" --gid "$PGID" androidtv

  else

    addgroup androidtv
    adduser --system --group androidtv androidtv

  fi

fi

# Symlink ADB-keys into AndroidTV's home-directory (where adb is hard-coded
# to look for them)

mkdir -p /home/androidtv/.android
chown -R androidtv:androidtv /home/androidtv/.android

if [ -f /androidtv/keys/adbkey ] && [ -f /androidtv/keys/adbkey.pub ]; then

  ln -sf /androidtv/keys/adbkey /home/androidtv/.android/adbkey
  ln -sf /androidtv/keys/adbkey.pub /home/androidtv/.android/adbkey.pub

fi
