- platform: integration
  source: sensor.power_all_lights
  name: Consumption (all lights)
  unit_prefix: k
  unit_time: h
  round: 3
- platform: integration
  source: sensor.ups_power_usage
  name: Consumption (UPS)
  unit_prefix: k
  unit_time: h
  round: 3
