# DD-WRT-1
- platform: snmp
  name: DD-WRT-1 1-minute load
  unique_id: 0f33ee17-36c1-4c64-bb67-a355ad3e63a0
  host: dd-wrt-1.sgraastra
  icon: mdi:chip
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: "%"
  value_template: >-
    {{ value | multiply(50) | round(1) }}
- platform: snmp
  name: DD-WRT-1 WAN in (total octets)
  unique_id: e7d276c1-8dca-4afe-8abc-05013781dd6c
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.10.5
  version: 2c
  accept_errors: true
- platform: snmp
  name: DD-WRT-1 WAN out (total octets)
  unique_id: 37aed17e-459b-4ad4-a66b-8c8e7d293b6a
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.16.5
  version: 2c
  accept_errors: true
- platform: derivative
  source: sensor.dd_wrt_1_wan_in_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN in (bps)
- platform: derivative
  source: sensor.dd_wrt_1_wan_out_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN OUT (bps)
# DD-WRT-2
- platform: snmp
  name: DD-WRT-2 1-minute load
  unique_id: 486c89c2-5461-4814-b440-3a4d4e13464c
  host: dd-wrt-2.sgraastra
  icon: mdi:chip
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: "%"
  value_template: >-
    {{ value | multiply(50) | round(1) }}
