- platform: mqtt
  state_topic: dd-wrt/ping/dd-wrt-1
  name: DD-WRT-1 Google DNS roundtrip time
  unit_of_measurement: ms
  icon: mdi:server-network
  value_template: >-
    {{ value | round(3) }}
  expire_after: 180
- platform: mqtt
  state_topic: dd-wrt/ping/dd-wrt-2
  name: DD-WRT-2 Google DNS roundtrip time
  unit_of_measurement: ms
  icon: mdi:server-network
  value_template: >-
    {{ value | round(3) }}
  expire_after: 180
