# DD-WRT-1
- platform: snmp
  name: DD-WRT-1 1-minute load
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: "%"
  value_template: >-
    {{ value | multiply(50) | round(1) }}
- platform: snmp
  name: DD-WRT-1 WAN in (total octets)
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.10.5
  version: 2c
  accept_errors: true
- platform: snmp
  name: DD-WRT-1 WAN out (total octets)
  host: dd-wrt-1.sgraastra
  baseoid: 1.3.6.1.2.1.2.2.1.16.5
  version: 2c
  accept_errors: true
- platform: derivative
  source: sensor.dd_wrt_1_wan_in_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN in (bps)
- platform: derivative
  source: sensor.dd_wrt_1_wan_out_total_octets
  unit_time: s
  unit: b
  name: DD-WRT-1 WAN OUT (bps)
- platform: template
  sensors:
    dd_wrt_1_wan_in_mbps:
      value_template: >-
        {{
          [(
            (
              states('sensor.dd_wrt_1_wan_in_bps')|float*8
            ) / 1000000
          )|round(2),0]|max
        }}
      unit_of_measurement: Mbps
      friendly_name: DD-WRT-1 WAN in (Mbps)
    dd_wrt_1_wan_out_mbps:
      value_template: >-
        {{
          [(
            (
              states('sensor.dd_wrt_1_wan_out_bps')|float*8
            ) / 1000000
          )|round(2),0]|max
        }}
      unit_of_measurement: Mbps
      friendly_name: DD-WRT-1 WAN out (Mbps)

# DD-WRT-2
- platform: snmp
  name: DD-WRT-2 1-minute load
  host: dd-wrt-2.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: "%"
  value_template: >-
    {{ value | multiply(50) | round(1) }}
