- platform: mqtt
  state_topic: femon/signal
  name: DVB-T signal-strength
  unit_of_measurement: "%"
  icon: mdi:signal-cellular-2
  value_template: >-
    {{ value | round(0) }}
  expire_after: 120
- platform: mqtt
  state_topic: femon/snr
  name: DVB-T signal-to-noise ratio
  unit_of_measurement: "%"
  icon: mdi:signal-cellular-2
  value_template: >-
    {{ value | round(0) }}
  expire_after: 120
