- platform: mqtt
  unique_id: 7c04a03b-5494-48b2-84cc-2a4f3d7839d3
  state_topic: gammu/signal
  name: Gammu signal-strength
  unit_of_measurement: "%"
  icon: mdi:signal-cellular-2
  value_template: >-
    {{ value_json.SignalPercent | round(0) }}
  availability:
    - topic: gammu/connected
      payload_available: 1
      payload_not_available: 0
