- platform: mqtt
  unique_id: 7c04a03b-5494-48b2-84cc-2a4f3d7839d3
  state_topic: gammu/signal
  name: Gammu signal-strength
  unit_of_measurement: "%"
  icon: mdi:signal-cellular-2
  value_template: >-
    {{ value_json.SignalPercent | round(0) }}
  availability:
    - topic: gammu/connected
      payload_available: 1
      payload_not_available: 0
# Following the MQTT Sensor manual ("Temporal mismatches between the state and
# the attribute data may occur if both the state and the attributes are changed
# simultaneously by the same MQTT message"), "json_attributes_topic" cannot be
# used to store the additional message attributes.
# As message contents is mainly processed via regular expressions anyway,
# concatenating them to the message body is sufficient for now...
- platform: mqtt
  unique_id: 773a0ad1-5f99-4271-8711-cd5faf2b6515
  state_topic: gammu/received
  name: Gammu received (message)
  icon: mdi:message-arrow-left-outline
  value_template: >-
    <{{ value_json.number }}> @ {{value_json.datetime}}:
    {{ value_json.text }}
- platform: mqtt
  unique_id: dbcbbc71-433d-4d48-a3b6-d9e38da373c6
  state_topic: gammu/sent
  name: Gammu sent (message)
  icon: mdi:message-arrow-right-outline
  value_template: >-
    <{{ value_json.number }}> @ {{value_json.datetime}}:
    {{ value_json.text }}
- platform: mqtt
  unique_id: 50dff5b0-8806-4fa4-b9e0-b53fdd642e9b
  state_topic: gammu/sent
  name: Gammu sent (result)
  icon: mdi:message-text-clock-outline
  value_template: >-
    {{ value_json.result }}
