# Estimate power consumption of all lights
#
# Made possible by the fact that (nearly) all lights in the house are Hue-based.
# Enumerates all lights that are turned on (and not a Hue-group, nor a Zigbee
# device erroneously identifying itself as a light). Provides an estimate that
# probably overshoots usage a bit (to keep things simple, light intensity is not
# factored in and lights are only roughly grouped).
#
# Lights are grouped as follows:
#   1.  Light-strips, assumed to be all 2 meters in length and using 50% of
#       their 24 Watt rating
#   2.  The Ensuite ceiling light (which contains 6 individual bulbs), assumed
#       to be using 50% of its 36 Watt rating
#   3.  All other lights (ranging from 6 to 9 Watt), assumed to be using 6 Watt
#       each
#
# This template sensor uses the "states.light"-domain; it should be updated in a
# way that limits its performance impact:
#   https://community.home-assistant.io/t/heads-up-upcoming-breaking-change-in-the-template-integration/223715

- platform: template
  sensors:
    power_lights_all:
      friendly_name: Power (all lights)
      unit_of_measurement: W
      value_template: >-
        {%- set result = namespace(watt=0) -%}
        {%- for light in states.light |
          selectattr('attributes.is_hue_group', 'undefined') |
          selectattr('state', 'eq', 'on') |
          selectattr('attributes.supported_features', 'gt', 0)
        -%}
          {%- if light.entity_id in
            [
              'light.hue_lightstrip_plus_1_2',
              'light.hue_lightstrip_plus_1_3',
              'light.hue_lightstrip_plus_1',
              'light.outdoor_lightstrip_garden',
              'light.extended_color_light_1_4'
            ]
          -%}
            {%- set result.watt = result.watt + 12 -%}
          {%- elif light.entity_id == 'light.hue_white_light_1' -%}
            {%- set result.watt = result.watt + 18 -%}
          {%- else -%}
            {%- set result.watt = result.watt + 6 -%}
          {%- endif -%}
        {%- endfor -%}
        {{ result.watt|int }}
- platform: integration
  source: sensor.power_lights_all
  name: consumption_lights_all
  unit_prefix: k
  round: 3
