# Estimate power consumption of all lights
#
# Made possible by the fact that all lights in the house are Hue-/Zigbee-based.
# Enumerates all lights that are turned on (and not a Hue-group nor a Home
# Assistant Light Group). Provides an estimate that probably overshoots usage a
# bit (to keep things simple, light intensity is not factored in and lights are
# only roughly grouped).
#
# Lights are grouped as follows:
#   0.  Zigbee entities that are not actually lights (no-op).
#   1.  Lights that are switched off are assumed to consume 0.4 Watt (based on
#       https://www.anandtech.com/show/6805/philips-hue-automated-home-lighting-gets-colorful/6)
#   2.  Light-strips, assumed to be all 2 meters in length and using 50% of
#       their 24 Watt rating
#   3.  The Ensuite ceiling light (which contains 6 individual bulbs), assumed
#       to be using 50% of its 36 Watt rating
#   4.  One of the Aqara smart-relay "gangs" in the Attic hallway connected to
#       three 3.5 Watt LED spots and one 18 Watt LEDtube, roughly 28 Watt.
#   5.  All other lights (ranging from 6 to 9 Watt), assumed to be using 6 Watt
#       each
#
# This template sensor uses the "states.light"-domain; it should be updated in a
# way that limits its performance impact:
#   https://community.home-assistant.io/t/heads-up-upcoming-breaking-change-in-the-template-integration/223715

- platform: template
  sensors:
    power_lights_all:
      friendly_name: Power (all lights)
      unit_of_measurement: W
      value_template: >-
        {%- set result = namespace(watt=0.0) -%}
        {%- for light in states.light |
          selectattr('attributes.is_hue_group', 'undefined') |
          selectattr('attributes.entity_id', 'undefined')
        -%}
          {%- if light.entity_id in
            [
              'light.range_extender_2',
              'light.smart_relay_1',
              'light.smart_relay_2'
            ]
          -%}
          {%- elif states(light.entity_id) == 'off' -%}
            {%- set result.watt = result.watt + 0.4 -%}
          {%- elif light.entity_id in
            [
              'light.hue_lightstrip_plus_1_2',
              'light.hue_lightstrip_plus_1_3',
              'light.hue_lightstrip_plus_1',
              'light.outdoor_lightstrip_garden',
              'light.extended_color_light_1_4'
            ]
          -%}
            {%- set result.watt = result.watt + 12 -%}
          {%- elif light.entity_id == 'light.hue_white_light_1' -%}
            {%- set result.watt = result.watt + 18 -%}
          {%- elif light.entity_id == 'light.smart_relay_4' -%}
            {%- set result.watt = result.watt + 28 -%}
          {%- else -%}
            {%- set result.watt = result.watt + 6 -%}
          {%- endif -%}
        {%- endfor -%}
        {{ result.watt|int }}
- platform: integration
  source: sensor.power_lights_all
  name: consumption_lights_all
  unit_prefix: k
  round: 3
