- platform: snmp
  name: Pi4 1-minute load
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.10.1.3.1
  version: 2c
  accept_errors: true
  unit_of_measurement: "%"
  value_template: >-
    {{ value | multiply(25) | round(1) }}
- platform: snmp
  name: Pi4 CPU temperature
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.8072.9999.9999.314.1
  version: 2c
  accept_errors: true
  unit_of_measurement: °C
  value_template: >-
    {{ (value|float/1000) | round(1) }}
- platform: snmp
  name: Pi4 memAvailReal (raw)
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.6.0
  version: 2c
  accept_errors: true
  unit_of_measurement: KiB
- platform: snmp
  name: Pi4 memCached (raw)
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.14.0
  version: 2c
  accept_errors: true
  unit_of_measurement: KiB
- platform: snmp
  name: Pi4 memBuffer (raw)
  host: pi4.sgraastra
  baseoid: 1.3.6.1.4.1.2021.4.15.0
  version: 2c
  accept_errors: true
  unit_of_measurement: KiB
- platform: template
  sensors:
    pi4_memory_available:
      value_template: >
        {{ ((
              (states('sensor.pi4_memavailreal_raw')|int) +
              (states('sensor.pi4_memcached_raw')|int) +
              (states('sensor.pi4_membuffer_raw')|int)
            )|float/1000) | round(0)
        }}
      unit_of_measurement: MiB
      friendly_name: Pi4 memory available
    pi4_memory_used_percentage:
      value_template: >
        {{  (
              (1 - (states('sensor.pi4_memory_available')|float)/4096) * 100
            ) | round(2)
        }}
      unit_of_measurement: "%"
      friendly_name: Pi4 memory used (percentage)
- platform: mqtt
  state_topic: tc66c/pi4/power_W
  name: Pi4 Power usage
  unit_of_measurement: W
  device_class: power
  value_template: >-
    {{ value | round(2) }}
