- platform: rest
  unique_id: 1f1982c0-e097-4302-b7d0-efdd7cc89ef9
  name: Prusa MINI+
  icon: mdi:printer-3d
  # Only attempt to query the *actual* RESTful API endpoint when the Prusa MINI+
  # is switched on (as indicated by its ping sensor)
  resource_template: >-
    {% if states('binary_sensor.prusa_mini_ping') == 'on' %}
      http://prusa-mini.sgraastra/api/telemetry
    {% else %}
      http://pi4.sgraastra:8123/local/prusa-mini-empty.json
    {% endif %}
  value_template: >-
    {% if value_json.progress is defined %}
      {{ value_json.progress | int(0) }}
    {% else %}
      0
    {% endif %}
  unit_of_measurement: "%"
  scan_interval: 60
  json_attributes:
    - flow_factor
    - material
    - pos_z_mm
    - printing_speed
    - temp_bed
    - temp_nozzle
    # The below attributes are only available while printing
    - print_dur
    - project_name
    - time_est
    - time_zone
