- platform: template
  sensors:
    ds1815_1_minute_load:
      value_template: >
        {{
          states('sensor.ds1815_cpu_load_average_1_min')|float |
            multiply(25) | round(1)
        }}
      unit_of_measurement: "%"
      friendly_name: ds1815 1-minute load
    ups_power:
      value_template: >
        {{
          (
            states('sensor.ups_nominal_real_power')|float *
              states('sensor.ups_load')|float / 100
          ) | round(0)
        }}
      unit_of_measurement: W
      device_class: power
      friendly_name: Back-UPS Pro 900 Power usage
    ups_battery_runtime_minutes:
      value_template: >
        {{
          (
            states('sensor.ups_battery_runtime')|float / 60
          ) | round(0)
        }}
      unit_of_measurement: min
      friendly_name: Back-UPS Pro 900 Battery Runtime (minutes)
- platform: integration
  source: sensor.ups_power
  name: consumption_ups
  unit_prefix: k
  unit_time: h
  round: 3
