# Due to the placement of the weather station, the wind direction is rather
# jittery. The below filter smooths out the measurements as bit. It's using a
# moving average instead of low-pass filter as the input time series is
# "unevenly spaced" (i.e. measurements come in as the wind direction changes,
# not at a regular interval).
- platform: filter
  name: WeeWX wind direction (filtered)
  entity_id: sensor.weewx_wind_direction
  filters:
    - filter: time_simple_moving_average
      type: last
      window_size: "00:30:00"
      precision: 0
- platform: filter
  name: WeeWX wind gust direction (filtered)
  entity_id: sensor.weewx_wind_gust_direction
  filters:
    - filter: time_simple_moving_average
      type: last
      window_size: "00:10:00"
      precision: 0
- platform: integration
  unique_id: d3d0b1ee-91bf-494c-a1fe-efae9ce92926
  source: sensor.weewx_rain_hour
  name: weewx_rain_total
  round: 1
  unit_time: h
  method: left
- platform: integration
  unique_id: 9f633e47-9970-4dd5-a924-7f89b51b4821
  source: sensor.weewx_evapotranspiration
  name: weewx_evapotranspiration_total
  round: 4
  unit_time: min
