- alias: 🛒 | 🔊 Announce Albert Heijn ETA (wakeup alarm snoozed or silenced)
  id: 381fa915-60ea-4d01-ab6c-51d245da3b8d
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.wakeup_snooze_time
    - platform: event
      event_type: wakeup_alarm_silenced
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.last_notification_albert_heijn_eta
          state:
            - unavailable
            - unknown
    # Albert Heijn ETA is for today
    - condition: template
      value_template: >-
        {{
          states('sensor.last_notification_albert_heijn_eta') | as_datetime
            >= today_at('00:00:00')
        }}
  action:
    - delay: 5
    - variables:
        eta_start: >-
          {%-
            set start = states('sensor.last_notification_albert_heijn_eta') |
              as_datetime
          -%}
          {{ start.hour }}:{{ start.minute }}
        eta_end: >-
          {%-
            set end = states('sensor.last_notification_albert_heijn_eta') |
              as_datetime + timedelta(seconds=state_attr(
                  'sensor.last_notification_albert_heijn_eta', 'interval'))
          -%}
          {{ end.hour }}:{{ end.minute }}
        eta_minutes: >-
          {{
            ((states('sensor.last_notification_albert_heijn_eta') |
              as_timestamp - now() | as_timestamp) / 60) | int
          }}
    - service: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          speaker: media_player.pi0_w2_speaker_bedroom
          # Cloud TTS chokes on "Heijn"...
          message: >-
            Good morning, Albert Heyn expects to arrive between {{ eta_start }}
            and {{ eta_end }}. That is in
            {% if eta_minutes < 55 %}
              {{ eta_minutes }} minutes...
            {% elif eta_minutes < 60 %}
              about an hour...
            {% else %}
              more than an hour...
            {% endif %}
  mode: single
- alias: 🛒 | 🔊 Queue Albert Heijn ETA announcement
  id: 4bc40f3a-f99c-4a8e-a76d-69bbe6992366
  trigger:
    - platform: state
      entity_id: sensor.last_notification_albert_heijn_eta
      from:
        - unavailable
        - unknown
  condition:
    # Prevent trigger on reload of the underlying template-entity. As it is not
    # possible to use a combination of "from" and "not_to" for the trigger, an
    # additional condition is needed.
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.last_notification_albert_heijn_eta
          state:
            - unknown
            - unavailable
  action:
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          expiry: "06:00:00"
          message: >-
            {%
              set eta = states('sensor.last_notification_albert_heijn_eta') |
                as_datetime
            %}
            {% set tomorrow = eta.day != now().day %}
            Albert Heyn expects to arrive {% if tomorrow is true%}
            tomorrow {% endif %} around {{ eta.hour }}:{{ eta.minute }}.
