- alias: 🛒/💤 |🔊 Queue Albert Heijn ETA announcement (everyone awake)
  id: 381fa915-60ea-4d01-ab6c-51d245da3b8d
  trigger:
    - trigger: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.last_notification_albert_heijn_eta
          state:
            - unavailable
            - unknown
    # Albert Heijn ETA is for today
    - condition: template
      value_template: >-
        {{
          states('sensor.last_notification_albert_heijn_eta') | as_datetime
            >= today_at('00:00:00')
        }}
  action:
    - variables:
        eta_start: >-
          {{
            states('sensor.last_notification_albert_heijn_eta') |
              as_timestamp | timestamp_custom('%H:%M')
          }}
        eta_end: >-
          {{
            (states('sensor.last_notification_albert_heijn_eta') |
              as_datetime + timedelta(seconds=state_attr(
                  'sensor.last_notification_albert_heijn_eta', 'interval'))
            ) | as_timestamp | timestamp_custom('%H:%M')
          }}
    - delay: 1 # Ensure "Good morning!" comes first
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: good_morning
          # Set to expire when at Albert Heijn's ETA. As an added benefit, this
          # allows %WAIT_REMAINING% to be used as a _dynamic_ indication as of
          # when Albert Heijn is expected to arrive (e.g. "in 30 minutes").
          expiry: >-
            {{
              [0,
                states('sensor.last_notification_albert_heijn_eta') |
                  as_timestamp - now() | as_timestamp
              ] | max
            }}
          message: >-
            Albert Heijn expects to arrive between {{ eta_start }} and
            {{ eta_end }}. That is %WAIT_REMAINING%
  mode: single
- alias: 🛒 | 🔊 Queue Albert Heijn ETA announcement
  id: 4bc40f3a-f99c-4a8e-a76d-69bbe6992366
  trigger:
    - trigger: state
      entity_id: sensor.last_notification_albert_heijn_eta
      not_to:
        - unknown
        - unavailable
  variables:
    albert_heijn_eta: >-
      {% from 'voice.jinja' import albert_heijn_eta %}
      {{ albert_heijn_eta() }}
  condition:
    - >-
      {{ albert_heijn_eta | trim != '' }}
    # Only relevant if ETA is in the future — prevents both stale notifications
    # (and the occasional notification that arrives after its actual ETA) from
    # getting queued...
    - >-
      {{
        states('sensor.last_notification_albert_heijn_eta') |
          as_datetime > now()
      }}
  action:
    # Abort any previously queued (and now invalid) announcements...
    - event: tts_queue_abort
      event_data:
        tag: albert_heijn_eta
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          tag: albert_heijn_eta
          expiry: "06:00:00"
          message: >-
            {{ albert_heijn_eta }}
