- alias: 🔊 | 🎂 Queue "Happy birthday!"
  id: 424f4e83-29a2-42b8-9031-07a1b1a0390d
  trigger:
    - platform: calendar
      event: start
      entity_id: calendar.home
  condition:
    - >-
      {{
        trigger.calendar_event.all_day is true and
        trigger.calendar_event.summary | trim
          is match('(?:🎂 ?)?Birthday', True)
      }}
  action:
    # The other "Good morning!"-announcements are queued up earlier (ie, at the
    # moment the wakeup alarm starts sounding) and released 5-seconds after the
    # below trigger; triggering here gives us the opportunity to impact
    # (ie, cancel) the other notifications...
    - wait_for_trigger:
        - platform: event
          event_type: timer.started
          event_data:
            entity_id: timer.wakeup_snooze_time
        - platform: event
          event_type: wakeup_alarm_silenced
      timeout: "12:00:00"
      continue_on_timeout: false
    # Abort all other "Good morning!"-announcements
    - event: tts_queue_abort
      event_data:
        tag: good_morning
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: good_morning
          priority: attention
          duration: 42
          expiry: "01:00:00"
          chime: false
          message: >-
            media-source://media_source/sd/audio/happy_birthday.ogg
  mode: single
