- alias: 🔊 | ⏰ Hourly "Dong!"
  id: d3514110-c85e-48ff-b60b-8dec439f0f6f
  trigger:
    # It seems "hours: *" is not the way to go — it works but (appears?) to
    # interfer with other automations running at the top of the hour... 🤨
    - platform: time_pattern
      seconds: 0
      minutes: 0
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
    - condition: state
      entity_id: media_player.nvidia_shield_tv
      state: "off"
    # Don't play when going to sleep / being asleep
    - condition: state
      entity_id: script.lights_out
      state: "off"
    - condition: state
      entity_id: timer.everyone_asleep_delay
      state: idle
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
    # Don't play while waking up
    - condition: state
      entity_id: script.wakeup_alarm
      state: "off"
    - condition: state
      entity_id: timer.wakeup_snooze_time
      state: idle
  action:
    # In Bedroom and Guestroom, the "Dong!" only sounds between 06:00 and 22:00
    - if:
        - condition: time
          after: "05:59:00"
          before: "22:59:00"
      then:
        - if:
            - condition: time
              after: "11:59:00"
              before: "12:01:00"
          # Special "Dong!" at noon
          then:
            - service: script.turn_on
              target:
                entity_id: script.tts_announce
              data:
                variables:
                  priority: regular
                  duration: 3
                  chime: false
                  message: >-
                    media-source://media_source/sd/audio/hourly_dong.mp3
          else:
            - service: script.turn_on
              target:
                entity_id: script.tts_announce
              data:
                variables:
                  priority: attention
                  duration: 2
                  chime: false
                  message: >-
                    media-source://media_source/sd/audio/Gentle_gong.ogg
      else:
        - service: script.turn_on
          target:
            entity_id: script.tts_announce
          data:
            variables:
              priority: regular
              duration: 2
              chime: false
              rooms:
                - attic
                - living_room
              message: >-
                media-source://media_source/sd/audio/Gentle_gong.ogg
  mode: single
