- alias: ðŸ”Š | ðŸ•¹ï¸ Goodnight message (bedside Smart Switches)
  id: 01987760-fad4-4e0c-a525-8d77c6c5cae3
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
  condition: []
  action:
    # If "Lights out" isn't yet running, double pressing the Smart Switches
    # starts that too (at the same time as this automation). To ensure the TTS
    # runs as expected in that case, don't directly abort if "Lights out" isn't
    # running but instead give it a short grace-period to start.
    - if:
        condition: state
        entity_id: script.lights_out
        state: "off"
      then:
        - wait_for_trigger:
            - platform: state
              entity_id: script.lights_out
              from: "off"
              to: "on"
          timeout: 10
          # Abort if "Lights out" didn't start
          continue_on_timeout: false
    - service: script.turn_on
      target:
        entity_id: script.tts_announce
      data:
        variables:
          speaker: media_player.pi0_w2_speaker_bedroom
          priority: whisper
          message: >-
            Switching off all lights.
            {% if states('input_boolean.alarm_auto_arm_night') == 'on' %}
              The Home Alarm will arm once everyone is asleep.
            {% endif %}
            {% if states('input_boolean.wakeup_alarm_mute') == 'off' %}
              The wakeup alarm will sound at {{
                today_at(states('input_datetime.wakeup')) |
                as_timestamp | timestamp_custom('%H:%M')
              }}.
            {% endif %}
            {%
              if states('sensor.last_notification_albert_heijn_eta')
                not in ['unknown', 'unavailable']
            %}
              {%
                set ah_eta =
                  states('sensor.last_notification_albert_heijn_eta') |
                  as_datetime
              %}
              Albert Heyn expects to arrive around
              {{ ah_eta.hour }}:{{ ah_eta.minute }}.
            {% endif %}
            Good night; sleep tight...
  mode: single
  max_exceeded: silent
