- alias: >-
    🔊 | 🕹️ Trigger "Good morning!" announcements (wakeup alarm snoozed
    or silenced)
  id: 5cfff24f-e0c7-422a-a181-9836432e1cf4
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.wakeup_snooze_time
    - platform: event
      event_type: wakeup_alarm_silenced
  action:
    # Slight delay both for "ergonomic" reasons and to allow other automations
    # to queue up their TTS announcements
    - delay: 5
    - event: tts_announce
      event_data:
        speaker: media_player.pi0_w2_speaker_bedroom
        tag: good_morning
- alias: 🔊 | 💤 Queue "Good morning!" (everyone awake)
  id: f1a0a203-6d0e-4c91-99a8-ced118c4c478
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  action:
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: good_morning
          expiry: "01:00:00"
          message: Good morning!
  mode: single
- alias: 🔊 | 💤 Queue "Activity while armed" announcement (everyone awake)
  id: bd31f54a-d88e-44d0-958b-4da2eb248150
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  variables:
    activity_while_armed: >-
      {% from 'voice.jinja' import activity_while_armed %}
      {{ activity_while_armed() }}
  condition:
    - >-
      {{ activity_while_armed | trim != '' }}
  action:
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: good_morning
          expiry: "01:00:00"
          chime: false
          message: >-
            While you were asleep, {{ activity_while_armed }}.
  mode: single
