- alias: Trigger "Goodnight" announcements
  id: 6af957b0-bc4e-489c-8ff7-4ae492b7ca21
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  conditions: []
  actions:
    - variables:
        room: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            living_room
          {% else %}
            bedroom
          {% endif %}
        priority: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            regular
          {% else %}
            whisper
          {% endif %}
    - parallel:
        # Release all queued up "attention"
        - event: tts_attention
          event_data:
            room: >-
              {{ room }}
        - sequence:
            # Give the other announcements time to queue up...
            - delay: 5
            # ...and finally add a "Goodnight" at the end of the queue
            - action: script.turn_on
              target:
                entity_id: script.tts_queue
              data:
                variables:
                  channel: announce
                  tag: goodnight
                  priority: >-
                    {{ priority }}
                  message: Goodnight...
            - event: tts_announce
              event_data:
                room: >-
                  {{ room }}
                tag: goodnight
  mode: single
  max_exceeded: silent
- alias: Queue "Lights off"-announcement
  id: 4bce7cff-f340-4fd7-9b18-b6a7aa85d38f
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  conditions: []
  actions:
    - delay: 2
    - variables:
        priority: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            regular
          {% else %}
            whisper
          {% endif %}
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: >-
            {{ priority }}
          message: >-
            {% from 'voice.jinja' import goodnight_alarm %}
            Switching off all lights.
            {{ goodnight_alarm() }}
  mode: single
  max_exceeded: silent
- alias: Queue "Attic window open"-warning
  id: d7e4036d-7484-4bd0-a688-601cb7f5c98c
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  conditions:
    - condition: state
      entity_id: sensor.attic_window_position
      state: open
  actions:
    - delay: 1 # Queue this one up first
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: regular
          message: >-
            The Attic window is still open
  mode: single
  max_exceeded: silent
