- alias: >-
    🔊 | 🕹️ Trigger "Goodnight" announcements ("Lights out"-script triggered)
  id: 6af957b0-bc4e-489c-8ff7-4ae492b7ca21
  trigger:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  condition: []
  action:
    - variables:
        room: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            living_room
          {% elif states('binary_sensor.occupancy_bed') == 'on' %}
            bedroom
          {% endif %}
    - if: >-
        {{ room in ['living_room', 'bedroom'] }}
      then:
        - event: tts_attention
          event_data:
            room: >-
              {{ room }}
        - delay: 2
        - event: tts_announce
          event_data:
            room: >-
              {{ room }}
            tag: goodnight
  mode: single
  max_exceeded: silent
- alias: 🔊 | 💡 Queue "Goodnight" announcements ("Lights out" triggered)
  id: 4bce7cff-f340-4fd7-9b18-b6a7aa85d38f
  trigger:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    albert_heijn_eta: >-
      {% from 'voice.jinja' import albert_heijn_eta %}
      {{ albert_heijn_eta() }}
  action:
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: whisper
          message: >-
            {% from 'voice.jinja' import goodnight_alarm %}
            Switching off all lights.
            {{ goodnight_alarm() }}
    - if:
        - >-
          {{ albert_heijn_eta | trim != '' }}
        # Only relevant if Albert Heijn ETA is in the future — otherwise we're
        # probably about to replay this morning's announcement...
        - >-
          {{
            states('sensor.last_notification_albert_heijn_eta') |
              as_datetime > now()
          }}
      then:
        - action: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: whisper
              message: >-
                {{ albert_heijn_eta }}
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: whisper
          message: Goodnight...
  mode: single
  max_exceeded: silent
