- alias: 🔊 | 🕹️ Trigger "Goodnight" announcements (bedside Smart Switches)
  id: 01987760-fad4-4e0c-a525-8d77c6c5cae3
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
  condition: []
  action:
    # If "Lights out" isn't yet running, double pressing the Smart Switches
    # starts that too (at the same time as this automation). To ensure the TTS
    # runs as expected, don't directly abort if "Lights out" isn't running;
    # instead give it a couple seconds and try again...
    # Intentionally not using a "wait-for-trigger" as past experience has shown
    # that in this specific instance, "Lights out" often started "in between"
    # the state check and the trigger becoming active (essentially missing the
    # intended state-transition). The below is crude, but more reliable.
    - if:
        condition: state
        entity_id: script.lights_out
        state: "off"
      then:
        - delay: 2
    # Mental note: This should be _outside_ "then"; if it's inside it just
    # aborts the rest of the "then" block, not the entire automation...
    - condition: state
      entity_id: script.lights_out
      state: "on"
    # Release all (if any) regular TTS announcements first
    - event: tts_attention
      event_data:
        speaker: media_player.pi0_w2
    # Slight delay to allow for the ("announce") TTS queue to fill
    - delay: 2
    - event: tts_announce
      event_data:
        speaker: media_player.pi0_w2
        tag: goodnight
  mode: single
  max_exceeded: silent
- alias: >-
    🔊 | 🕹️ Trigger "Goodnight" announcements ("Lights out" triggered from
    Kitchen tablet)
  id: 6af957b0-bc4e-489c-8ff7-4ae492b7ca21
  trigger:
    - platform: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  condition:
    - >-
      {{ trigger.to_state.context.user_id == tablet_kitchen_user_id }}
  action:
    # Release all (if any) regular TTS announcements first
    - event: tts_attention
      event_data:
        speaker: media_player.bpi_m2z
    # Slight delay to allow for the ("announce") TTS queue to fill
    - delay: 2
    - event: tts_announce
      event_data:
        speaker: media_player.bpi_m2z
        tag: goodnight
  mode: single
  max_exceeded: silent
- alias: 🔊 | 💡 Queue "Goodnight" announcements ("Lights out" triggered)
  id: 4bce7cff-f340-4fd7-9b18-b6a7aa85d38f
  trigger:
    - platform: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    goodnight_alarm: >-
      {% from 'voice.jinja' import goodnight_alarm %}
      {{ goodnight_alarm() }}
    albert_heijn_eta: >-
      {% from 'voice.jinja' import albert_heijn_eta %}
      {{ albert_heijn_eta() }}
  action:
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: whisper
          message: Switching off all lights.
    - if:
        - >-
          {{ goodnight_alarm | trim != '' }}
      then:
        - service: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: whisper
              chime: false
              message: >-
                {{ goodnight_alarm }}
    - if:
        - >-
          {{ albert_heijn_eta | trim != '' }}
        # Only relevant if Albert Heijn ETA is in the future — otherwise we're
        # probably about to replay this morning's announcement...
        - >-
          {{
            states('sensor.last_notification_albert_heijn_eta') |
              as_datetime > now()
          }}
      then:
        - service: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: whisper
              chime: false
              message: >-
                {{ albert_heijn_eta }}
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: whisper
          chime: false
          message: Goodnight...
  mode: single
  max_exceeded: silent
