- alias: Trigger "Goodnight" announcements
  id: 6af957b0-bc4e-489c-8ff7-4ae492b7ca21
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  conditions: []
  actions:
    - variables:
        room: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            living_room
          {% else %}
            bedroom
          {% endif %}
    - event: tts_attention
      event_data:
        room: >-
          {{ room }}
    - delay: 2
    - event: tts_announce
      event_data:
        room: >-
          {{ room }}
        tag: goodnight
  mode: single
  max_exceeded: silent
- alias: Queue "Goodnight" announcements
  id: 4bce7cff-f340-4fd7-9b18-b6a7aa85d38f
  triggers:
    - trigger: state
      entity_id: script.lights_out
      from: "off"
      to: "on"
  variables:
    albert_heijn_eta: >-
      {% from 'voice.jinja' import albert_heijn_eta %}
      {{ albert_heijn_eta() }}
    tablet_kitchen_user_id: !secret tablet_kitchen_user_id
  conditions: []
  actions:
    - variables:
        priority: >-
          {% if trigger.to_state.context.user_id == tablet_kitchen_user_id %}
            regular
          {% else %}
            whisper
          {% endif %}
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: >-
            {{ priority }}
          message: >-
            {% from 'voice.jinja' import goodnight_alarm %}
            Switching off all lights.
            {{ goodnight_alarm() }}
    - if:
        - >-
          {{ albert_heijn_eta | trim != '' }}
        # Only relevant if Albert Heijn ETA is in the future — otherwise we're
        # probably about to replay this morning's announcement...
        - >-
          {{
            states('sensor.last_notification_albert_heijn_eta') |
              as_datetime > now()
          }}
      then:
        - action: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              channel: announce
              tag: goodnight
              priority: >-
                {{ priority }}
              message: >-
                {{ albert_heijn_eta }}
    - action: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          channel: announce
          tag: goodnight
          priority: >-
            {{ priority }}
          message: Goodnight...
  mode: single
  max_exceeded: silent
