mqtt:
  host: pi4.sgraastra
  port: 1883
  client_id: pi0-speaker-bt-mqtt-gateway
  availability_topic: bt-mqtt-gateway/pi0-speaker

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35
  command_retries: 0
  update_retries: 0
  workers:
    miflora:
      args:
        devices:
          bonsai_living_room: C0:FF:EE:12:34:56
          calathea_living_room: C0:FF:EE:12:34:56
          strelitzia_attic: C0:FF:EE:12:34:56
        topic_prefix: miflora
        per_device_timeout: 6
      update_interval: 1200
