version: "2.3"

services:
  bt-mqtt-gateway:
    # Digest-pin the "linux/arm/v6"-image (the version of Docker on RPi Zero
    # Raspbian doesn't support multi-arch; without this it _will_ pull the
    # wrong architecture...)
    image: zewelor/bt-mqtt-gateway@sha256:f592afa18000bf59c712f1f85d1c5b2521bae1a8fe92fc6df22fcbf3d25ec2c6
    restart: always
    # environment:
    #  - DEBUG=true
    volumes:
      - ./config.yaml:/config.yaml
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
