# The colour is modified when "script.tts_announce" gets called. It is restored
# whenever one the satellites starts listening (as this is the only way to do
# so covertly).
- alias: Restore HA Voice LED-ring colour
  id: 99916b32-acee-4e00-8d55-836df3413ad7
  trigger:
    - trigger: state
      entity_id:
        - assist_satellite.ha_voice_living_room
        - assist_satellite.ha_voice_attic
        - assist_satellite.ha_voice_bedroom
        - assist_satellite.ha_voice_guestroom
      from: idle
      to: listening
  condition: []
  action:
    - variables:
        led_ring: >-
          {%
            if trigger.to_state.entity_id ==
              'assist_satellite.ha_voice_living_room'
          %}
            light.ha_voice_living_room_led_ring
          {%
            elif trigger.to_state.entity_id ==
              'assist_satellite.ha_voice_attic'
          %}
            light.ha_voice_attic_led_ring
          {%
            elif trigger.to_state.entity_id ==
              'assist_satellite.ha_voice_bedroom'
          %}
            light.ha_voice_bedroom_led_ring
          {%
            elif trigger.to_state.entity_id ==
              'assist_satellite.ha_voice_guestroom'
          %}
            light.ha_voice_guestroom_led_ring
          {% endif %}
    - action: light.turn_on
      data:
        brightness: 180
        rgb_color:
          - 0
          - 0
          - 255
      target:
        entity_id: >-
          {{ led_ring }}
    - wait_template: >-
        {{ states(trigger.to_state.entity_id) == 'idle' }}
      timeout: "00:05:00"
      continue_on_timeout: false
    - action: light.turn_off
      target:
        entity_id: >-
          {{ led_ring }}
  mode: parallel
  max: 3
