- alias: 💡 | 🕹️ Turn on Attic hallway lights (Dimmer Switch)
  id: 26a80c46-4ba4-4721-b650-6b0fccf034ef
  description: ''
  mode: single
  trigger:
    - device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id: light.attic_hallway
- alias: 💡 | 🕹️ Turn off Attic hallway lights (Dimmer Switch)
  id: d248cca1-d887-40b2-966a-5bbc2ebd84dd
  description: ''
  mode: single
  trigger:
    - device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_off
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id: light.attic_hallway
