- alias: Turn on Attic hallway lights
  id: 26a80c46-4ba4-4721-b650-6b0fccf034ef
  triggers:
    - trigger: device
      device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      type: remote_button_short_press
      subtype: turn_on
    - trigger: device
      device_id: 5999769c0e60efa48786c19add551dec
      domain: deconz
      type: remote_button_short_press
      subtype: turn_on
  conditions: []
  actions:
    - action: light.turn_on
      target:
        entity_id: light.attic_hallway
    - action: timer.start
      target:
        entity_id: timer.attic_hallway_motion_pause
- alias: Cycle through Attic hallway gangs
  id: 1d18a07f-cd2b-49ac-bcd8-ab48089558c9
  triggers:
    - trigger: device
      device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      type: remote_button_short_press
      subtype: dim_up
    - trigger: device
      device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      type: remote_button_short_press
      subtype: dim_down
    - trigger: device
      device_id: 5999769c0e60efa48786c19add551dec
      domain: deconz
      type: remote_button_short_press
      subtype: dim_up
    - trigger: device
      device_id: 5999769c0e60efa48786c19add551dec
      domain: deconz
      type: remote_button_short_press
      subtype: dim_down
  conditions:
    - condition: state
      entity_id: light.attic_hallway
      state: "on"
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id:
                - light.attic_hallway_up
                - light.attic_hallway_down
              state: "on"
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.attic_hallway_down
        - conditions:
            - condition: state
              entity_id: light.attic_hallway_up
              state: "on"
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.attic_hallway_up
            - action: light.turn_on
              target:
                entity_id: light.attic_hallway_down
      default:
        - action: light.turn_on
          target:
            entity_id: light.attic_hallway
- alias: Turn off Attic hallway lights
  id: d248cca1-d887-40b2-966a-5bbc2ebd84dd
  triggers:
    - trigger: device
      device_id: c7a32fb1be6494d32caafb27134fee28
      domain: deconz
      type: remote_button_short_press
      subtype: turn_off
    - trigger: device
      device_id: 5999769c0e60efa48786c19add551dec
      domain: deconz
      type: remote_button_short_press
      subtype: turn_off
  conditions: []
  actions:
    - action: timer.cancel
      target:
        entity_id: timer.attic_hallway_motion_pause
    - action: light.turn_off
      target:
        entity_id: light.attic_hallway
- alias: Turn off Attic hallway lights
  id: b4a35562-ea3c-4e01-9d4e-ee0f3fead943
  triggers:
    - trigger: event
      event_type: timer.finished
      event_data:
        entity_id: timer.attic_hallway_motion_pause
  conditions: []
  actions:
    - action: light.turn_off
      target:
        entity_id: light.attic_hallway
- alias: Attic scene to "Concentrate"
  id: 7f5910f6-98e5-4c59-ab83-e349f38f0022
  triggers:
    - trigger: state
      entity_id: sensor.hue_scene_attic
      to: Bright
      for: "00:00:30"
    - trigger: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: sensor.hue_scene_attic
      state: Bright
  actions:
    - action: hue.activate_scene
      target:
        entity_id: scene.attic_concentrate
      data:
        transition: 600
- alias: Attic scene to "Bright"
  id: 03cf9d49-66ce-4f55-9f59-a2faceff1f6d
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions:
    - condition: state
      entity_id: sensor.hue_scene_attic
      state: Concentrate
  actions:
    - action: hue.activate_scene
      target:
        entity_id: scene.attic_bright
      data:
        transition: 600
