- alias: Bathroom light on
  id: 63b00f23-043a-4d8b-9974-03a7e850e897
  triggers:
    - trigger: state
      entity_id: binary_sensor.occupancy_bathroom
      from: "off"
      to: "on"
    # Also trigger (ie, restart) the automation when it gets too dark in the
    # Bathroom. Initially we might not have triggered because it was too bright;
    # this ensures the lights go one when it gets darker outside...
    - trigger: numeric_state
      entity_id: sensor.lightlevel_bathroom
      below: 200
  conditions:
    - condition: numeric_state
      entity_id: sensor.lightlevel_bathroom
      below: 200
    - condition: state
      entity_id: binary_sensor.occupancy_bathroom
      state: "on"
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  actions:
    - if:
        - condition: state
          entity_id: sensor.time_of_day
          state:
            - dusk
            - night
      then:
        - if:
            - condition: state
              entity_id: input_boolean.everyone_asleep
              state: "on"
          then:
            # Nighttime (everyone asleep)
            - action: scene.turn_on
              target:
                entity_id: scene.bathroom_nighttime
          else:
            # Evenings
            - action: scene.turn_on
              target:
                entity_id: scene.bathroom_bright
      else:
        # Daytime
        - action: scene.turn_on
          target:
            entity_id: scene.bathroom_concentrate
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.occupancy_bathroom
          from: "on"
          to: "off"
      timeout: "02:00:00"
    - condition: state
      entity_id: light.bathroom
      state: "on"
    - action: light.turn_on
      data:
        brightness_step_pct: -30
      target:
        entity_id: light.bathroom
    - delay: "00:00:30"
    - action: light.turn_off
      target:
        entity_id: light.bathroom
  mode: restart
