- alias: ðŸ’¡ | ðŸ•¹ï¸ Bedroom lights toggle (bedside Smart Switches)
  id: f03f5e56-2eaf-4bc0-8424-d316445b0236
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition:
    # Don't act when the wakeup alarm is sounding or snoozed (the light is
    # supposed to stay on in those cases)
    - condition: state
      entity_id: script.wakeup_alarm
      state: "off"
    - condition: state
      entity_id: timer.wakeup_snooze_time
      state: idle
  action:
    - service: light.toggle
      target:
        entity_id: light.bedroom
  mode: single
- alias: ðŸ’¡ | ðŸ•¹ï¸ All lights out (bedside Smart Switches)
  id: bce1284e-8bd4-4234-bbbc-652c4a3c192d
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
  condition:
    # Only act at night, if the Bedroom lights are on, and everyone is not
    # asleep yet
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: state
      entity_id: light.bedroom
      state: "on"
    # This condition is additionally relevant as it prevents interfering with
    # the wakeup alarm silencing automation (which triggers on double press too)
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
  action:
    # Don't block on the (long-running) "Lights out"-script
    - service: script.turn_on
      target:
        entity_id: script.lights_out
    - service: tts.cloud_say
      data:
        entity_id: media_player.pi0_speaker_bedroom
        message: >-
          Switching off all lights.
          {% if states('input_boolean.alarm_auto_arm_night') == 'on' -%}
            The Home Alarm will arm once everyone is asleep.
          {%- endif %}
          {% if states('input_boolean.wakeup_alarm_mute') == 'off' -%}
            The wakeup alarm will sound at {{
              today_at(states('input_datetime.wakeup')) |
              as_timestamp | timestamp_custom('%H:%M')
            -}}.
          {%- endif %}
          Sleep tight; good night.
        language: en-GB
    - service: light.turn_off
      data:
        transition: 30
        entity_id: light.bedroom
  mode: single
