- alias: 💡 | 🕹️ Bedroom lights toggle (bedside Smart Switches)
  id: f03f5e56-2eaf-4bc0-8424-d316445b0236
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition:
    # Don't act when the wakeup alarm is sounding or snoozed (the light is
    # supposed to stay on in those cases)
    - condition: state
      entity_id: script.wakeup_alarm
      state: "off"
    - condition: state
      entity_id: timer.wakeup_snooze_time
      state: idle
  action:
    - service: light.toggle
      target:
        entity_id: light.bedroom
  mode: single
- alias: 💡 | 🕹️ All lights out (bedside Smart Switches)
  id: bce1284e-8bd4-4234-bbbc-652c4a3c192d
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_double_press
      subtype: turn_on
  condition:
    # Only act at night, if the "Lights out"-script isn't running, and not
    # everyone is asleep yet
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: state
      entity_id: script.lights_out
      state: "off"
    # This condition is additionally relevant as it prevents interfering with
    # the "Silence wakeup alarm"-automation (which triggers on double press
    # too).
    # There is some time between "Lights out" finishing and "Everyone asleep"
    # activating. As the "Lights out"-script is idempotent running this
    # automation again in that period doesn't cause any issues, so no attempt
    # is made to prevent this eventuality.
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "off"
  action:
    # Flash Bedroom lights to provide feedback
    - service: light.turn_on
      data:
        flash: short
      entity_id: light.bedroom
    # Don't block on the (long-running) "Lights out"-script
    - service: script.turn_on
      target:
        entity_id: script.lights_out
    # Delay for 2 seconds to prevent switching off the Bedroom lights from
    # interfering with flashing them
    - delay: 2
    # Switch off the upstairs Hallway light
    - if:
        condition: state
        entity_id: light.upstairs_hallway
        state: "on"
      then:
        - service: light.turn_off
          data:
            transition: 10
            entity_id: light.upstairs_hallway
    # Switch off the Bedroom lights
    - condition: state
      entity_id: light.bedroom
      state: "on"
    - service: light.turn_off
      data:
        transition: 10
        entity_id: light.bedroom
  mode: single
