- alias: 💡 | ⏰ Inside lights on (dark outside when everyone wakes up)
  id: 4ad4a1ef-cc9c-4193-b212-f7dbfa20cd72
  trigger:
    # The "wakeup" time can happen multiple times during a morning cycle; as we
    # only act if lights are off, there's little harm in running this automation
    # multiple times (could actually be useful: Someone getting up early might
    # have switched the lights off on their way out the door).
    - platform: time
      at: input_datetime.wakeup
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: night
        - condition: state
          entity_id: sensor.time_of_day
          state: dawn
  action:
    # Living room
    - if:
        - condition: state
          entity_id: light.living_room
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.living_room_ambiance
    # Ensuite
    - if:
        - condition: state
          entity_id: light.ensuite
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.ensuite_orchid
    # Kitchen
    - if:
        - condition: state
          entity_id: light.kitchen
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.kitchen_ambiance
    # Hallway
    - if:
        - condition: state
          entity_id: light.hallway
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.hallway_evening
  mode: single
- alias: >-
    💡 | ⏰ Inside lights off – Living room (daily at sunrise;
    daytime lighting aware)
  id: 4adbf84d-a5d3-478a-b422-ea2a3d505c3e
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.living_room
      state: "on"
  action:
    # If the light _doesn't_ transition to Daytime within 30 seconds, turn it
    # off... This allows the daytime lighting automation to take precedence
    - wait_for_trigger:
        - platform: state
          entity_id: sensor.hue_scene_living_room
          to: Daytime
      timeout: 30
      continue_on_timeout: true
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - service: light.turn_off
      target:
        entity_id: light.living_room
  mode: single
- alias: >-
    💡 | ⏰ Inside lights off – Ensuite (daily at sunrise)
  id: a3d47ffd-337d-4c61-ba82-b1600ca671ff
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.ensuite
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.ensuite
  mode: single
- alias: >-
    💡 | ⏰ Inside lights off – Kitchen (daily at sunrise;
    daytime lighting aware)
  id: 36c03621-a126-457e-b916-a0af315c7a72
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.kitchen
      state: "on"
    # Never override "Bright (custom)" – it's based on sustained activity in
    # the Kitchen and is separately managed
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: sensor.hue_scene_kitchen
          to: Daytime
      timeout: 30
      continue_on_timeout: true
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - service: script.hue_activate_scene_kitchen
      data:
        turn_off: true
  mode: single
- alias: >-
    💡 | ⏰ Inside lights off – Downstairs hallway (daily at sunrise;
    daytime lighting aware)
  id: be42179a-5665-4e50-8a2a-e474386ba982
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.hue_filament_bulb_1_4
          state: "on"
        - condition: state
          entity_id: light.hue_filament_bulb_1_5
          state: "on"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id:
            - light.hue_filament_bulb_1_4
            - light.hue_filament_bulb_1_5
          attribute: brightness
          to: 128
      timeout: 30
      continue_on_timeout: true
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - service: light.turn_off
      target:
        entity_id:
          - light.hue_filament_bulb_1_4
          - light.hue_filament_bulb_1_5
  mode: single
- alias: >-
    💡 | ⏰ Inside lights off – Upstairs hallway (daily at sunrise;
    daytime lighting aware)
  id: cb13a7e2-2a2a-4788-ac6e-efe09b10d0fe
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.upstairs_hallway
      state: "on"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: light.upstairs_hallway
          attribute: brightness
          # This value is hard-coded in "📄 light/daytime.yaml"
          to: 128
      timeout: 30
      continue_on_timeout: true
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - service: light.turn_off
      target:
        entity_id: light.upstairs_hallway
  mode: single
# The "House lights" and "Garden lights" automations guard against exceptional
# situations (mainly initiated in "📄 alarm/alert.yaml"). Under normal
# circumstances they _don't_ run – the lights they switch off should already be
# off at sunrise...
- alias: 💡 | ⏰ House lights off (daily at sunrise)
  id: 314514eb-0cce-4519-833d-40300537a27b
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.front_back_door
          state: "on"
        - condition: state
          entity_id: light.guestroom
          state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.front_back_door
          - light.guestroom
  mode: single
- alias: 💡 | ⏰ Garden lights off (daily at sunrise)
  id: bca8278d-d0b5-41a6-a828-8310255cb93d
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.garden
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.garden
  mode: single
