- alias: 💡 | ⏰ Inside lights on (dark outside when everyone wakes up)
  id: 4ad4a1ef-cc9c-4193-b212-f7dbfa20cd72
  trigger:
    # The trigger on "everyone asleep" (and not "wakeup time") is intentional:
    # Everyone asleep toggles once per day (at the first "wakeup time"), the
    # wakeup time itself can happen multiple times daily (occupants getting up
    # at different times; snoozing the alarm; etc.) – the lights should only go
    # on once though...
    - platform: state
      entity_id: input_boolean.everyone_asleep
      from: "on"
      to: "off"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: night
        - condition: state
          entity_id: sensor.time_of_day
          state: dawn
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.living_room
              state: "off"
          sequence:
            - service: hue.hue_activate_scene
              data:
                group_name: Living room
                scene_name: Ambiance
    - choose:
        - conditions:
            - condition: state
              entity_id: light.kitchen
              state: "off"
          sequence:
            - service: hue.hue_activate_scene
              data:
                group_name: Kitchen
                scene_name: Ambiance
    - choose:
        - conditions:
            - condition: state
              entity_id: light.hallway
              state: "off"
          sequence:
            - service: hue.hue_activate_scene
              data:
                group_name: Hallway
                scene_name: Evening
  mode: single
- alias: 💡 | ⏰ Inside lights off (daily at sunrise)
  id: 314514eb-0cce-4519-833d-40300537a27b
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.living_room
          state: "on"
        - condition: state
          entity_id: light.kitchen
          state: "on"
        - condition: state
          entity_id: light.hallway
          state: "on"
        - condition: state
          entity_id: light.front_back_door
          state: "on"
        - condition: state
          entity_id: light.guestroom
          state: "on"
  action:
    - service: light.turn_off
      entity_id:
        - light.living_room
        - light.kitchen
        - light.hallway
        - light.front_back_door
        - light.guestroom
  mode: single
- alias: 💡 | ⏰ Garden lights off (daily at civil dawn)
  id: bca8278d-d0b5-41a6-a828-8310255cb93d
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: night
      to: dawn
    # Run again at sunrise – other automations might trigger the lights during
    # twilight; here we ensure they are switched off properly again
    - platform: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
  condition:
    - condition: state
      entity_id: light.garden
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.garden
  mode: single
