- alias: Kitchen lights on
  id: 5b3387c6-763b-47da-b938-1eaefcd0ffd1
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_47
      for: "00:01:00"
      below: 80
    - trigger: state
      id: dawn
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: time
      id: wakeup
      at: input_datetime.wakeup
    - trigger: state
      id: obscured
      entity_id: sensor.sun_relative_to_house
      to: obscured
  conditions:
    # In case of the wakeup-trigger, "everyone asleep" isn't relevant (and most
    # likely still active as there's a race condition between this automation
    # and the one that toggles "everyone asleep" off)
    # The reason for this complexity is that "everyone asleep" can potentially
    # also toggle off at night (when someone comes home late).
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "off"
        - condition: trigger
          id: wakeup
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.lightlevel_47
          below: 80
        # In case of the "obscured"-trigger we don't care about the light-level,
        # we just ensure the Kitchen is already in its daytime setting
        - condition: and
          conditions:
            - condition: trigger
              id: obscured
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Daytime
    # Never override "Bright (custom)" – this is handled by the activity
    # activations in the Kitchen (which also handles restoring the lights back
    # to their daytime setting if so required)
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_kitchen
          state: Bright (custom)
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
      then:
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_bright_custom
            transition: >-
              {{ 15 if states('light.kitchen') == 'off' else 600 }}
      else:
        - action: script.hue_activate_scene_kitchen
          data:
            scene_id: scene.kitchen_daytime
            transition: >-
              {{ 15 if states('light.kitchen') == 'off' else 600 }}
  mode: single
- alias: Kitchen lights off
  id: 2c48592e-2d8b-42f1-880b-44183ffc442a
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_47
      for: "00:10:00"
      above: 90
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: sensor.hue_scene_kitchen
      state: Daytime
  actions:
    - action: script.hue_activate_scene_kitchen
      data:
        turn_off: true
        transition: 15
  mode: single
- alias: Living room lights on
  id: 05a5eb32-be80-4130-a561-d21015851ae8
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_194
      for: "00:02:00"
      below: 1500
    - trigger: state
      id: dawn
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: time
      id: wakeup
      at: input_datetime.wakeup
    - trigger: state
      id: obscured
      entity_id: sensor.sun_relative_to_house
      to: obscured
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "off"
        - condition: trigger
          id: wakeup
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.lightlevel_194
          below: 1500
        - condition: and
          conditions:
            - condition: trigger
              id: obscured
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Daytime
    # Don't act when the Android TV is playing – lights are not automatically
    # dimmed during the day, but we don't want to run the risk of interfering
    # with manual adjustments
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.eh_ls800b
          state: "on"
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
      then:
        - action: hue.activate_scene
          target:
            entity_id: scene.living_room_active
          data:
            transition: >-
              {{ 15 if states('light.living_room') == 'off' else 600 }}
      else:
        - action: hue.activate_scene
          target:
            entity_id: scene.living_room_daytime
          data:
            transition: >-
              {{ 15 if states('light.living_room') == 'off' else 600 }}
  mode: single
- alias: Living room lights off
  id: 21a8d2ce-746d-460a-9c65-b9ddf4f1b3b1
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_194
      for: "00:08:00"
      above: 1400
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: sensor.hue_scene_living_room
      state: Daytime
  actions:
    - action: light.turn_off
      target:
        entity_id: light.living_room
      data:
        transition: 15
  mode: single
- alias: Ensuite lights on
  id: d4dd4a4d-20f8-4f08-bcc9-a58941db2063
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_195
      for: "00:02:00"
      below: 250
    - trigger: state
      id: dawn
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: time
      id: wakeup
      at: input_datetime.wakeup
    - trigger: state
      id: obscured
      entity_id: sensor.sun_relative_to_house
      to: obscured
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "off"
        - condition: trigger
          id: wakeup
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.lightlevel_195
          below: 250
        - condition: and
          conditions:
            - condition: trigger
              id: obscured
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Daytime
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.eh_ls800b
          state: "on"
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: obscured
      then:
        - action: hue.activate_scene
          target:
            entity_id: scene.ensuite_ambiance
          data:
            transition: >-
              {{ 15 if states('light.light_ensuite') == 'off' else 600 }}
      else:
        - action: hue.activate_scene
          target:
            entity_id: scene.ensuite_daytime
          data:
            transition: >-
              {{ 15 if states('light.light_ensuite') == 'off' else 600 }}
  mode: single
- alias: Ensuite lights off
  id: cf719538-53fa-4a46-a566-b14ad3a5c870
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_195
      for: "00:08:00"
      above: 300
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: sensor.hue_scene_ensuite
      state: Daytime
  actions:
    - action: light.turn_off
      target:
        entity_id: light.ensuite
      data:
        transition: 15
  mode: single
- alias: Hallway (downstairs) lights on
  id: 1815106e-2684-4397-8fe8-73711ca6e7b5
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_48
      for: "00:01:00"
      below: 40
    - trigger: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: time
      id: wakeup
      at: input_datetime.wakeup
    - trigger: state
      id: in_back
      entity_id: sensor.sun_relative_to_house
      to: in_back
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.everyone_asleep
          state: "off"
        - condition: trigger
          id: wakeup
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.lightlevel_48
          below: 40
        - condition: trigger
          id: in_back
    # Never interfere with the manual override
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_hallway
          state: «Override»
  actions:
    - if:
        - condition: state
          entity_id: sensor.sun_relative_to_house
          state: in_back
      then:
        - action: hue.activate_scene
          target:
            entity_id: scene.hallway_downstairs_daytime_reduced
          data:
            transition: >-
              {{
                15 if states('light.hallway_downstairs') == 'off' else 600
              }}
      else:
        - action: hue.activate_scene
          target:
            entity_id: scene.hallway_downstairs_daytime
          data:
            transition: >-
              {{
                15 if states('light.hallway_downstairs') == 'off' else 600
              }}
  mode: single
- alias: Hallway (downstairs) lights off
  id: 9b941157-f359-4d69-a19c-eaa242f6faf3
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_48
      for: "00:10:00"
      above: 60
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: light.hallway_downstairs
      state: "on"
  actions:
    - action: light.turn_off
      target:
        entity_id: light.hallway_downstairs
      data:
        transition: 15
  mode: single
- alias: Hallway (upstairs) lights on
  id: 6fcf79b7-be12-4990-b2dd-21d8a85b4987
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_upstairs_hallway
      for: "00:01:00"
      below: 30
    - trigger: state
      entity_id: sensor.time_of_day
      from: dawn
      to: day
    - trigger: time
      id: wakeup
      at: input_datetime.wakeup
  conditions:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: input_boolean.everyone_asleep
              state: "off"
            # It is possible for everyone_asleep to be disabled, but still have
            # someone sleeping – to prevent waking them by switching on the
            # Hallway light, ensure that today's wakeup time has passed.
            - >-
              {{
                states('input_datetime.last_wakeup') |
                  as_datetime | as_local < now()
              }}
        - condition: trigger
          id: wakeup
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: numeric_state
      entity_id: sensor.lightlevel_upstairs_hallway
      below: 30
  actions:
    - action: hue.activate_scene
      target:
        entity_id: scene.hallway_upstairs_daytime
      data:
        transition: 15
  mode: single
- alias: Hallway (upstairs) lights off
  id: 14585406-3c8d-4c76-902a-af71e509e95d
  triggers:
    - trigger: numeric_state
      entity_id: sensor.lightlevel_upstairs_hallway
      for: "00:10:00"
      above: 50
  conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
    - condition: state
      entity_id: light.hallway_upstairs
      state: "on"
  actions:
    - action: light.turn_off
      target:
        entity_id: light.hallway_upstairs
      data:
        transition: 15
  mode: single
