# Front and Kitchen door have almost identical automations. They are not folded
# into a single automation as that would cause problems when both doors are
# opened at the same time. Parrallelising the automation (to cope with both
# doors opening at the same time) in turn causes problems with reverting the
# light back to its original state (as restarting the automation for the same
# door midway through causes it to always the detect the original state as
# "on" – and thus never turning the light off again).
- alias: 💡 | 🚪 Outside light to maximum brightness (Front door open)
  id: 78c89018-504b-4ff1-8aa1-fbebc14206e9
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_16
      from: "off"
      to: "on"
  condition:
    # Only act if the alarm is disarmed or there's someone asleep at home (i.e.
    # when it might be helpful for the light to turn on). Turning them on in
    # other situations could cause the camera night vision feed to (temporarily)
    # over-expose, reducing the effectiveness of the cameras...
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  action:
    - variables:
        light_state: >-
          {{ states('light.hue_filament_bulb_1_2') }}
        light_brightness: >-
          {{ state_attr('light.hue_filament_bulb_1_2', 'brightness')|int }}
    - service: light.turn_on
      data:
        brightness: 255
        entity_id: light.hue_filament_bulb_1_2
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.openclose_16
          to: "off"
    - delay: "00:00:30"
    - choose:
        - conditions:
            - condition: template
              value_template: >-
                {{ light_state == 'on' }}
          sequence:
            - service: light.turn_on
              data:
                brightness: >-
                  {{ light_brightness }}
              target:
                entity_id: light.hue_filament_bulb_1_2
        - conditions:
            - condition: template
              value_template: >-
                {{ light_state == 'off' }}
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.hue_filament_bulb_1_2
      default: []
  mode: single
  max_exceeded: silent
- alias: 💡 | 🚪 Outside light to maximum brightness (Kitchen door open)
  id: ffff8c6f-9dbd-4791-8c32-766e1570811e
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_12
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
  action:
    - variables:
        light_state: >-
          {{ states('light.hue_filament_bulb_1') }}
        light_brightness: >-
          {{ state_attr('light.hue_filament_bulb_1', 'brightness')|int }}
    - service: light.turn_on
      data:
        brightness: 255
        entity_id: light.hue_filament_bulb_1
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.openclose_12
          to: "off"
    - delay: "00:00:30"
    - choose:
        - conditions:
            - condition: template
              value_template: >-
                {{ light_state == 'on' }}
          sequence:
            - service: light.turn_on
              data:
                brightness: >-
                  {{ light_brightness }}
              target:
                entity_id: light.hue_filament_bulb_1
        - conditions:
            - condition: template
              value_template: >-
                {{ light_state == 'off' }}
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.hue_filament_bulb_1
      default: []
  mode: single
  max_exceeded: silent
- alias: 💡 | 🚪 Garden lights on (Kitchen door / Back gate open)
  id: cd0a0eac-d482-4add-ba9f-28e63fae0d26
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.openclose_12
        - binary_sensor.openclose_34
      from: "off"
      to: "on"
      # Slight delay to prevent "checking if the door is locked" (by attempting
      # to open it) from triggering the Garden lights...
      for: "00:00:03"
  condition:
    # Again, only under "normal" circumstances – the alarm automations also
    # control the Garden lights
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: light.garden
      state: "off"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Garden
        scene_name: Ambiance
    - wait_for_trigger:
        - platform: template
          value_template: >-
            {{ is_state(trigger.entity_id, 'off') }}
    - delay: "00:05:00"
    - service: light.turn_off
      entity_id: light.garden
  mode: restart
