- alias: 💡 | 🚪 Front / back door to maximum brightness (door open)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.openclose_12
    - binary_sensor.openclose_16
    from: 'off'
    to: 'on'
  condition:
  # Only act if the alarm is disarmed or there's someone asleep at home (i.e.
  # when it might be helpful for the lights to turn on). Turning them on in
  # other situations could cause the camera night vision feed to (temporarily)
  # over-expose, reducing the effectiveness of the cameras...
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - disarmed
      - armed_night
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
  action:
  - choose:
    # Lights already on
    - conditions:
      - condition: state
        entity_id: light.front_back_door
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          brightness: 255
          entity_id: >-
            {%- if trigger.entity_id == "binary_sensor.openclose_12" -%}
              light.hue_filament_bulb_1
            {%- else -%}
              light.hue_filament_bulb_1_2
            {%- endif -%}
      - wait_for_trigger:
        - platform: template
          value_template: >-
            {{ is_state(trigger.entity_id, 'off') }}
      - delay: '00:00:30'
      - service: hue.hue_activate_scene
        data:
          group_name: Front & back door
          scene_name: Evening
    # Lights off
    - conditions:
      - condition: state
        entity_id: light.front_back_door
        state: 'off'
      sequence:
      - service: light.turn_on
        data:
          brightness: 255
          entity_id: >-
            {%- if trigger.entity_id == "binary_sensor.openclose_12" -%}
              light.hue_filament_bulb_1
            {%- else -%}
              light.hue_filament_bulb_1_2
            {%- endif -%}
      - wait_for_trigger:
        - platform: template
          value_template: >-
            {{ is_state(trigger.entity_id, 'off') }}
      - delay: '00:00:30'
      - service: light.turn_off
        entity_id: light.front_back_door
    default: []
  mode: parallel
  max: 2
  max_exceeded: silent
- alias: 💡 | 🚪 Garden lights on (kitchen door / back gate open)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.openclose_12
    - binary_sensor.openclose_34
    from: 'off'
    to: 'on'
    # Slight delay to prevent "checking if the door is locked" (by attempting to
    # open it) from triggering the Garden lights...
    for: '00:00:03'
  condition:
  # Again, only under "normal" circumstances – the alarm automations also
  # control the Garden lights
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - disarmed
      - armed_night
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.time_of_day
      state: day
  - condition: state
    entity_id: light.garden
    state: 'off'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Garden
      scene_name: Ambiance
  - wait_for_trigger:
    - platform: template
      value_template: >-
        {{ is_state(trigger.entity_id, 'off') }}
  - delay: '00:05:00'
  - service: light.turn_off
    entity_id: light.garden
  mode: restart
