- alias: Garden lights on
  id: 8fa0a6d4-f80a-4312-8669-9f5525bbf3d5
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: dusk
      to: night
  conditions:
    - condition: state
      entity_id: light.garden
      state: "off"
  actions:
    - action: hue.activate_scene
      target:
        entity_id: scene.garden_ambiance
      data:
        transition: 30
  mode: single
- alias: Inside lights on
  id: 0ca01a00-8847-41f1-b852-70f4c4a49275
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions: []
  actions:
    - parallel:
        # Living room
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: light.living_room
                  state: "off"
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state: Daytime
          then:
            - action: hue.activate_scene
              target:
                entity_id: scene.living_room_active
              data:
                transition: >-
                  {{ 30 if states('light.living_room') == 'off' else 600 }}
        # Ensuite
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: light.ensuite
                  state: "off"
                - condition: state
                  entity_id: sensor.hue_scene_ensuite
                  state: Daytime
          then:
            - action: hue.activate_scene
              target:
                entity_id: scene.ensuite_ambiance
              data:
                transition: >-
                  {{ 30 if states('light.ensuite') == 'off' else 600 }}
        # Kitchen
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: light.kitchen
                  state: "off"
                - condition: state
                  entity_id: sensor.hue_scene_kitchen
                  state: Daytime
          then:
            - action: hue.activate_scene
              target:
                entity_id: scene.kitchen_ambiance
              data:
                transition: >-
                  {{ 30 if states('light.kitchen') == 'off' else 600 }}
        # Hallway
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: light.hallway
                  state: "off"
                # Daytime lighting on; no active override
                - condition: and
                  conditions:
                    - condition: or
                      conditions:
                        - condition: state
                          entity_id: sensor.hue_scene_hallway_downstairs
                          state:
                            - Daytime
                            - Daytime (reduced)
                            # Downstairs Hallway transitions to Evening as part
                            # of its daytime-lighting automation
                            - Evening
                        - condition: state
                          entity_id: sensor.hue_scene_hallway_upstairs
                          state: Daytime
                    - condition: not
                      conditions:
                        - condition: state
                          entity_id: sensor.hue_scene_hallway
                          state: «Override»
          then:
            - action: hue.activate_scene
              target:
                entity_id: scene.hallway_evening
              data:
                transition: >-
                  {{ 30 if states('light.hallway') == 'off' else 600 }}
  mode: single
# The distinction between "Inside lights" and "House lights" is somewhat
# arbitrary – it serves to keep the dusk and dawn lighting automations aligned.
# See "📄 lights/dawn.yaml" for more details...
- alias: House lights on
  id: 260c4540-8991-4541-93a2-2c5200733de8
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions: []
  actions:
    # Front and back (i.e. Kitchen) door
    - action: scene.turn_on
      target:
        entity_id: scene.front_back_door_evening
    # Guestroom
    - if:
        - condition: state
          entity_id: light.guestroom
          state: "off"
      then:
        - action: hue.activate_scene
          target:
            entity_id: scene.guestroom_relax
          data:
            transition: 30
  mode: single
- alias: Garden lights off
  id: 99711cfd-e1c7-47d8-83af-94876e126b6c
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: dusk
      to: night
    # If Home Assistant is (re)started while this automation is running, the
    # lights won't be switched off – account for that edge case too...
    - trigger: homeassistant
      id: ha_start
      event: start
  conditions: []
  actions:
    # Garden lights normally go off at 23:00, _but_ should be on for at least
    # 90 minutes. If they've been on for less than that, delay execution beyond
    # 23:00... Note the logic compensates for the 5-minute timeout on the
    # wait-for-trigger that follows.
    - delay: >-
        {% set delay = (today_at("22:55") - now()).seconds %}
        {#
          Timedelta's seconds-property doesn't go negative; wraps around at
          24-hours instead – this guard is required to prevent an impossibly
          long delay in case we trigger after 22:55...
        #}
        {% if today_at("22:55") <= now() %}
          {{ 0 }}
        {% elif trigger.id != 'ha_start' and delay < 5100 %}
          {{ 5100 }}
        {% else %}
          {{ delay }}
        {% endif %}
    # The Kitchen/Shed door and Back gate have separate automations that trigger
    # the lights when they're opened. To prevent interfering with those, wait
    # for their triggers at the end of our run and add an additional delay if
    # they occur.
    - wait_for_trigger:
        - trigger: state
          entity_id:
            - binary_sensor.openclose_12 # Kitchen door
            - binary_sensor.openclose_34 # Back gate
            - binary_sensor.openclose_189 # Shed
          from: "off"
          to: "on"
      timeout: "00:05:00"
      continue_on_timeout: true
    - if: >-
        {{ wait.trigger is not none }}
      then:
        # Unconditional 10-minute delay – should be enough to not override the
        # other automations' behaviour
        delay: "00:10:00"
    # Only continue if the Garden lights are still on their original scene
    - condition: state
      entity_id: sensor.hue_scene_garden
      state: Ambiance
    - action: light.turn_off
      target:
        entity_id:
          - light.garden
          - light.hue_filament_bulb_1 # Back door light
      data:
        transition: 30
  # Override in case Home Assistant got restarted during the day (allowing the
  # proper trigger to take over)
  mode: restart
- alias: Front door light off
  id: dc5c6595-78d3-43c9-94ab-24ddd2a4073d
  triggers:
    - trigger: time
      at: "23:00:00"
  conditions:
    - condition: state
      entity_id: light.hue_filament_bulb_1_2
      state: "on"
  actions:
    - action: light.turn_off
      entity_id: light.hue_filament_bulb_1_2
