# N.B. This automation's name is used later in the file!
- alias: 💡 | ⏰ Garden lights on (daily at civil dusk)
  id: 8fa0a6d4-f80a-4312-8669-9f5525bbf3d5
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: dusk
      to: night
  condition:
    - condition: state
      entity_id: light.garden
      state: "off"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.garden_ambiance
  mode: single
- alias: 💡 | ⏰ Inside lights on (daily at sunset)
  id: 0ca01a00-8847-41f1-b852-70f4c4a49275
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition: []
  action:
    # Living room
    - if:
        - condition: or
          conditions:
            - condition: state
              entity_id: light.living_room
              state: "off"
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state: Daytime
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.living_room_ambiance
    # Ensuite
    - if:
        - condition: state
          entity_id: light.ensuite
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.ensuite_orchid
    # Kitchen
    - if:
        - condition: or
          conditions:
            - condition: state
              entity_id: light.kitchen
              state: "off"
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Daytime
      then:
        # If the Kitchen counter & cupboard lights are on, aim to keep them on
        # while transitioning the Kitchen to "Ambiance"
        - if:
            - condition: state
              entity_id: sensor.hue_scene_kitchen_counter_cupboards
              state: Activity
          then:
            - service: scene.turn_on
              target:
                entity_id: scene.kitchen_ambiance
            # Wait for the Kitchen to register its change before
            # changing counter & cupboards; this is required for the
            # scene heuristic to work properly. Not doing so will lead
            # the Kitchen to revert back to Daytime (instead of
            # Ambiance) after activity ends.
            - wait_for_trigger:
                - platform: state
                  entity_id: sensor.hue_scene_kitchen
                  to: Ambiance
              timeout: "00:00:10"
              continue_on_timeout: false
            - service: scene.turn_on
              target:
                entity_id: scene.kitchen_counter_cupboards_activity
          # Otherwise, act on the Kitchen alone
          else:
            - service: scene.turn_on
              target:
                entity_id: scene.kitchen_ambiance
    # Hallway – turn on lights regardless of their state. The daytime light
    # automation most likely already switched them on; the below ensures they
    # don't get stuck at their – too high – daytime brightness level...
    - service: scene.turn_on
      target:
        entity_id: scene.hallway_evening
  mode: single
# The distinction between "Inside lights" and "House lights" is somewhat
# arbitrary – it serves to keep the dusk and dawn lighting automations aligned.
# See "📄 lights/dawn.yaml" for more details...
- alias: 💡 | ⏰ House lights on (daily at sunset)
  id: 260c4540-8991-4541-93a2-2c5200733de8
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition: []
  action:
    # Front and back (i.e. Kitchen) door
    - service: scene.turn_on
      target:
        entity_id: scene.front_back_door_evening
    # Guestroom
    - if:
        - condition: state
          entity_id: light.guestroom
          state: "off"
      then:
        - service: scene.turn_on
          target:
            entity_id: scene.guestroom_evening
  mode: single
- alias: 💡 | ⏰ Garden lights off (daily after 23:00)
  id: 99711cfd-e1c7-47d8-83af-94876e126b6c
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.garden
          state: "on"
        - condition: state
          entity_id: light.hue_filament_bulb_1 # Back door
          state: "on"
  action:
    # Garden lights should be on for at least 90 minutes – delay execution to
    # achieve this based on when their "switch on"-automation ran...
    - delay: >-
        {% set ref = state_attr(
            'automation.outside_lights_on_daily_at_civil_dusk', 'last_triggered'
          ) | as_local
        %}
        {% set delta=1380-(ref.hour * 60 + ref.minute) %}
        {% if delta >= 0 and delta < 90 %}
          {{ (90 - delta) * 60 }}
        {% else %}
          0
        {% endif %}
    - service: light.turn_off
      entity_id:
        - light.garden
        - light.hue_filament_bulb_1 # Back door
  mode: single
- alias: 💡 | ⏰ Front door light off (daily at 22:30)
  id: dc5c6595-78d3-43c9-94ab-24ddd2a4073d
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    - condition: state
      entity_id: light.hue_filament_bulb_1_2
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.hue_filament_bulb_1_2
