- alias: 🕯️ | 🤖 Fireplace toggle (input boolean)
  id: e885702e-c8fb-4720-84f7-07aa9f13855b
  trigger:
    - entity_id: input_boolean.fireplace
      platform: state
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.fireplace
              state: "on"
          sequence:
            - service: rest_command.fireplace_start
        - conditions:
            - condition: state
              entity_id: input_boolean.fireplace
              state: "off"
          sequence:
            - service: rest_command.fireplace_stop
  mode: single
- alias: 🕯️ | 🤖/⏰ Fireplace off (Living room lights off / daily at 02:00)
  id: 84653754-190c-4571-85e8-e5eca37e81a9
  trigger:
    - platform: state
      entity_id: light.living_room
      from: "on"
      to: "off"
    - platform: time
      at: "02:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.fireplace
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fireplace
    - delay: 30
    - service: light.turn_off
      entity_id:
        - light.fireplace_1_living_room
        - light.fireplace_2_living_room
  mode: single
- alias: 🕯️ | 🤖 Fireplace on (Living room lights on after 20:00)
  id: 0997f7bb-f73d-4bb4-a0bc-c31d6c8d8875
  trigger:
    - entity_id: sensor.hue_scene_living_room
      platform: state
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: time
      after: "20:00:00"
      before: "02:00:00"
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.fireplace
      state: "off"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - Ambiance
                - Movie
                - Movie (ambiance)
          sequence:
            - service: rest_command.fireplace_start
        # No-op in case of <Off> or <Unknown> state
        - conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - <Off>
                - <Unknown>
          sequence: []
      default:
        - service: rest_command.fireplace_stop
        # The fireplace lights will remain in whatever state they were in when
        # the animation stopped; re-applying the current scene will set them
        # to their proper setting
        - delay: 30
        - service: hue.hue_activate_scene
          data:
            group_name: Living room
            scene_name: >-
              {{ sensor.hue_scene_living_room }}
  mode: single
