- alias: ✨ | 🕹️ Fireplace toggle (input boolean)
  id: e885702e-c8fb-4720-84f7-07aa9f13855b
  trigger:
    - entity_id: input_boolean.fireplace
      platform: state
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.fireplace
              state: "on"
          sequence:
            - service: rest_command.fireplace_start
        - conditions:
            - condition: state
              entity_id: input_boolean.fireplace
              state: "off"
          sequence:
            - service: rest_command.fireplace_stop
  mode: single
- alias: ✨ | 💡/⏰ Fireplace off (Living room lights off / daily at 02:00)
  id: 84653754-190c-4571-85e8-e5eca37e81a9
  trigger:
    - platform: state
      entity_id: light.living_room
      from: "on"
      to: "off"
    - platform: time
      at: "02:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.fireplace
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fireplace
    - delay: 10
    - service: light.turn_off
      entity_id:
        - light.fireplace_1_living_room
        - light.fireplace_2_living_room
  mode: single
- alias: ✨ | 💡 Fireplace on (Living room Hue scene change after 20:00)
  id: 0997f7bb-f73d-4bb4-a0bc-c31d6c8d8875
  trigger:
    - platform: state
      entity_id: sensor.hue_scene_living_room
      to:
        - Ambiance
        - Movie
        - Movie (ambiance)
      for: "00:02:00"
    # Also trigger at 20:00 and at nightfall
    - platform: time
      at: "20:00:00"
    - platform: state
      entity_id: sensor.time_of_day
      from: dusk
      to: night
  condition:
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: time
      after: "20:00:00"
      before: "02:00:00"
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.fireplace
      state: "off"
    # In case of time-based triggers, ensure Living room has the correct Hue
    # scene activated (superfluous for the scene-based trigger)
    - condition: state
      entity_id: sensor.hue_scene_living_room
      state:
        - Ambiance
        - Movie
        - Movie (ambiance)
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.fireplace
  mode: single
- alias: ✨ | 💡 Fireplace off (Living room Hue scene change after 20:00)
  id: af1142fe-e8fe-4f6f-83c7-0d60f650e899
  trigger:
    - platform: state
      entity_id: sensor.hue_scene_living_room
      to:
        # The <Off> state is covered by a separate automation
        - Active
        - Daytime
  condition:
    - condition: state
      entity_id: sensor.time_of_day
      state: night
    - condition: time
      after: "20:00:00"
      before: "02:00:00"
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.fireplace
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fireplace
    # The fireplace lights will remain in whatever state they were in
    # when the animation stopped; re-applying the current scene restores
    # them to their proper setting
    - delay: 10
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: >-
          {{ sensor.hue_scene_living_room }}
  mode: single
