# The Gledopto light-strip controllers in the Kitchen have the annoying habit of
# reporting they're switched "off" while they're actually still "on". After a
# while they realise this discrepancy and start to report "on" again. This has
# unintended effects on other automations.
# The below is related to the issue addressed in – 📄 scripts/hue.yaml - but
# specifically for the "off" situation. Instead of proactively toggling the
# light off multiple times, reactively correct the inconsistent situation.
- alias: 💡 | 🩹 Enforce "off"-state for Gledopto light-strip controllers
  id: 77eb93cc-0e5f-4ad9-9153-e2f7858b1688
  trigger:
    - platform: state
      entity_id:
        - light.extended_color_light_1_3
        - light.extended_color_light_1_4
      to: "on"
      for: 10
  condition:
    # Whenever these two lights-strips are on, the lights in the cupboards
    # should also be on – if not, toggle the light-strips back off...
    - condition: state
      # Checking one of the four cupboard lights is sufficient
      entity_id: light.hue_color_spot_2_2
      state: "off"
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.extended_color_light_1_3
          - light.extended_color_light_1_4
  mode: restart
