# The Hallway lights are often manually adjusted – these changes don't need to
# persist after activity in the Hallway ends
- alias: Restore hallway lights after inactivity
  id: 4e1d15da-52cb-47ea-90e7-1396257116eb
  triggers:
    - trigger: state
      entity_id: sensor.hue_scene_hallway
      to: «Override»
  conditions: []
  actions:
    - wait_for_trigger:
        - trigger: state
          id: motion_stop
          entity_id:
            - binary_sensor.presence_121 # Stairs
            - binary_sensor.presence_123 # Downstairs hallway
            - binary_sensor.presence_125 # Downstairs hallway
            - binary_sensor.presence_127 # Upstairs hallway
          from: "on"
          to: "off"
          for: "00:10:00"
        - trigger: state
          entity_id: sensor.hue_scene_hallway
          not_to: «Override»
      timeout: "02:00:00"
      continue_on_timeout: false
    # Only restore when there's no more activity
    - condition: template
      value_template: >-
        {{ wait.trigger is not none and wait.trigger.id == 'motion_stop' }}
    # Daytime
    - if:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
      then:
        # Downstairs
        - if:
            - condition: numeric_state
              entity_id: sensor.lightlevel_48
              below: 60
          then:
            - action: script.turn_on
              target:
                entity_id: script.hallway_downstairs_daytime_lights
          else:
            - action: light.turn_off
              target:
                entity_id: light.hallway_downstairs
        # Upstairs
        - if:
            - condition: numeric_state
              entity_id: sensor.lightlevel_upstairs_hallway
              below: 50
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.hallway_upstairs_daytime
          else:
            - action: light.turn_off
              target:
                entity_id: light.upstairs_hallway
      # Evening
      else:
        - action: scene.turn_on
          target:
            entity_id: scene.hallway_evening
  mode: single
- alias: Dim hallway lights
  id: 2a98868c-c030-4159-803e-3cc6193a9872
  triggers:
    - trigger: state
      entity_id: binary_sensor.vibration_43 # Doorbell
      from: "off"
      to: "on"
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
    - condition: state
      entity_id: light.hallway_downstairs
      state: "on"
  actions:
    - wait_for_trigger:
        - trigger: state
          entity_id:
            - binary_sensor.presence_121 # Stairs
            - binary_sensor.presence_123 # Downstairs hallway
            - binary_sensor.presence_125 # Downstairs hallway
          from: "off"
          to: "on"
      timeout: "00:02:00"
      continue_on_timeout: false
    - action: light.turn_on
      data:
        brightness: 8
        entity_id: light.hallway_downstairs
    # Restore lights on opening the front door, or after five-minutes if the
    # door isn't opened
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.openclose_16
          from: "off"
          to: "on"
          for: "00:00:05"
        # Abort if the lights get otherwise changed
        - trigger: state
          id: abort
          entity_id: light.hallway_downstairs
          attribute: brightness
          from: 8
      timeout: "00:05:00"
      continue_on_timeout: true
    - condition: >-
        {{ wait.trigger is none or wait.trigger.id != 'abort' }}
    # Restore the previous (ie, current) scene
    - action: script.hue_activate_scene
      data:
        scene_entity: sensor.hue_scene_hallway_downstairs
