# Ensuite sometimes doesn't turn on with the rest of the Living room – attempt
# to detect and correct for this...
- alias: 💡 | 🩹 Enforce Ensuite "on"-state to follow Living room
  id: 48db5b8d-2b8d-4651-a29e-c6614a144b6d
  trigger:
    - platform: state
      entity_id: sensor.hue_scene_living_room
      to: ~
  condition:
    # Every Living room Hue scene has the Ensuite switched on
    - condition: state
      entity_id: light.hue_white_light_1
      state: "off"
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.hue_scene_living_room
          state:
            - <Off>
            - <Unknown>
  action:
    # As the Ensuite is not included in the heuristic computation, we only get
    # one shot at this. Explicitly switch on the Ensuite, wait a bit and then
    # re-apply the Hue scene – only re-applying the Hue scene might not be
    # sufficient...
    - service: light.turn_on
      target:
        entity_id: light.hue_white_light_1
    - delay: "00:00:10"
    - service: script.hue_activate_scene
      data:
        scene_entity: sensor.hue_scene_living_room
  mode: restart
# The Gledopto controllers in the Kitchen are a bit stubborn; they don't always
# respond to the first scene change request, nor do they always properly switch
# off when asked to do so... See "📄 docs/HUE.md" for more details.
# The below aims to keep the "off" state of the Gledopto controllers in line
# with the Kitchen as a whole.
- alias: 💡 | 🩹 Enforce "off"-state for Gledopto controllers
  id: 77eb93cc-0e5f-4ad9-9153-e2f7858b1688
  trigger:
    - platform: state
      entity_id:
        - light.extended_color_light_1_3
        - light.extended_color_light_1_4
      to: "on"
      for: "00:00:10"
  condition:
    # If the Gledopto controllers are on, the rest of the Kitchen should also be
    # on. If that's not the case, switch the Gledopto controllers off. The below
    # is possible because Hue Group – Kitchen is explicitly set up to _exclude_
    # the Gledopto controllers.
    - condition: state
      entity_id: light.hue_group_kitchen
      state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.extended_color_light_1_3
          - light.extended_color_light_1_4
  mode: restart
# Change scene in Kitchen twice to ensure the Gledopto controllers follow
- alias: 💡 | 🩹 Enforce Kitchen scene change for Gledopto controllers
  id: 66dc6374-f19a-437c-966b-0679400fc2b5
  trigger:
    # By prioritising (and blocking for a while) on the Kitchen counter &
    # cupboards trigger, we ensure that change gets priority over the Kitchen
    # as a whole — as the Gledopto controllers are part of both sets of Hue
    # scenes, this is the most straightforward way to reapply their scene (no
    # need to figure out what to do, simply punch in the triggered scene change
    # again).
    - platform: state
      entity_id:
        - sensor.hue_scene_kitchen_counter_cupboards
      not_to:
        - <Off>
        - <Unknown>
    - platform: state
      entity_id:
        - sensor.hue_scene_kitchen
      not_to:
        - <Off>
        - <Unknown>
      for: "00:00:01"
  condition: []
  action:
    - condition: >-
        {{ trigger.entity_id is defined }}
    - service: script.hue_activate_scene
      data:
        scene_entity: >-
          {{ trigger.entity_id }}
    - delay: 20
  mode: single
  max_exceeded: silent
# Occasionally, the Innr colour bulbs in the Garden refuse a scene change, so
# whenever we change the Garden, change it twice to ensure they properly follow
- alias: 💡 | 🩹 Enforce Garden scene change for Innr bulbs
  id: 0c7cd39c-6355-45ee-9e53-ab2d3c940f08
  trigger:
    - platform: state
      entity_id: sensor.hue_scene_garden
      not_to:
        - <Off>
        - <Unknown>
      # Best result is achieved if the repeat command is slightly delayed
      for: "00:00:03"
  condition: []
  action:
    - service: script.hue_activate_scene
      data:
        scene_entity: sensor.hue_scene_garden
  mode: restart
- alias: 💡 | 🩹 Log Hue scene heuristic failures
  id: c47f1d4b-d0dc-49e9-ae8d-0af0a2c3a092
  trigger:
    - platform: state
      entity_id:
        - sensor.hue_scene_living_room
        - sensor.hue_scene_kitchen
        - sensor.hue_scene_kitchen_counter_cupboards
        - sensor.hue_scene_garden
      to:
        - <Unknown>
  condition: []
  action:
    - variables:
        room: >-
          {{
            trigger.entity_id | replace('sensor.hue_scene_', '')
          }}
        num_lights: >-
          {{
            expand(
              state_attr('light.hue_group_' ~ room, 'entity_id')
            ) | selectattr('state', '==', 'on') | list | length
          }}
        brightness: >-
          {{ state_attr('light.hue_group_' ~ room, 'brightness') | int(-1) }}
        xy_color: >-
          {%
            if state_attr('light.hue_group_' ~ room, 'xy_color') == none
          %}
            {{ [-1.0, -1.0] }}
          {% else %}
            {%
              set xy_color = state_attr('light.hue_group_' ~ room, 'xy_color')
            %}
            {{ [xy_color[0] | round(2), xy_color[1] | round (2)] }}
          {% endif %}
    # Attempt to distinguish between a regular and transient failure
    - wait_for_trigger:
        - platform: state
          entity_id:
            - sensor.hue_scene_living_room
            - sensor.hue_scene_kitchen
            - sensor.hue_scene_kitchen_counter_cupboards
            - sensor.hue_scene_garden
          from:
            - <Unknown>
      timeout: "00:00:20"
      continue_on_timeout: true
    - variables:
        transient_end_state: >-
          {%- if wait.trigger is not none -%}
            {{ wait.trigger.to_state.state }}
          {%- endif -%}
        transient_duration: >-
          {%- if wait.trigger is not none -%}
            {{ (20 - wait.remaining) | round(0) }}
          {%- endif -%}
    - service: notify.log_hue_scene_heuristic
      data:
        message: >-
          Hue scene heuristic failure: {{ trigger.entity_id }} transitioned {%
          if transient_end_state != '' -%}
            through <Unknown> from {{ trigger.from_state.state }} to {{
            transient_end_state }} for {{ transient_duration }} seconds {%
          else -%}
            from {{ trigger.from_state.state }} to {{
            trigger.to_state.state }} {%
          endif -%}
          { num_lights: {{ num_lights}}, brightness: {{ brightness }}, xy_color:
          {{ xy_color }} }
  mode: parallel
  max: 3
