- alias: 💡 | 👋 Kitchen counter & cupboards toggle (motion detected)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_53
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.hue_activate_scene_kitchen_counter_cupboards
    data:
      scene_name: Activity
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.presence_53
      from: 'on'
      to: 'off'
      for: 00:02:00
    # If the scene for "Kitchen counter & cupboards" is still "Activity",
    # no changes were made to the lighting. We can safely restore the previous
    # scene for the "Kitchen" as a whole...
  - condition: state
    entity_id: input_select.hue_scene_kitchen_counter_cupboards
    state:  Activity
  - choose:
    - conditions:
        - condition: template
          value_template: >-
            {{  not is_state('input_select.hue_scene_kitchen', '<Off>') and
                not is_state('input_select.hue_scene_kitchen', '<Unknown>') }}
      sequence:
      - service: script.hue_activate_scene_kitchen
        data:
          # This works because changing "Kitchen counter & cupboards"
          # doesn't actually change the "Kitchen" scene (it retains its
          # state even though some of its lights changed). We can simply
          # re-apply the already active scene.
          scene_name: >-
            {{ states('input_select.hue_scene_kitchen') }}
    - conditions:
        - condition: template
          value_template: >-
            {{ is_state('input_select.hue_scene_kitchen', '<Off>') }}
      sequence:
      - service: light.turn_off
        data:
          entity_id: light.kitchen
  mode: restart
  max_exceeded: silent
- alias: 💡 | 👋 Toilet light toggle (motion detected)
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_60
    from: "off"
    to: "on"
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
      kelvin: 4500
    entity_id: light.toilet
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.presence_60
      from: "on"
      to: "off"
  - delay: 330
  - service: light.turn_off
    data:
      entity_id: light.toilet
      transition: 30
  mode: restart
  max_exceeded: silent
- alias: 💡 | 👋 Basement light toggle (motion detected)
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.presence_50
      light_target:
        entity_id: light.basement
      no_motion_wait: 60
