- alias: 💡 | 👋 Toilet light toggle (motion detected)
  id: e884ea40-fdf9-4069-ad27-4e09d8a45e2e
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_60
      from: "off"
      to: "on"
  condition:
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - service: light.turn_on
      data:
        brightness: 255
        kelvin: 4500
      target:
        entity_id: light.toilet
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.presence_60
          from: "on"
          to: "off"
    - delay: 270
    - service: light.turn_on
      data:
        brightness_step_pct: -30
      target:
        entity_id: light.toilet
    - delay: 30
    - service: light.turn_off
      target:
        entity_id: light.toilet
  mode: restart
- alias: 💡 | 👋 Basement light toggle (motion detected)
  id: 7a1ebf52-c69e-4bf5-8670-0b32bba52600
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_50
      from: "off"
      to: "on"
  condition:
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - service: light.turn_on
      entity_id: light.basement
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.presence_50
          from: "on"
          to: "off"
    - delay: 60
    - service: light.turn_off
      entity_id: light.basement
  mode: restart
- alias: 💡 | 👋 Wardrobe light toggle (motion detected)
  id: f30e4af7-6b31-4062-8f12-25fde6ae3577
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_63
      from: "off"
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.lightlevel_65
      below: 50
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - choose:
        # Evenings
        - conditions:
            - condition: state
              entity_id: sensor.time_of_day
              state:
                - dusk
                - night
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.wardrobe_bright
        # Nighttime
        - conditions:
            - condition: state
              entity_id: input_boolean.everyone_asleep
              state: "on"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.wardrobe_nighttime
      default:
        - service: scene.turn_on
          target:
            entity_id: scene.wardrobe_concentrate
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.presence_63
          from: "on"
          to: "off"
    - delay: 120
    - service: light.turn_off
      entity_id: light.wardrobe
  mode: restart
- alias: >-
    💡 | 👋 Upstairs hallway light toggle (motion detected; everyone asleep)
  id: 456be834-0809-442b-a022-2827923c3358
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_127
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - service: light.turn_on
      data:
        brightness: 40
      entity_id: light.upstairs_hallway
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.presence_127
          from: "on"
          to: "off"
    - delay: 60
    - service: light.turn_off
      entity_id: light.upstairs_hallway
  mode: restart
- alias: >-
    💡 | 👋 Downstairs hallway light toggle (motion detected; everyone asleep)
  id: 6d3da877-2a4f-453a-a4a2-cda751548fe0
  trigger:
    # Trigger only on the sensor in the staircase (i.e. someone walks down from
    # the bedroom at night)
    - platform: state
      entity_id: binary_sensor.presence_121
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - service: light.turn_on
      data:
        brightness: 40
      entity_id:
        - light.hue_filament_bulb_1_4
        - light.hue_filament_bulb_1_5
    # Wait for _all_ motion sensors in the downstairs hallway to clear
    - wait_template: >-
        {{
          states('binary_sensor.presence_121') == 'off' and
          states('binary_sensor.presence_123') == 'off' and
          states('binary_sensor.presence_125') == 'off'
        }}
    - delay: 60
    - service: light.turn_off
      entity_id:
        - light.hue_filament_bulb_1_4
        - light.hue_filament_bulb_1_5
  mode: restart
- alias: 💡 | 👋 Attic hallway light toggle (motion detected)
  id: 6eb9fb1b-c177-4e11-986c-d6cfec41454a
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.presence_91
        - binary_sensor.presence_92
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: timer.attic_hallway_motion_pause
      state: idle
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  action:
    - choose:
        # Upstairs
        - conditions:
            - condition: template
              value_template: >-
                {{ trigger.entity_id == 'binary_sensor.presence_91' }}
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.attic_hallway_up
        # Downstairs
        - conditions:
            - condition: template
              value_template: >-
                {{ trigger.entity_id == 'binary_sensor.presence_92' }}
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.attic_hallway_down
      default:
        - service: light.turn_on
          target:
            entity_id: light.attic_hallway
    # Wait for _all_ motion sensors to clear
    - wait_template: >-
        {{
          states('binary_sensor.presence_91') == 'off' and
          states('binary_sensor.presence_92') == 'off'
        }}
    # If the washing machine door was recently (ie, within the last 10-minutes)
    # opened, wait a bit longer to ensure the lights aren't switched off when
    # someone is (un)loading the washing machine...
    - if:
        - >-
          {{
            states.binary_sensor.openclose_158 is defined and
            (states.binary_sensor.openclose_158.last_changed | as_local) +
              timedelta(seconds = 600) >= now()
          }}
      then:
        # Delay for _up to_ 10-minutes (discounting the time that passed since
        # the door was opened; ensuring we never provide in a negative delay)
        - delay: >-
            {{
              [0, 600 - (
                now() | as_timestamp -
                states.binary_sensor.openclose_158.last_changed | as_timestamp
              ) | int ] | max
            }}
      else:
        - delay: 60
    - condition: state
      entity_id: timer.attic_hallway_motion_pause
      state: idle
    - service: light.turn_off
      target:
        entity_id: light.attic_hallway
  mode: restart
