- alias: Trigger "Lights out"-script
  id: 9b24fc0b-fc61-432c-b881-aa2b644a2efe
  triggers:
    - trigger: time
      at: "23:00:00"
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
  actions:
    - delay: >-
        {{ range(7200) | random }}
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
    - action: script.turn_on
      target:
        entity_id: script.lights_out
      data:
        variables:
          # Randomly toggle between activation from the Kitchen and activation
          # from the Bedroom
          activatedFrom: >-
            {% if (range(100) | random) >= 80 %}
              kitchen
            {% else %}
              bedroom
            {% endif %}
  mode: single
# The "Lights out"-script has a runtime of up to 15-minutes; if someone comes
# home while the script is running, the inside lights will switch off after a
# short while for no apparent reason... To prevent that, stop the script when
# someone comes home. No need to switch on any lights, other automations (in
# "📄 alarm/welcome.yaml" specifically) handle that.
- alias: Stop "Lights out"-script
  id: 9c2f2cea-8a22-40aa-ba35-575816f03acd
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  conditions:
    - condition: state
      entity_id: script.lights_out
      state: "on"
  actions:
    - action: script.turn_off
      target:
        entity_id: script.lights_out
  mode: single
# Combined into a single automation to prevent the lights from getting switched
# *on* at dusk if dusk is _after_ the randomised switch off moment (somewhere
# between 19:00 and 20:00)
- alias: Attic lights on and off
  id: 10746e4d-a051-42c0-afb0-79b375ac17d2
  triggers:
    - trigger: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  conditions:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
    # Ensure the range for the (final) random duration is at least half an hour
    # (to reduce the likelihood of the lights only being switched on
    # momentarily)
    - condition: time
      before: "19:30:00"
  actions:
    # ± 85% Chance of switching the lights on
    - condition: template
      value_template: >-
        {{ (range(0, 99) | random) > 15 }}
    - action: scene.turn_on
      target:
        entity_id: scene.attic_away
    # Wait until it's 19:00
    - if:
        - condition: time
          before: "19:00:00"
      then:
        - wait_for_trigger:
            - trigger: time
              at: "19:00:00"
          # Should never timeout; if it does, best to continue...
          timeout: "04:00:00"
          continue_on_timeout: true
    # Then delay for a random interval between "now" and 20:00
    - delay: >-
        {{ range(0, (today_at("20:00") - now()).seconds) | random }}
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - armed_away
        - armed_vacation
    - action: light.turn_off
      target:
        entity_id: light.attic
  mode: single
# Leaving the Attic lights on when someone's home would lead the occupancy
# detection in the Attic to assume there's someone in the Attic and
# unintentionally switch on the heating/airco...
- alias: Attic lights off
  id: 561c1b1f-4604-4f18-8635-d716dc677387
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  conditions:
    - condition: state
      entity_id: light.attic
      state: "on"
  actions:
    - action: light.turn_off
      target:
        entity_id: light.attic
  mode: single
