- alias: >-
    💡 | ✈️ Inside lights off when everyone away (daily between 23:00 - 01:00)
  id: 9b24fc0b-fc61-432c-b881-aa2b644a2efe
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
    - delay: >-
        {{ range(7200) | random }}
    - condition: state
      entity_id: group.family
      state: not_home
    - service: script.turn_on
      target:
        entity_id: script.lights_out
      data:
        variables:
          # Randomly toggle between activation from the Kitchen and activation
          # from the Bedroom
          activatedFrom: >-
            {% if (range(100) | random) >= 50 %}
              kitchen
            {% else %}
              bedroom
            {% endif %}
  mode: single
# The "Lights out"-script has a runtime of up to 15-minutes; if someone comes
# home while the script is running, the inside lights will switch off after a
# short while for no apparent reason... To prevent that, stop the script when
# someone comes home. No need to switch on any lights, other automations (in
# "📄 alarm/welcome.yaml" specifically) handle that.
- alias: 💡 | ✈️ Stop "Lights out"-script when someone home
  id: 9c2f2cea-8a22-40aa-ba35-575816f03acd
  trigger:
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: script.lights_out
      state: "on"
  action:
    - service: script.turn_off
      target:
        entity_id: script.lights_out
  mode: single
# Combined into a single automation to prevent the lights from getting switched
# *on* at dusk if dusk is _after_ the randomised switch off moment (somewhere
# between 19:00 and 20:00)
- alias: >-
    💡 | ✈️ Attic lights on and off when everyone away (most weekdays)
  id: 10746e4d-a051-42c0-afb0-79b375ac17d2
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition:
    - condition: time
      weekday: [mon, tue, wed, thu, fri] # yamllint disable-line rule:brackets
    - condition: state
      entity_id: group.family
      state: not_home
    # It never makes sense to run after 20:00
    - condition: time
      before: "20:00:00"
  action:
    # ± 85% Chance of switching the lights on
    - condition: template
      value_template: >-
        {{ (range(0, 99) | random) > 15 }}
    - service: scene.turn_on
      target:
        entity_id: scene.attic_away
    # Wait until it's 19:00
    - if:
        - condition: time
          before: "19:00:00"
      then:
        - wait_for_trigger:
            - platform: time
              at: "19:00:00"
          # Should never timeout; if it does, best to continue...
          timeout: "04:00:00"
          continue_on_timeout: true
    # Then delay for a random interval between "now" and 20:00 — can probably
    # fold the preceding "if" into the below template, but this way (with as
    # little time arithmetic as possible) it's much easier to understand.
    - delay: >-
        {{ range(0, (today_at("20:00") - now()).seconds) | random }}
    - condition: state
      entity_id: group.family
      state: not_home
    - service: light.turn_off
      target:
        entity_id: light.attic
  mode: single
# Leaving the Attic lights on when someone's home would lead the occupancy
# detection in the Attic to assume there's someone in the Attic and
# unintentionally switch on the heating/airco...
- alias: 💡 | ✈️ Attic lights off when someone home
  id: 561c1b1f-4604-4f18-8635-d716dc677387
  trigger:
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: light.attic
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.attic
  mode: single
