- alias: Dim lights
  id: c136b7ec-1a71-49d3-b000-efddfcd4b433
  triggers:
    - trigger: state
      entity_id: sensor.plex_shield_android_tv
      to: playing
  conditions: []
  # Acts when the lights are on, and _not_ in Daytime-mode. During the day,
  # switching on the projector is most likely more functional than for
  # entertainment purposes – also, the new Epson is more than bright enough to
  # overpower the Daytime-lighting...
  actions:
    - parallel:
        # Living room
        - if:
            - condition: state
              entity_id: light.living_room
              state: "on"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.hue_scene_living_room
                  state: Daytime
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.living_room_movie
        # Ensuite
        - if:
            - condition: state
              entity_id: light.ensuite
              state: "on"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.hue_scene_ensuite
                  state: Daytime
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.ensuite_movie
        # Kitchen
        - if:
            - condition: state
              entity_id: light.kitchen
              state: "on"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.hue_scene_kitchen
                  state: Daytime
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.kitchen_movie
        # Hallway – downstairs
        - if:
            - condition: state
              entity_id: light.hallway_downstairs
              state: "on"
            - condition: not
              conditions:
                - condition: state
                  entity_id: sensor.hue_scene_hallway_downstairs
                  state: Daytime
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.hallway_downstairs_movie
  mode: single
- alias: Dim lights (initial)
  id: f168660c-0dc6-4c56-8221-fecb7cad1ece
  triggers:
    - trigger: state
      entity_id: media_player.marantz_cinema_70s
      attribute: source
      to: SHIELD
      for: "00:00:02"
  conditions: []
  actions:
    - if:
        - condition: state
          entity_id: light.living_room
          state: "on"
        - condition: not
          conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - Daytime
                - Movie
      then:
        - action: scene.turn_on
          target:
            entity_id: scene.living_room_movie_ambiance
  mode: single
- alias: Restore lights
  id: 586f5ad1-0c79-4213-820d-9e6ed587d540
  triggers:
    - trigger: state
      id: paused
      entity_id: sensor.plex_shield_android_tv
      from: playing
      to:
        - idle
        - paused
    - trigger: state
      entity_id: media_player.marantz_cinema_70s
      attribute: source
      from: SHIELD
  conditions:
    # When triggered by the AVR source, the AVR should be off (we don't want to
    # trigger when _switching_ sources)
    - condition: or
      conditions:
        - condition: trigger
          id: paused
        - condition: state
          entity_id: media_player.marantz_cinema_70s
          state: "off"
  actions:
    - parallel:
        # Living room
        - if:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - Movie
                - Movie (ambiance)
          then:
            - if:
                - condition: trigger
                  id: paused
              then:
                - action: scene.turn_on
                  target:
                    entity_id: scene.living_room_movie_ambiance
              else:
                - action: scene.turn_on
                  target:
                    entity_id: scene.living_room_ambiance
        # Ensuite
        - if:
            - condition: state
              entity_id: sensor.hue_scene_ensuite
              state: Movie
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.ensuite_ambiance
        # Kitchen
        - if:
            - condition: state
              entity_id: sensor.hue_scene_kitchen
              state: Movie
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.kitchen_ambiance
        # Hallway – downstairs
        - if:
            - condition: state
              entity_id: sensor.hue_scene_hallway_downstairs
              state: Movie
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.hallway_downstairs_evening
  mode: single
