- alias: 💡 | 💤 Wakeup light bedroom (daily at «wakeup light start» time)
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wakeup_light_start
  condition:
  - condition: state
    entity_id: timer.wakeup_grace_time
    state: idle
  action:
  - service: light.turn_on
    data:
      xy_color:
      - 0.4448
      - 0.4066
      brightness: 240
      transition: 1200
    entity_id: light.bedroom
  - delay: '02:20:00'
  - service: light.turn_off
    data: {}
    entity_id: light.bedroom
  mode: single
