- alias: 💡 | 🤖 VOCOlinc Living room light on (aroma diffuser on)
  id: 2e702914-5d9a-432a-8b8e-06d80ee2cdbf
  trigger:
    - platform: state
      entity_id: humidifier.vocolinc_flb_living_room
      from: "off"
      to: "on"
    - platform: state
      entity_id: sensor.hue_scene_living_room
      to: ~
  condition:
    - condition: state
      entity_id: humidifier.vocolinc_flb_living_room
      state: "on"
  action:
    - service: light.turn_on
      data:
        # yamllint disable rule:brackets
        rgb_color: [200, 255, 145]
        # Brightness is based on the active Hue scene in the Living room
        brightness: >-
          {% set scene = states('sensor.hue_scene_living_room') %}
          {% if scene in ['Ambiance', 'Movie (ambiance)'] %}
            40
          {% elif scene in ['Active', 'Daytime'] %}
            100
          {% elif scene == 'Movie' %}
            25
          {% elif scene == '<Off>' %}
            160
          {% endif %}
      target:
        entity_id: light.vocolinc_flb_living_room
  mode: single
- alias: 💡 | 🤖 VOCOlinc Living room light off (aroma diffuser off)
  id: dee9b3f1-4ffb-40de-b133-6dee43208b0d
  trigger:
    - platform: state
      entity_id: humidifier.vocolinc_flb_living_room
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.vocolinc_flb_living_room
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.vocolinc_flb_living_room
  mode: single
