- alias: Wardrobe light on
  id: f30e4af7-6b31-4062-8f12-25fde6ae3577
  triggers:
    - trigger: state
      entity_id: binary_sensor.presence_63
      from: "off"
      to: "on"
  conditions:
    - condition: numeric_state
      entity_id: sensor.lightlevel_65
      below: 50
    # Only switch on the lights under normal circumstances (i.e. the alarm is
    # either disarmed or "Armed night")
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  actions:
    - if:
        - condition: state
          entity_id: sensor.time_of_day
          state:
            - dusk
            - night
      then:
        - if:
            - condition: state
              entity_id: input_boolean.everyone_asleep
              state: "on"
          then:
            # Nighttime (everyone asleep)
            - action: scene.turn_on
              target:
                entity_id: scene.wardrobe_nighttime
          else:
            # Evenings
            - action: scene.turn_on
              target:
                entity_id: scene.wardrobe_bright
      else:
        # Daytime
        - action: scene.turn_on
          target:
            entity_id: scene.wardrobe_concentrate
  mode: single
- alias: Wardrobe light off
  id: 07ec0f12-cedd-4584-a143-8dba0fcecb9c
  triggers:
    - trigger: state
      entity_id: sensor.hue_scene_wardrobe
      not_to: «Off»
    - trigger: state
      entity_id: binary_sensor.presence_63
      from: "off"
      to: "on"
  conditions:
    # Only act under normal circumstances (i.e. the alarm is disarmed)
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state:
        - disarmed
        - armed_night
  actions:
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.presence_63
          from: "on"
          to: "off"
      continue_on_timeout: true
      timeout: "00:28:00"
    - delay: "00:02:00"
    - action: light.turn_off
      entity_id: light.wardrobe
  mode: restart
