- alias: 📱 | ⏰ Trash reminder (Black and Green bins)
  id: 992518b0-4f2f-4a35-b262-c882d6330996
  trigger:
    # Remind at 21:00 the day _before_ pickup
    - platform: time
      at: "21:00:00"
  condition:
    - condition: state
      entity_id: sensor.afvalwijzer_tomorrow
      state:
        - restafval
        - gft
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Reminder
          group: chores
          title: ♻️ Trash reminder
          message: >-
            Don't forget to put the
              {%- if is_state('sensor.afvalwijzer_tomorrow', 'restafval')
                %} <strong>black bin</strong>
              {%- elif is_state('sensor.afvalwijzer_tomorrow', 'gft')
                %} <strong>green bin</strong>
              {%- endif
            %} outside!
  mode: single
- alias: 📱 | ⏰ Trash reminder (Paper)
  id: 1f0e4981-921e-426f-a77d-05a1e6b8f478
  trigger:
    # Remind at 08:30 on the day of pickup
    - platform: time
      at: "08:30:00"
  condition:
    - condition: state
      entity_id: sensor.afvalwijzer_today
      state: papier
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Reminder
          group: chores
          title: 📦 Trash reminder
          message: Don't forget to put the <strong>paper</strong> outside!
  mode: single
