- alias: 📺/🔊 | 🚪/📱 Pause Android TV (doorbell rang; phone ringing)
  id: 87c17fff-a8e1-4c5a-8e31-e8ede68d7899
  trigger:
    - platform: state
      id: doorbell
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
    - platform: state
      entity_id:
        - sensor.pixel_9_pro_phone_state
        - sensor.sm_g990b2_phone_state
      to: ringing
  condition:
    - condition: state
      entity_id: media_player.epson_eh_ls800b
      state: playing
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.epson_eh_ls800b
  mode: single
  max_exceeded: silent
