- alias: 🤯/💧 | 📱 Send notification (water detected)
  id: e604c349-9733-4d0c-bb6f-199dd62f1004
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.water_59
        - binary_sensor.water_82
      from: "off"
      to: "on"
  condition: []
  action:
    # Explicitly block any further runs of this automation while the
    # notification is up (i.e. once a notification is up, no additional
    # notifications are raised)
    - service: script.persistent_notification
      data:
        group: calamity
        channel: Alert
        criticalNotification: true
        title: Leak detected!
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} detected water!
  mode: single
  max_exceeded: silent
- alias: 🤯/💧 | 🔊 Sound the alarm (water detected when someone home)
  id: 761dc98c-6444-4782-8295-26dd8caaad59
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.water_59
        - binary_sensor.water_82
      from: "off"
      to: "on"
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    - repeat:
        # Short pulses for 2 minutes – just to get people's attention...
        count: 8
        sequence:
          - service: switch.turn_on
            entity_id: switch.warning_device_8
          - delay: 2
          - service: switch.turn_off
            entity_id: switch.warning_device_8
          - delay: 13
  mode: single
- alias: 🤯/🔥 | 📱 Send notification (smoke detected)
  id: 1166dfdf-0375-4834-aa52-188c78d3bbdd
  trigger:
    - platform: state
      entity_id: binary_sensor.fire_81
      from: "off"
      to: "on"
  condition: []
  action:
    # Explicitly block any further runs of this automation while the
    # notification is up
    - service: script.persistent_notification
      data:
        group: calamity
        channel: Critical
        importance: high
        criticalNotification: true
        title: Smoke detected!
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} detected smoke!
  mode: single
  max_exceeded: silent
- alias: 🤯/🔥 | 🔊 Sound the alarm (smoke detected)
  id: 3e33958b-6f90-4612-afd0-d0078e054e92
  trigger:
    - platform: state
      entity_id: binary_sensor.fire_81
      from: "off"
      to: "on"
      # Hold state for 1 minute so we don't raise hell on a false alarm...
      for: "00:01:00"
  condition: []
  # Sound the alarm for 15 minutes or until the smoke detector clears. The goal
  # is to draw as much attention as possible regardless of whether someone is
  # home – the neighbours might notice and call the Fire department. If after
  # 15 minutes the alarm is still sounding, it has probably outlives its
  # usefulness...
  action:
    - service: switch.turn_on
      entity_id: switch.warning_device_8
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.fire_81
          from: "on"
          to: "off"
      timeout: "00:15:00"
      continue_on_timeout: true
    - service: switch.turn_off
      entity_id: switch.warning_device_8
  mode: single
