- alias: 🤯/💧 | 📱 Send notification (water detected)
  id: e604c349-9733-4d0c-bb6f-199dd62f1004
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.water_59
        - binary_sensor.water_82
      from: "off"
      to: "on"
  condition: []
  action:
    # Explicitly block any further runs of this automation while the
    # notification is up (i.e. once a notification is up, no additional
    # notifications are raised)
    - service: script.persistent_notification
      data:
        group: calamity
        channel: Alert
        criticalNotification: true
        title: Leak detected!
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} detected water!
  mode: single
  max_exceeded: silent
- alias: 🤯/💧 | 🔊 Sound the alarm (water detected when someone home)
  id: 761dc98c-6444-4782-8295-26dd8caaad59
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.water_59
        - binary_sensor.water_82
      from: "off"
      to: "on"
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    # Turn on the siren without blocking this script's execution
    - service: script.turn_on
      target:
        entity_id: script.sirens
      data:
        # Short pulses for 2 minutes; just to get people's attention
        variables:
          mode: pulse
          ontime: 120
    - wait_for_trigger:
        - platform: state
          entity_id:
            - binary_sensor.water_59
            - binary_sensor.water_82
          from: "on"
          to: "off"
      # No need to bother once the siren is off
      timeout: 120
      continue_on_timeout: false
    # Only silence the siren if _both_ sensors are clear
    - condition: state
      entity_id:
        - binary_sensor.water_59
        - binary_sensor.water_82
      state: "off"
    - service: script.sirens
      data:
        mode: none
  mode: single
- alias: 🤯/🔥 | 📱 Send notification (smoke detected)
  id: 1166dfdf-0375-4834-aa52-188c78d3bbdd
  trigger:
    - platform: state
      entity_id: binary_sensor.fire_81
      from: "off"
      to: "on"
  condition: []
  action:
    # Explicitly block any further runs of this automation while the
    # notification is up
    - service: script.persistent_notification
      data:
        group: calamity
        channel: Critical
        importance: high
        criticalNotification: true
        title: Smoke detected!
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} detected smoke!
  mode: single
  max_exceeded: silent
- alias: 🤯/🔥 | 🔊 Sound the alarm (smoke detected)
  id: 3e33958b-6f90-4612-afd0-d0078e054e92
  trigger:
    - platform: state
      entity_id: binary_sensor.fire_81
      from: "off"
      to: "on"
      # Hold state for 1 minute so we don't raise hell on a false alarm...
      for: "00:01:00"
  condition: []
  # Sound the alarm for 5 minutes (the maximum duration) or until the smoke
  # detector clears. The goal is to draw as much attention as possible
  # regardless of whether someone is home – the neighbours might notice and call
  # the Fire department. If after 5 minutes the alarm is still sounding, it has
  # probably outlived its usefulness...
  action:
    # Turn on the siren without blocking this script's execution
    - service: script.turn_on
      target:
        entity_id: script.sirens
      data:
        variables:
          mode: lselect
          ontime: 300
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.fire_81
          from: "on"
          to: "off"
      # No need to bother once the siren is off
      timeout: 300
      continue_on_timeout: false
    - service: script.sirens
      data:
        mode: none
  mode: single
