- alias: 🎄 | ✈️ Christmas tree on (Living Room lights on / someone home)
  id: 1f000056-9ced-4832-a6a0-4cbb93fb381e
  trigger:
    # Follow the Living Room lights (only when someone is home)
    - platform: state
      entity_id: light.living_room
      from: "off"
      to: "on"
    # If the Living Room lights are on when someone comes home, switch on the
    # Christmas tree
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: light.living_room
      state: "on"
    - condition: state
      entity_id: switch.on_off_plug_in_unit_6
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.on_off_plug_in_unit_6
  mode: single
- alias: 🎄 | 💡/✈️ Christmas tree off (Living Room lights off / everyone away)
  id: 7d791dff-0c3d-4774-91e6-648ff3348e53
  trigger:
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
      for: "00:05:00"
    - platform: state
      entity_id: light.living_room
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.on_off_plug_in_unit_6
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_6
  mode: single
- alias: 🎄 | ⏰ Christmas star on (dusk)
  id: cc862e68-ace8-4bc6-b78b-26db199d5ba2
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition: []
  action:
    - service: switch.turn_on
      entity_id: switch.on_off_plug_in_unit_7
  mode: single
- alias: 🎄 | ⏰ Christmas star off (dawn)
  id: 1f6b28e7-a390-4385-9d3d-52c756cb648f
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: night
      to: dawn
  condition: []
  action:
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_7
  mode: single
