- alias: 🎄 | 💡/🛡️ Christmas tree on (Living room Hue scene / alarm disarmed)
  id: 1f000056-9ced-4832-a6a0-4cbb93fb381e
  trigger:
    - platform: state
      entity_id: sensor.hue_scene_living_room
      to: ~
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
    # Ensure Living room has the correct Hue scene activated (the Home Alarm
    # state trigger cannot be guarded, so the check has to be done here)
    - condition: state
      entity_id: sensor.hue_scene_living_room
      state:
        - Active
        - Ambiance
        - Daytime
        - Movie
        - Movie (ambiance)
        - <Off> # During daytime only
  action:
    - choose:
        # Active
        - conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state: Active
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.festavia_string_lights_1
              data:
                effect: candle
        # Ambiance
        - conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state: Ambiance
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.festavia_string_lights_1
              data:
                effect: fire
                brightness_pct: 75
        # Daytime
        - conditions:
            # During daytime only (the Hue scene is guarded against this; the
            # off-state is not)
            - condition: state
              entity_id: sensor.time_of_day
              state: day
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - Daytime
                - <Off>
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.festavia_string_lights_1
              data:
                effect: opal
        # Movie
        - conditions:
            - condition: state
              entity_id: sensor.hue_scene_living_room
              state:
                - Movie
                - Movie (ambiance)
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.festavia_string_lights_1
              data:
                effect: fire
                brightness_pct: 25
      default:
        - stop: >-
            Not changing Christmas tree lights: Unknown Living room Hue scene
            "{{ states('sensor.hue_scene_living_room') }}"...
          error: true
  mode: single
  max_exceeded: silent
- alias: 🎄 | 💡/🛡️ Christmas tree off (Living room off / "Armed away")
  id: 7d791dff-0c3d-4774-91e6-648ff3348e53
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to:
        - armed_away
        - armed_vacation
    - platform: state
      id: lights_off
      entity_id: sensor.hue_scene_living_room
      to: <Off>
  condition:
    - condition: state
      entity_id: light.festavia_string_lights_1
      state: "on"
  action:
    - if:
        - condition: state
          entity_id: sensor.time_of_day
          state: day
        - condition: trigger
          id: lights_off
      then:
        - stop: Ignoring lights-off trigger during daytime...
    - service: light.turn_off
      entity_id: light.festavia_string_lights_1
  mode: single
- alias: 🎄 | ⏰ Christmas star on (dusk)
  id: cc862e68-ace8-4bc6-b78b-26db199d5ba2
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: day
      to: dusk
  condition:
    - condition: state
      entity_id: switch.on_off_plug_in_unit_7
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.on_off_plug_in_unit_7
  mode: single
- alias: 🎄 | ⏰ Christmas star off (dawn)
  id: 1f6b28e7-a390-4385-9d3d-52c756cb648f
  trigger:
    - platform: state
      entity_id: sensor.time_of_day
      from: night
      to: dawn
  condition:
    - condition: state
      entity_id: switch.on_off_plug_in_unit_7
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.on_off_plug_in_unit_7
  mode: single
