- alias: 💡 | 🚪 Blink Attic lights (doorbell rang)
  id: e08720ba-f27a-4308-aeef-275c606872b6
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition: []
  action:
    - repeat:
        count: 2
        sequence:
          - service: light.turn_on
            data:
              flash: short
            entity_id: light.attic
          - delay: "00:00:01"
  mode: single
- alias: 📱 | 🚪 Notify devices at home (doorbell rang; auto-dismissed)
  id: dd5d2646-26e3-4c71-aa3c-b7f49151606e
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: doorbell
          channel: Alert
          tag: doorbell
          targetDevices: home
          criticalNotification: true
          title: 🚪 Someone's at the front door!
          message: >-
            The doorbell just rang...
    # Wait up to one minutes for the front door to open
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.openclose_16
          from: "off"
          to: "on"
      timeout: 60
      continue_on_timeout: true
    - choose:
        # The door was not opened (i.e. the timer expired), update notification
        # with the latest Arlo capture
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger is none }}
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.persistent_notification
              data:
                variables:
                  group: doorbell
                  channel: Notification
                  tag: doorbell
                  targetDevices: home
                  title: 🚪 Missed someone at the front door...
                  message: >-
                    Arlo captured the situation:
                  image: >-
                    {{ state_attr('camera.aarlo_front', 'last_thumbnail') }}
      # Otherwise (i.e. the door was opened) dismiss the notification
      default:
        - service: persistent_notification.dismiss
          data:
            notification_id: doorbell
  mode: single
  max_exceeded: silent
- alias: 📹 | 🚪 Arlo snapshot (doorbell rang)
  id: dbfbeeab-04a2-404f-8771-5109ec19f729
  trigger:
    # Sensor stays active for 60 seconds, so there's no need to guard against
    # multiple triggers in rapid succession...
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition:
    # Don't disturb an active capture/recording-session
    - condition: not
      conditions:
        - condition: state
          entity_id: camera.aarlo_front
          state: recording
  action:
    - variables:
        filename: >-
          -{{ now() | as_timestamp | timestamp_custom('%Y%m%d%H%M') }}.jpg
        time_of_day: >-
          {% set time_of_day = states('sensor.time_of_day') %}
          {% if time_of_day in ['day', 'dusk', 'night', 'dawn'] %}
            -{{ time_of_day }}
          {% else %}
            -unknown
          {% endif %}
    - service: aarlo.camera_request_snapshot_to_file
      data:
        filename: >-
          /config/var/doorbell/front{{ time_of_day ~ filename }}
      entity_id: camera.aarlo_front
  mode: single
- alias: 📱 | 🚪 Send Arlo capture (camera active when doorbell rang)
  id: a811aa28-9084-4158-87b4-a063e9b8358c
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.aarlo_motion_front
      state: "on"
  action:
    - wait_for_trigger:
        - platform: event
          event_type: aarlo_capture_updated
      timeout: 60
      # If no capture comes in within one minute, it was (most likely) already
      # taken before the doorbell rang – continue and send the previously
      # available thumbnail...
      continue_on_timeout: true
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: doorbell
          channel: Notification
          criticalNotification: true
          title: 🚪 Someone rang the doorbell...
          message: >-
            Arlo captured the situation:
          image: >-
            {{ state_attr('camera.aarlo_front', 'last_thumbnail') }}
  mode: single
