- alias: 💡 | 🚪 Blink Attic lights (doorbell rang)
  id: e08720ba-f27a-4308-aeef-275c606872b6
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition: []
  action:
    - repeat:
        count: 2
        sequence:
          - service: light.turn_on
            data:
              flash: short
            entity_id: light.attic
          - delay: "00:00:01"
  mode: single
- alias: 📱 | 🚪 Notify devices at home (doorbell rang; auto-dismissed)
  id: dd5d2646-26e3-4c71-aa3c-b7f49151606e
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: doorbell
          channel: Alert
          tag: doorbell
          targetDevices: home
          criticalNotification: true
          title: 🚪 Someone's at the front door!
          message: >-
            The doorbell just rang...
    # Auto-dismiss when front door opens or after 2 minutes
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.openclose_16
          from: "off"
          to: "on"
      timeout: 120
      continue_on_timeout: true
    # Also causes the notification to be dismissed from all mobile devices
    - service: persistent_notification.dismiss
      data:
        notification_id: doorbell
  mode: single
  max_exceeded: silent
- alias: 📹 | 🚪 Arlo snapshot (doorbell rang)
  id: dbfbeeab-04a2-404f-8771-5109ec19f729
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition:
    # Don't disturb an active capture/recording-session
    - condition: not
      conditions:
        - condition: state
          entity_id: camera.aarlo_front
          state: recording
  action:
    - service: aarlo.camera_request_snapshot
      data: {}
      entity_id: camera.aarlo_front
  mode: single
- alias: 📱 | 🚪 Send Arlo capture (camera active when doorbell rang)
  id: a811aa28-9084-4158-87b4-a063e9b8358c
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id:
        - binary_sensor.aarlo_motion_front
        - sensor.aarlo_recent_activity_front
      state: "on"
  action:
    - wait_for_trigger:
        - platform: event
          event_type: aarlo_capture_updated
      timeout: 60
      # If no capture comes in within 1 minute, it was (most likely) already
      # taken before the doorbell was rang...
      continue_on_timeout: true
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: doorbell
          channel: Notification
          criticalNotification: true
          title: 🚪 Someone rang the doorbell...
          message: >-
            Arlo captured the situation:
          image: >-
            {{ state_attr('camera.aarlo_front', 'last_thumbnail') }}
  mode: single
