- alias: 📱 | 🗞️ Notify on CM4 availability (rpilocator RSS-feed)
  id: b33f3b51-4c6c-4963-81d1-fa8e5035c633
  trigger:
    - platform: event
      event_type: feedreader
      event_data:
        feed_url: https://rpilocator.com/feed/?cat=cm4
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: general
          channel: Alert
          targetDevices: my
          criticalNotification: true
          title: 🛍️ Compute Module 4 in-stock!
          action_1: Check it out!
          uri_1: >-
            {{ trigger.event.data.link }}
          message: >-
            {{ trigger.event.data.description }}
