- alias: ⏰ | 🧹 Housekeeper present
  id: 22862b80-0db9-41a1-8ab0-86bd72278540
  description: ""
  trigger:
    - platform: time
      at: !secret housekeeper_time
  condition:
    - condition: time
      weekday:
        - !secret housekeeper_day
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.housekeeper_present
    - delay: !secret housekeeper_duration
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.housekeeper_present
  mode: single
