- alias: 📱 | 👖 Notify on washing machine done
  id: 2c6b4dfe-90f0-40b8-a94a-4578edfd05ca
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_86_actual
      above: 100
      for: "00:03:00"
  condition: []
  action:
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_86_actual
          below: 10
          for: "00:20:00"
      timeout: "06:00:00"
      continue_on_timeout: false
    - variables:
        done_at: >-
          {{ now().hour ~ ':' ~now().minute }}
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Notification
          tag: washing_machine
          targetDevices: home
          title: 👖 Washing machine is done
          message: >-
            Time to take the laundry from the washing machine...
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.vibration_130 # Vibration sensor on door
          from: "off"
          to: "on"
      timeout: "02:00:00"
      continue_on_timeout: true
    # The washing machine turns itself off when it's done, so it's not possible
    # to use power consumption to determine if it has been emptied. Instead, if
    # the washing machine door is _not_ opened (i.e. trigger times out) within
    # two hours, assume it wasn't emptied and raise the alert level...
    - condition: template
      value_template: >-
        {{ wait.trigger is none }}
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Alert
          criticalNotification: true
          tag: washing_machine
          targetDevices: all
          title: 👖 Take the laundry from the washing machine!
          message: >-
            The washing machine finished at <strong>{{ done_at }}</strong>,
            time to take the laundry out!
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.vibration_130 # Vibration sensor on door
          from: "off"
          to: "on"
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: washing_machine
  mode: single
- alias: 📱 | 👖 Notify on dryer done
  id: 72c3b569-a2e9-4c9e-85f1-cf9bbf49c86e
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_83
      above: 500
      for: "00:20:00"
  condition: []
  action:
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 500
          for: "00:40:00"
      timeout: "06:00:00"
      continue_on_timeout: false
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Notification
          tag: dryer
          targetDevices: home
          title: 👖 Dryer is done
          message: >-
            Time to take the laundry from the dryer...
    # Dismiss notification when dryer is emptied (i.e. when it's switched off)
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.dryer
          from: "on"
          to: "off"
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: dryer
  mode: single
- alias: 📱 | 👖 Notify on dryer reservoir full
  id: 7dabd9e4-77b7-4663-9eb7-c5fd5efb96e1
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_83
      above: 500
      for: "00:01:00"
  condition: []
  action:
    # This isn't totally fool-proof (only triggers if the reservoir fills up
    # early in the run; conflicts with the "done"-automation in edge cases), but
    # serves as a good starting to point to judge the value of the
    # notification...
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 500
          for: "00:02:00"
      timeout: "00:20:00"
      continue_on_timeout: false
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Alert
          criticalNotification: true
          tag: dryer
          targetDevices: home
          title: 👖 Dryer reservoir is full!
          message: >-
            Empty the reservoir so the dryer can continue its run...
    # Dismiss notification when dryer reservoir is emptied (i.e. when it appears
    # to be continuing its run)
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          above: 500
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: dryer
  mode: single
  max_exceeded: silent
