- alias: 📱 | 👖 Notify on washing machine done
  id: 2c6b4dfe-90f0-40b8-a94a-4578edfd05ca
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_86_actual
      above: 100
      for: "00:01:00"
  condition: []
  action:
    - wait_for_trigger:
        - platform: numeric_state
          id: cycle_completed
          entity_id: sensor.power_86_actual
          below: 10
          for: "00:20:00"
        # Short-circuit on door open
        - platform: state
          entity_id: binary_sensor.vibration_130 # Vibration sensor on door
          from: "off"
          to: "on"
      timeout: "06:00:00"
      continue_on_timeout: false
    # Only continue on "cycle completed"-trigger
    - condition: trigger
      id: cycle_completed
    - variables:
        done_at: >-
          {{ now().hour ~ ':' ~now().minute }}
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Notification
          tag: washing_machine
          targetDevices: home
          title: 👖 Washing machine is done
          message: >-
            Time to take the laundry from the washing machine...
    # The washing machine turns itself off when it's done, so it's not possible
    # to use its power consumption to determine if it has been emptied (i.e
    # interacted with). Instead, use a sensor stuck to its door...
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.vibration_130
          from: "off"
          to: "on"
      timeout: "02:00:00"
      continue_on_timeout: true
    - choose:
        # Door got opened (i.e. triggered within timeout) – dismiss notification
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger is not none }}
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: washing_machine
      # Door was _not_ opened within two hours of completing the run (i.e.
      # trigger timed out) – raise the alert level...
      default:
        - service: script.turn_on
          target:
            entity_id: script.persistent_notification
          data:
            variables:
              group: chores
              channel: Alert
              criticalNotification: true
              tag: washing_machine
              targetDevices: all
              title: 👖 Take the laundry from the washing machine!
              message: >-
                The washing machine finished at <strong>{{ done_at }}</strong>,
                time to take the laundry out!
        - wait_for_trigger:
            - platform: state
              entity_id: binary_sensor.vibration_130
              from: "off"
              to: "on"
          timeout: "12:00:00"
          continue_on_timeout: false
        - service: persistent_notification.dismiss
          data:
            notification_id: washing_machine
  mode: single
  max_exceeded: silent
- alias: 📱 | 👖 Notify on dryer done
  id: 72c3b569-a2e9-4c9e-85f1-cf9bbf49c86e
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_83
      above: 500
      for: "00:01:00"
  condition: []
  action:
    - wait_for_trigger:
        # Anti-crease cycle takes about an hour; consider the dryer to be done
        # 20-minutes after that cycle started...
        - platform: numeric_state
          id: cycle_completed
          entity_id: sensor.power_83
          below: 500
          for: "00:20:00"
        # Short-circuit on water reservoir full
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 10
          for: "00:05:00"
        # Short-circuit on dryer switched off
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 1
          for: "00:01:00"
      timeout: "06:00:00"
      continue_on_timeout: false
    # Only continue on "cycle completed"-trigger
    - condition: trigger
      id: cycle_completed
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Notification
          tag: dryer
          targetDevices: home
          title: 👖 Dryer is done
          message: >-
            Time to take the laundry from the dryer...
    # Dismiss notification when dryer is emptied (i.e. switched off)
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 1
      timeout: "16:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: dryer
  mode: single
  max_exceeded: silent
- alias: 📱 | 👖 Notify on dryer reservoir full
  id: 7dabd9e4-77b7-4663-9eb7-c5fd5efb96e1
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_83
      above: 500
      for: "00:01:00"
  condition: []
  action:
    # If the water reservoir is full, the dryer stops immediately (as opposed
    # to running its anti-crease cycle) – power consumption goes to ± 2 Watt
    - wait_for_trigger:
        - platform: numeric_state
          id: reservoir_full
          entity_id: sensor.power_83
          below: 10
          for: "00:05:00"
        # Short-circuit on dryer switched off
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 1
          for: "00:01:00"
      # The shortest normal drying cycle (including the anti-crease cycle) takes
      # well over an hour, the actual "drying" part takes well _under_  an
      # hour – so after an hour it's safe to give up on detecting a full
      # reservoir; this furthermore ensures this automation never conflicts
      # with the "dryer done"-automation.
      timeout: "01:00:00"
      continue_on_timeout: false
    # Only continue on "reservoir full"-trigger
    - condition: trigger
      id: reservoir_full
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Alert
          criticalNotification: true
          tag: dryer
          targetDevices: home
          title: 👖 Dryer reservoir is full!
          message: >-
            Empty the reservoir so the dryer can continue its run...
    # Dismiss notification when dryer reservoir is emptied (i.e. when it appears
    # to be continuing its run) – the regular "dryer done"-automation will
    # restart (it aborts on a full water reservoir)
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          above: 500
          for: "00:01:00"
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: dryer
  mode: single
  max_exceeded: silent
