- alias: 📱 | 🧹 Notify on Neato D7 docking-failure
  id: 3a327d1c-422a-496a-8dd4-b3700fdb41e1
  trigger:
  - platform: template
    value_template: >-
      {%-
        if states('sensor.neato_d7_battery')|int < 95 and
          states('vacuum.neato_d7') != 'cleaning'
      -%}
        true
      {%- else -%}
        false
      {%- endif -%}
    for: "01:00:00"
  condition: []
  action:
  - service: script.persistent_notification_my_devices
    data:
      tag: system_general
      title: 🧹 Neato D7 failed to dock!
      message: >-
        {{ trigger.to_state.attributes.friendly_name }} battery-level has been
        below "battery-level at clean end" for
        {{ relative_time(trigger.to_state.last_changed) }}.
