- alias: 📱 | 🧹 Notify on Neato D7 docking-failure
  id: 3a327d1c-422a-496a-8dd4-b3700fdb41e1
  trigger:
    # It appears this is the most reliable way to detect whether Neato didn't
    # dock properly. Making it smarter (e.g. by relying on the state Neato
    # reports) doesn't work (as the reported state doesn't always reflect
    # reality – Neato can be driving around the Living room while its state
    # indicates it's "docked").
    - platform: numeric_state
      entity_id: sensor.neato_d7_battery
      below: 95
      for: "03:00:00"
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: general
          channel: Notification
          tag: neato_d7_failure
          targetDevices: home
          title: 🧹 Neato D7 failed to dock!
          message: >-
            Neato's battery-level has been below 95% for more than three
            hours – please ensure it has docked properly...
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.neato_d7_battery
          above: 95
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: neato_d7_failure
- alias: 📱 | 🧹 Notify on Neato D7 dustbin full
  id: f8ba3ff2-5319-40f6-8038-e75fa4f0fe02
  trigger:
    - platform: state
      entity_id: vacuum.neato_d7
      attribute: status
      to: Dust bin full
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: general
          channel: Notification
          tag: neato_d7_failure
          targetDevices: home
          title: 🧹 Neato D7 dustbin full
          message: >-
            Neato's dustbin is full – it will automatically resume cleaning when
            the dustbin is emptied...
    - wait_for_trigger:
        - platform: state
          entity_id: vacuum.neato_d7
          attribute: status
          from: Dust bin full
      timeout: "12:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: neato_d7_failure
