- alias: Pause Plex
  id: 87c17fff-a8e1-4c5a-8e31-e8ede68d7899
  triggers:
    - trigger: state
      id: doorbell
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
    - trigger: state
      entity_id:
        - sensor.pixel_9_pro_phone_state
        - sensor.sm_g990b2_phone_state
      to: ringing
  conditions:
    - condition: state
      entity_id: sensor.plex_shield_android_tv
      state: playing
  actions:
    - action: media_player.media_play_pause
      entity_id: media_player.shield
  mode: single
  max_exceeded: silent
