- alias: 📺/🔊 | 👋/🚪 Pause Shield TV (motion detected / doorbell rang)
  id: 87c17fff-a8e1-4c5a-8e31-e8ede68d7899
  trigger:
    - platform: state
      id: motion
      entity_id:
        - binary_sensor.aarlo_motion_front
        - binary_sensor.aarlo_motion_back
        - binary_sensor.aarlo_motion_balcony
      from: "off"
      to: "on"
    - platform: state
      id: doorbell
      entity_id: binary_sensor.vibration_43
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: media_player.nvidia_shield_tv
      state: playing
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.nvidia_shield_tv
  mode: single
  max_exceeded: silent
- alias: 📺 | 📱 Pause Shield TV (phone ringing)
  id: c1c84bf2-f550-4aca-b525-b03bc9b09a12
  trigger:
    - platform: state
      entity_id:
        - sensor.pixel_6_pro_phone_state
        - sensor.sm_g990b2_phone_state
      to: ringing
  condition:
    - condition: state
      entity_id: media_player.nvidia_shield_tv
      state: playing
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.nvidia_shield_tv
