# Note that input_boolean.everyone_asleep is toggled regardless of presence
# (i.e. it is also toggled when no-one is home). This keeps the overall setup
# as simple as possible. In the limited number of cases where asleep/awake-
# triggers should not cause things to happen when no-one is home, explicit
# exceptions are put in place...
- alias: ðŸ’¤ | ðŸ’¡ Everyone asleep (all lights off)
  id: cdec9ae5-d391-4826-a957-36fb823a73a7
  trigger:
    - platform: state
      from: "on"
      to: "off"
      for: "00:20:00"
      entity_id: group.light_inside_rooms
  condition:
    - condition: state
      entity_id: group.light_inside_rooms
      state: "off"
    - condition: state
      entity_id: sensor.time_of_day
      state: night
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.everyone_asleep
  mode: single
# The "everyone awake"-transition is intended to only happen once per day (at
# the first "wakeup" time of the day)
- alias: ðŸ’¤ | â° Everyone awake (daily at Â«wakeupÂ» time)
  id: dfe729c9-436a-4fdb-8970-b68492d9a1a2
  trigger:
    - platform: time
      at: input_datetime.wakeup
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.everyone_asleep
  mode: single
- alias: ðŸ’¤ Set next Â«wakeupÂ» (at Â«wakeupÂ» time)
  id: 01d828d8-da3e-432c-8beb-0f20392d2f8e
  trigger:
    - platform: time
      at: input_datetime.wakeup
  condition:
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: idle
  action:
    # The "grace-time" timer prevents the alarm (and related logic) from,
    # _unintentionally_ running multiple times in the same day. This occurs
    # when today's alarm triggers _before_ tomorrow's preset alarm time (as
    # defined below). If the alarm is to sound a second time during the same
    # day, simple cancel the timer...
    - service: timer.start
      entity_id: timer.wakeup_grace_time
    - choose:
        - conditions:
            - condition: time
              weekday: [fri, sat] # yamllint disable-line rule:brackets
          sequence:
            - service: input_datetime.set_datetime
              data:
                time: "09:00:00"
              entity_id: input_datetime.wakeup
        - conditions:
            - condition: time
              # yamllint disable-line rule:brackets
              weekday: [sun, mon, tue, wed, thu]
          sequence:
            - service: input_datetime.set_datetime
              data:
                time: "08:00:00"
              entity_id: input_datetime.wakeup
    # Unmute the wakeup alarm
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.wakeup_alarm_mute
  mode: single
- alias: ðŸ’¤ Set Â«wakeup light startÂ» time (Â«wakeupÂ» time change)
  id: 2067fdfb-bad3-40fb-aa7d-d35430dd5b78
  trigger:
    - platform: state
      entity_id: input_datetime.wakeup
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        time: >-
          {{
            (state_attr('input_datetime.wakeup', 'timestamp') | int - 1200) |
              timestamp_custom('%H:%M:%S', false)
          }}
      entity_id: input_datetime.wakeup_light_start
  mode: single
- alias: ðŸ’¡ | ðŸ’¤ Wakeup light bedroom (at Â«wakeup light startÂ» time)
  id: 8dfa00b1-9749-4b77-b0c9-7eceaf146bf6
  trigger:
    - platform: time
      at: input_datetime.wakeup_light_start
  condition:
    # N.B. Compared to the wakeup alarm automation (below) the omission of the
    # occupancy condition is intentionally (as the daily wakeup light is
    # considered to be part of occupancy simulation)
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: idle
    - condition: state
      entity_id: input_boolean.wakeup_alarm_mute
      state: "off"
  action:
    - service: light.turn_on
      data:
        xy_color:
          - 0.4448
          - 0.4066
        brightness: 240
        transition: 1200
      entity_id: light.bedroom
    - delay: "02:20:00"
    - service: light.turn_off
      entity_id: light.bedroom
  mode: single
- alias: ðŸ’¤ | ðŸ”Š Wakeup alarm bedroom (at Â«wakeupÂ» time)
  id: 4f9e08f9-b352-4945-b788-215e301ef883
  # N.B. This automation's name is used in the next automation!
  trigger:
    - platform: time
      at: input_datetime.wakeup
  condition:
    - condition: state
      state: home
      entity_id: group.family
    - condition: state
      entity_id: timer.wakeup_grace_time
      state: idle
    - condition: state
      entity_id: input_boolean.wakeup_alarm_mute
      state: "off"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.pi0_speaker_bedroom
        volume_level: 0.45
    - repeat:
        count: 4
        sequence:
          - service: media_player.play_media
            data:
              media_content_type: audio/mpeg
              # cspell: disable-next-line
              media_content_id: file:/var/lib/mopidy/media/4nsekecn.mp3
            entity_id: media_player.pi0_speaker_bedroom
          - delay: "00:00:20"
  mode: single
- alias: ðŸ’¤ | ðŸ•¹ï¸ Snooze wakeup alarm (Bedroom Smart Switches)
  id: 3c49fa1c-db0a-44ea-8fb3-8e57c515e310
  trigger:
    # Bedside Smart Switches
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition:
    # Only act if the wakeup alarm is sounding (i.e. in the Â±90 seconds after
    # its automation started)
    - condition: template
      value_template: >-
        {{
          (as_timestamp(now())|int - as_timestamp(
            state_attr('automation.wakeup_alarm_bedroom_at_wakeup_time',
              'last_triggered')
          ) | int(0) ) <= 90
        }}
  action:
    - service: automation.turn_off
      entity_id: automation.wakeup_alarm_bedroom_at_wakeup_time
    - service: automation.turn_on
      entity_id: automation.wakeup_alarm_bedroom_at_wakeup_time
    - service: media_player.media_stop
      entity_id: media_player.pi0_speaker_bedroom
  mode: single
  max_exceeded: silent
