- alias: 🕹️ Fireplace toggle (Magic Cube)
  id: fa8b26c2-5a32-4a64-a90a-c546465fef54
  trigger:
    - device_id: 7053d7e589bf4a4496cff59a24b7c83c
      domain: deconz
      platform: device
      type: remote_turned_clockwise
      subtype: ""
  condition: []
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.fireplace
  mode: single
- alias: 🕹️ Ensuite maximum brightness (Magic Cube)
  id: 0c5d2b27-0900-42d8-9b1e-8a412185cb34
  trigger:
    - device_id: 7053d7e589bf4a4496cff59a24b7c83c
      domain: deconz
      platform: device
      type: remote_double_tap_any_side
      subtype: ""
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.hue_white_light_1
      data:
        brightness: 255
  mode: single
- alias: 🕹️ Bedroom lights toggle (bedside Smart Switches)
  id: f03f5e56-2eaf-4bc0-8424-d316445b0236
  trigger:
    - device_id: da1237666189a9a364fa383795ba532d
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    - device_id: b26003b4b78afd0e5b2c3bcb3b06eeeb
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition:
    # Don't act when the wakeup alarm is sounding or snoozed (the light is
    # supposed to stay on in those cases)
    - condition: state
      entity_id: script.wakeup_alarm
      state: "off"
    - condition: state
      entity_id: timer.wakeup_snooze_time
      state: idle
  action:
    - service: light.toggle
      target:
        entity_id: light.bedroom
  mode: single
