- alias: 🚧 | ⏰ Time of Day
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -6.0
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 2.0
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 2.0
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -6.0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: |-
          {{ is_state_attr('sun.sun', 'rising', true) }}
      sequence:
      - choose:
        - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 2.0
            above: -6.0
          sequence:
          - service: input_select.select_option
            data:
              option: dawn
            entity_id: input_select.time_of_day
        - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: 2.0
          sequence:
          - service: input_select.select_option
            data:
              option: day
            entity_id: input_select.time_of_day
        default: []
    default:
    - choose:
      - conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          above: -6.0
          below: 2.0
        sequence:
        - service: input_select.select_option
          data:
            option: dusk
          entity_id: input_select.time_of_day
      - conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: -6.0
        sequence:
        - service: input_select.select_option
          data:
            option: night
          entity_id: input_select.time_of_day
      default: []
  mode: single
  max_exceeded: silent
# The "Nighttime" boolean is used in graphs to provide a dark(er) background
# when it's dark outside
- alias: 🚧 | 🌛 Nighttime on (at dusk)
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.time_of_day
    from: day
    to: dusk
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.nighttime
  mode: single
- alias: 🚧 | 🌛 Nighttime off (after dawn)
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.time_of_day
    from: dawn
    to: day
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.nighttime
  mode: single
