- alias: ðŸ“± | â° Trash reminder
  id: 992518b0-4f2f-4a35-b262-c882d6330996
  trigger:
    # Remind at 19:00 the day _before_ pickup
    - platform: time
      at: "19:00:00"
  condition:
    - condition: state
      entity_id: sensor.afvalwijzer_tomorrow
      state:
        - restafval
        - gft
        - papier
    # No need to remind when we're on vacation...
    - condition: state
      entity_id: input_boolean.alarm_vacation_mode
      state: "off"
  action:
    - variables:
        trash: >-
          {{ states('sensor.afvalwijzer_tomorrow') }}
        message: >-
          Don't forget to put the <strong>
            {%- if trash == 'restafval' -%}
              black bin
            {%- elif trash == 'gft' -%}
              green bin
            {%- elif trash == 'papier' -%}
              paper
            {%- endif -%}
          </strong> outside!
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: all
          channel: Reminder
          group: chores
          title: >-
            {{ 'ðŸ“¦' if trash == 'papier' else 'â™»ï¸' }} Trash reminder
          message: >-
            {{ message }}
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          expiry: "06:00:00"
          message: >-
            {{ message }}
  mode: single
  max_exceeded: silent
