- alias: ðŸ“± | â° Trash reminder
  id: 992518b0-4f2f-4a35-b262-c882d6330996
  trigger:
    # Remind at 19:00 the day _before_ pickup
    - platform: time
      at: "19:00:00"
  condition:
    - condition: state
      entity_id: sensor.afvalwijzer_tomorrow
      state:
        - restafval
        - gft
        - papier
  action:
    - variables:
        trash: >-
          {{ states('sensor.afvalwijzer_tomorrow') }}
    - if:
        - condition: state
          entity_id: group.family
          state: not_home
      then:
        # If no-one is home, delay the notification for up to 5-hours (until
        # midnight) in case someone gets home later...
        - wait_for_trigger:
            - platform: state
              entity_id: group.family
              from: not_home
              to: home
          timeout: "05:00:00"
          continue_on_timeout: false
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: home
          channel: Reminder
          group: chores
          title: >-
            {{ 'ðŸ“¦' if trash == 'papier' else 'â™»ï¸' }} Trash reminder
          message: >-
            Don't forget to put the <strong>
              {%- if trash == 'restafval' -%}
                black bin
              {%- elif trash == 'gft' -%}
                green bin
              {%- elif trash == 'papier' -%}
                paper
              {%- endif -%}
            </strong> outside!
  mode: single
  max_exceeded: silent
