- alias: 📱 | 👖 Notify on washing machine done
  id: 2c6b4dfe-90f0-40b8-a94a-4578edfd05ca
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_86_actual
      above: 100
      for: "00:01:00"
  condition: []
  action:
    - wait_for_trigger:
        - platform: numeric_state
          id: cycle_completed
          entity_id: sensor.power_86_actual
          below: 5
          for: "00:20:00"
        # Short-circuit on door open
        - platform: state
          entity_id: binary_sensor.openclose_158 # Contact sensor on door
          from: "off"
          to: "on"
      timeout: "06:00:00"
      continue_on_timeout: false
    # Only continue on "cycle completed"-trigger
    - condition: template
      value_template: >-
        {{ wait.trigger.id == 'cycle_completed' }}
    - variables:
        done_at: >-
          {{ now().hour ~ ':' ~ now().minute }}
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          group: chores
          channel: Notification
          tag: washing_machine
          targetDevices: home
          title: 👖 Washing machine is done
          message: >-
            Time to take the laundry from the washing machine...
    - service: script.turn_on
      target:
        entity_id: script.tts_queue
      data:
        variables:
          tag: washing_machine
          message: >-
            The washing machine is done.
    # The washing machine turns itself off when it's done, so it's not possible
    # to use its power consumption to determine if it has been emptied (i.e
    # interacted with). Instead, use a sensor stuck to its door...
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.openclose_158
          from: "off"
          to: "on"
      timeout: "02:00:00"
      continue_on_timeout: true
    - choose:
        # Door got opened (i.e. triggered within timeout) – dismiss notification
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger is not none }}
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: washing_machine
            - event: tts_queue_abort
              event_data:
                tag: washing_machine
      # Door was _not_ opened within two hours of completing the run (i.e.
      # trigger timed out) – raise the alert level...
      default:
        - variables:
            message: >-
              The washing machine finished at <strong>{{ done_at }}</strong>,
              time to take the laundry out!
        - service: script.turn_on
          target:
            entity_id: script.persistent_notification
          data:
            variables:
              group: chores
              channel: Alert
              criticalNotification: true
              tag: washing_machine
              targetDevices: all
              title: 👖 Take the laundry from the washing machine!
              message: >-
                {{ message }}
        - event: tts_queue_abort
          event_data:
            tag: washing_machine
        - service: script.turn_on
          target:
            entity_id: script.tts_queue
          data:
            variables:
              tag: washing_machine
              message: >-
                {{ message }}
        - wait_for_trigger:
            - platform: state
              entity_id: binary_sensor.openclose_158
              from: "off"
              to: "on"
          timeout: "12:00:00"
          continue_on_timeout: false
        - service: persistent_notification.dismiss
          data:
            notification_id: washing_machine
  mode: single
  max_exceeded: silent
- alias: 📱 | 👖 Notify on dryer done or reservoir full
  id: 72c3b569-a2e9-4c9e-85f1-cf9bbf49c86e
  initial_state: false
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_83
      above: 500
      for: "00:01:00"
  condition: []
  action:
    - wait_for_trigger:
        # Anti-crease cycle takes about an hour; consider the dryer to be done
        # 20-minutes after that cycle started...
        - platform: numeric_state
          id: cycle_completed
          entity_id: sensor.power_83
          below: 500
          for: "00:20:00"
        # If the water reservoir is full, the dryer stops immediately (as
        # opposed to running the anti-crease cycle) – power consumption goes
        # to ± 2 Watt
        - platform: numeric_state
          id: reservoir_full
          entity_id: sensor.power_83
          below: 10
          for: "00:05:00"
        # Short-circuit on dryer switched off
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 1
          for: "00:01:00"
      timeout: "06:00:00"
      continue_on_timeout: false
    - choose:
        # Cycle completed
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger.id == 'cycle_completed' }}
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.persistent_notification
              data:
                variables:
                  group: chores
                  channel: Notification
                  tag: dryer
                  targetDevices: home
                  title: 👖 Dryer is done
                  message: >-
                    Time to take the laundry from the dryer...
        # Water reservoir full
        - conditions:
            - condition: template
              value_template: >-
                {{ wait.trigger.id == 'reservoir_full' }}
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.persistent_notification
              data:
                variables:
                  group: chores
                  channel: Alert
                  criticalNotification: true
                  tag: dryer
                  targetDevices: home
                  title: 👖 Dryer reservoir is full!
                  message: >-
                    Empty the reservoir so the dryer can continue its run...
            - service: script.turn_on
              target:
                entity_id: script.tts_queue
              data:
                variables:
                  tag: dryer
                  message: >-
                    The dryer reservoir is full! Empty it so the dryer can
                    continue its run...
    # Dismiss notification when dryer is switched off or when it appears to be
    # continuing its run – the latter case mainly occurs if the  reservoir was
    # full, but can also be triggered if a second run is started without first
    # switching off the dryer...
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.power_83
          below: 1
        - platform: numeric_state
          entity_id: sensor.power_83
          above: 500
          for: "00:01:00"
      timeout: "16:00:00"
      continue_on_timeout: false
    - service: persistent_notification.dismiss
      data:
        notification_id: dryer
    - event: tts_queue_abort
      event_data:
        tag: dryer
  mode: single
  max_exceeded: silent
