- alias: ðŸ“± | ðŸ–¨ï¸ Notify on Prusa MINI+ finished printing
  id: 6b129c1c-a534-43b0-8308-113498507a33
  # Triggering on "Job Name" becoming unavailable allows the name of the job to
  # be used in the notification
  trigger:
    - platform: state
      entity_id: sensor.prusa_mini_job_name
      to: unavailable
  condition: []
  action:
    # Printer should be idle, otherwise something else is happening... The
    # various Prusa sensor's don't all change at exactly the same moment; if the
    # printer is not idle give, it a couple minutes.
    - if:
        - condition: not
          conditions:
            - condition: state
              entity_id: sensor.prusa_mini_printer_state
              state: idle
      then:
        - wait_for_trigger:
            - platform: state
              entity_id: sensor.prusa_mini_printer_state
              to: idle
          timeout: "00:03:00"
          continue_on_timeout: false
    - service: script.turn_on
      target:
        entity_id: script.persistent_notification
      data:
        variables:
          targetDevices: my
          channel: Reminder
          group: chores
          title: ðŸ–¨ï¸ Prusa MINI+ job completed
          message: >-
            The Prusa MINI+ has finished printing
            <b>{{ trigger.from_state.state }}</b>.
  mode: single
