services:
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:1.6.3
    user: 1000:1003
    command:
      - --streaming
      - --voice
      - en_US-danny-low
      - --length-scale
      - "1.15"
    volumes:
      - ./piper:/data
    ports:
      - 10200:10200
    restart: on-failure
