version: "3"
services:
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:1.2.0
    user: 1000:1003
    command:
      - --voice
      - en_US-amy-low
      - --length-scale
      - "1.15"
    volumes:
      - ./data:/data
    ports:
      - 10200:10200
    restart: unless-stopped
