- alias: 🛒 | 💤 Prepone «wakeup» time (Albert Heijn arriving early)
  id: 866031ac-89c6-4ab4-8a76-b0f67b910ae7
  trigger:
    - platform: state
      entity_id: sensor.last_notification_albert_heijn_eta
      not_to:
        - unavailabe
        - unknown
  condition:
    - condition: state
      entity_id: group.family
      state: home
    # When reloading templates, the above "not_to" doesn't adequately guard
    # against an invalid value for the sensor...
    - >-
      {{ has_value('sensor.last_notification_albert_heijn_eta') }}
    # Only act if ETA is in the future — the next condition assumes "future"
    # entails either today or tomorrow. Currently, no effort is made to guard
    # against ETA being further in the future; cross that bridge if we ever get
    # there...
    - >-
      {{
        states('sensor.last_notification_albert_heijn_eta') |
          as_datetime > now()
      }}
    # Prepone «wakeup» time if Albert Heijn's ETA is within a 15-minute interval
    # of it.
    # When «wakeup» time is in the past, we assume we're operating on tomorrow's
    # wakeup time (and simply add 24-hours to the comparison logic; this works
    # great except when changing to/from DST, alas 😉).
    - >-
      {% set eta = states('sensor.last_notification_albert_heijn_eta') |
          as_datetime - timedelta(minutes=15) %}
      {% set wakeup = today_at(states('input_datetime.wakeup')) %}
      {{
        eta <= wakeup or (
          now() > wakeup and eta <= (wakeup + timedelta(hours=24))
        )
      }}
  action:
    # Set «wakeup» time to 15-minutes _before_ Albert Heijn ETA — note that
    # "input_datetime.wakeup" only cares about the time component; the date
    # component is ignored
    - service: input_datetime.set_datetime
      data:
        datetime: >-
          {%
            set wakeup = states('sensor.last_notification_albert_heijn_eta') |
              as_datetime - timedelta(minutes=15)
          %}
          {#
            If the «wakeup» time would be _before_ the current time, set the
            alarm to sound ASAP. This is possible if an ETA change comes through
            very late (i.e., within the "wakeup grace-period").
          #}
          {% if wakeup <= now() %}
            {{ now() + timedelta(seconds=10) }}
          {% else %}
            {{ wakeup }}
          {% endif %}
      target:
        entity_id: input_datetime.wakeup
  mode: single
