name: Docker — sysmon-mqtt

"on": workflow_dispatch

jobs:
  build_push:
    name: Build and push Docker image
    runs-on: ubuntu-22.04
    environment: docker-ghcr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Retrieve sysmon-mqtt version
        id: sysmon
        run: |
          semver=$(
            ./extras/sysmon-mqtt/sysmon.sh --version | \
            grep -oE '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'
          )
          echo semver="v$semver" >> "$GITHUB_OUTPUT"
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            thijsputman/sysmon-mqtt
            ghcr.io/thijsputman/sysmon-mqtt
          # yamllint disable rule:line-length
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ steps.sysmon.outputs.semver }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.sysmon.outputs.semver }}
            type=semver,pattern={{major}},value=${{ steps.sysmon.outputs.semver }}
          # yamllint enable rule:line-length
          flavor: |
            latest=true
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./extras/sysmon-mqtt
          platforms: linux/amd64,linux/arm64,linux/arm/v7
